// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: books/v1/books.proto

package bookspbv1

import (
	_ "github.com/seeruk/tego/tegopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_books_v1_books_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBookRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetBookRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBookRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBookRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetBookRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetBookRequest_builder) Build() *GetBookRequest {
	m0 := &GetBookRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetBookResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Book *Book                  `protobuf:"bytes,1,opt,name=book"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_books_v1_books_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.xxx_hidden_Book
	}
	return nil
}

func (x *GetBookResponse) SetBook(v *Book) {
	x.xxx_hidden_Book = v
}

func (x *GetBookResponse) HasBook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Book != nil
}

func (x *GetBookResponse) ClearBook() {
	x.xxx_hidden_Book = nil
}

type GetBookResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Book *Book
}

func (b0 GetBookResponse_builder) Build() *GetBookResponse {
	m0 := &GetBookResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Book = b.Book
	return m0
}

type Book struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Author      *string                `protobuf:"bytes,3,opt,name=author"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_books_v1_books_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Book) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		if x.xxx_hidden_Author != nil {
			return *x.xxx_hidden_Author
		}
		return ""
	}
	return ""
}

func (x *Book) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Book) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Book) SetAuthor(v string) {
	x.xxx_hidden_Author = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Book) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Book) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Book) HasAuthor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Book) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Book) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *Book) ClearAuthor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Author = nil
}

type Book_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     *string
	Title  *string
	Author *string
}

func (b0 Book_builder) Build() *Book {
	m0 := &Book{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Title = b.Title
	}
	if b.Author != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Author = b.Author
	}
	return m0
}

var File_books_v1_books_proto protoreflect.FileDescriptor

const file_books_v1_books_proto_rawDesc = "" +
	"\n" +
	"\x14books/v1/books.proto\x12\bbooks.v1\x1a\x12tego/options.proto\" \n" +
	"\x0eGetBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetBookResponse\x12\"\n" +
	"\x04book\x18\x01 \x01(\v2\x0e.books.v1.BookR\x04book\"D\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author2M\n" +
	"\vBookService\x12>\n" +
	"\aGetBook\x12\x18.books.v1.GetBookRequest\x1a\x19.books.v1.GetBookResponseB\x82\x01҅\n" +
	";\n" +
	"9github.com/seeruk/tego/examples/error-mapping/books;booksZAgithub.com/seeruk/tego/examples/error-mapping/bookspbv1;bookspbv1b\beditionsp\xe9\a"

var file_books_v1_books_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_books_v1_books_proto_goTypes = []any{
	(*GetBookRequest)(nil),  // 0: books.v1.GetBookRequest
	(*GetBookResponse)(nil), // 1: books.v1.GetBookResponse
	(*Book)(nil),            // 2: books.v1.Book
}
var file_books_v1_books_proto_depIdxs = []int32{
	2, // 0: books.v1.GetBookResponse.book:type_name -> books.v1.Book
	0, // 1: books.v1.BookService.GetBook:input_type -> books.v1.GetBookRequest
	1, // 2: books.v1.BookService.GetBook:output_type -> books.v1.GetBookResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_books_v1_books_proto_init() }
func file_books_v1_books_proto_init() {
	if File_books_v1_books_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_books_v1_books_proto_rawDesc), len(file_books_v1_books_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_books_v1_books_proto_goTypes,
		DependencyIndexes: file_books_v1_books_proto_depIdxs,
		MessageInfos:      file_books_v1_books_proto_msgTypes,
	}.Build()
	File_books_v1_books_proto = out.File
	file_books_v1_books_proto_goTypes = nil
	file_books_v1_books_proto_depIdxs = nil
}
