// Code generated by protoc-gen-tego. DO NOT EDIT.
package kitchensink

import (
	errors "errors"
	tego "github.com/seeruk/tego"
	kitchensinkpbv1 "github.com/seeruk/tego/examples/kitchen-sink/kitchensinkpbv1"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	time "time"
)

type Status uint

const (
	StatusUnspecified Status = 0
	StatusActive      Status = 1
	StatusArchived    Status = 2
)

type ChoiceValue interface {
	isChoiceValue()
}

type ChoiceText struct {
	Text string
}

func (ChoiceText) isChoiceValue() {}

type ChoiceNumber struct {
	Number int32
}

func (ChoiceNumber) isChoiceValue() {}

type KitchenSink struct {
	BoolValue     bool
	Int32Value    int32
	Sint32Value   int32
	Sfixed32Value int32
	Uint32Value   uint32
	Fixed32Value  uint32
	Int64Value    int
	Sint64Value   int
	Sfixed64Value int
	Uint64Value   uint
	Fixed64Value  uint
	FloatValue    float32
	DoubleValue   float64
	StringValue   string
	BytesValue    []byte
	Status        Status
	Tags          []string
	Counts        map[string]int32
	WrappedBool   *bool
	WrappedString *string
	CreatedAt     time.Time
	TTL           time.Duration
	StructValue   tego.Struct
	DynamicValue  tego.Value
	ListValue     tego.ListValue
	AnyValue      *anypb.Any
	EmptyValue    struct{}
	Choice        Choice
}

type Choice struct {
	Value ChoiceValue
}

func KitchenSinkFromProto(source *kitchensinkpbv1.KitchenSink) KitchenSink {
	var target KitchenSink
	if source == nil {
		return target
	}
	target.BoolValue = source.GetBoolValue()
	target.Int32Value = source.GetInt32Value()
	target.Sint32Value = source.GetSint32Value()
	target.Sfixed32Value = source.GetSfixed32Value()
	target.Uint32Value = source.GetUint32Value()
	target.Fixed32Value = source.GetFixed32Value()
	target.Int64Value = int(source.GetInt64Value())
	target.Sint64Value = int(source.GetSint64Value())
	target.Sfixed64Value = int(source.GetSfixed64Value())
	target.Uint64Value = uint(source.GetUint64Value())
	target.Fixed64Value = uint(source.GetFixed64Value())
	target.FloatValue = source.GetFloatValue()
	target.DoubleValue = source.GetDoubleValue()
	target.StringValue = source.GetStringValue()
	target.BytesValue = source.GetBytesValue()
	target.Status = Status(source.GetStatus())
	tags := make([]string, 0, len(source.GetTags()))
	for _, tagsItem := range source.GetTags() {
		tags = append(tags, tagsItem)
	}
	target.Tags = tags
	counts := make(map[string]int32, len(source.GetCounts()))
	for countsKey, countsValue := range source.GetCounts() {
		counts[countsKey] = countsValue
	}
	target.Counts = counts
	var wrappedBool *bool
	if source.GetWrappedBool() != nil {
		wrappedBool = new(source.GetWrappedBool().GetValue())
	}
	target.WrappedBool = wrappedBool
	var wrappedString *string
	if source.GetWrappedString() != nil {
		wrappedString = new(source.GetWrappedString().GetValue())
	}
	target.WrappedString = wrappedString
	var createdAt time.Time
	if source.GetCreatedAt() != nil {
		createdAt = source.GetCreatedAt().AsTime()
	}
	target.CreatedAt = createdAt
	var ttl time.Duration
	if source.GetTtl() != nil {
		ttl = source.GetTtl().AsDuration()
	}
	target.TTL = ttl
	var structValue tego.Struct
	if source.GetStructValue() != nil {
		structValue = source.GetStructValue().AsMap()
	}
	target.StructValue = structValue
	var dynamicValue tego.Value
	if source.GetDynamicValue() != nil {
		dynamicValue = source.GetDynamicValue().AsInterface()
	}
	target.DynamicValue = dynamicValue
	var listValue tego.ListValue
	if source.GetListValue() != nil {
		listValue = source.GetListValue().AsSlice()
	}
	target.ListValue = listValue
	target.AnyValue = source.GetAnyValue()
	target.EmptyValue = struct{}{}
	target.Choice = ChoiceFromProto(source.GetChoice())
	return target
}

func KitchenSinkToProto(source KitchenSink) (*kitchensinkpbv1.KitchenSink, error) {
	target := new(kitchensinkpbv1.KitchenSink)
	target.SetBoolValue(source.BoolValue)
	target.SetInt32Value(source.Int32Value)
	target.SetSint32Value(source.Sint32Value)
	target.SetSfixed32Value(source.Sfixed32Value)
	target.SetUint32Value(source.Uint32Value)
	target.SetFixed32Value(source.Fixed32Value)
	target.SetInt64Value(int64(source.Int64Value))
	target.SetSint64Value(int64(source.Sint64Value))
	target.SetSfixed64Value(int64(source.Sfixed64Value))
	target.SetUint64Value(uint64(source.Uint64Value))
	target.SetFixed64Value(uint64(source.Fixed64Value))
	target.SetFloatValue(source.FloatValue)
	target.SetDoubleValue(source.DoubleValue)
	target.SetStringValue(source.StringValue)
	target.SetBytesValue(source.BytesValue)
	target.SetStatus(kitchensinkpbv1.Status(source.Status))
	tags := make([]string, 0, len(source.Tags))
	for _, tagsItem := range source.Tags {
		tags = append(tags, tagsItem)
	}
	target.SetTags(tags)
	counts := make(map[string]int32, len(source.Counts))
	for countsKey, countsValue := range source.Counts {
		counts[countsKey] = countsValue
	}
	target.SetCounts(counts)
	var wrappedBool *wrapperspb.BoolValue
	if source.WrappedBool != nil {
		wrappedBool = wrapperspb.Bool(*source.WrappedBool)
	}
	target.SetWrappedBool(wrappedBool)
	var wrappedString *wrapperspb.StringValue
	if source.WrappedString != nil {
		wrappedString = wrapperspb.String(*source.WrappedString)
	}
	target.SetWrappedString(wrappedString)
	target.SetCreatedAt(timestamppb.New(source.CreatedAt))
	target.SetTtl(durationpb.New(source.TTL))
	var structValue *structpb.Struct
	if source.StructValue != nil {
		structValue2, err := structpb.NewStruct(source.StructValue)
		if err != nil {
			return nil, err
		}
		structValue = structValue2
	}
	target.SetStructValue(structValue)
	dynamicValue, err := structpb.NewValue(source.DynamicValue)
	if err != nil {
		return nil, err
	}
	target.SetDynamicValue(dynamicValue)
	var listValue *structpb.ListValue
	if source.ListValue != nil {
		listValue2, err := structpb.NewList(source.ListValue)
		if err != nil {
			return nil, err
		}
		listValue = listValue2
	}
	target.SetListValue(listValue)
	target.SetAnyValue(source.AnyValue)
	target.SetEmptyValue(new(emptypb.Empty))
	choice, err := ChoiceToProto(source.Choice)
	if err != nil {
		return nil, err
	}
	target.SetChoice(choice)
	return target, nil
}

func (ks KitchenSink) ToProto() (*kitchensinkpbv1.KitchenSink, error) {
	return KitchenSinkToProto(ks)
}

func ChoiceFromProto(source *kitchensinkpbv1.Choice) Choice {
	var target Choice
	if source == nil {
		return target
	}
	switch source.WhichValue() {
	case kitchensinkpbv1.Choice_Text_case:
		target.Value = ChoiceText{Text: source.GetText()}
	case kitchensinkpbv1.Choice_Number_case:
		target.Value = ChoiceNumber{Number: source.GetNumber()}
	}
	return target
}

func ChoiceToProto(source Choice) (*kitchensinkpbv1.Choice, error) {
	target := new(kitchensinkpbv1.Choice)
	switch value := source.Value.(type) {
	case nil:
	case ChoiceText:
		target.SetText(value.Text)
	case *ChoiceText:
		if value != nil {
			target.SetText(value.Text)
		}
	case ChoiceNumber:
		target.SetNumber(value.Number)
	case *ChoiceNumber:
		if value != nil {
			target.SetNumber(value.Number)
		}
	default:
		return nil, errors.New("unsupported oneof implementation")
	}
	return target, nil
}

func (c Choice) ToProto() (*kitchensinkpbv1.Choice, error) {
	return ChoiceToProto(c)
}
