// Code generated by protoc-gen-tego. DO NOT EDIT.
package kitchensink

import (
	errors "errors"
	tego "github.com/seeruk/tego"
	kitchensinkpbv1 "github.com/seeruk/tego/examples/kitchen-sink/kitchensinkpbv1"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	time "time"
)

type Status uint

const (
	StatusUnspecified Status = 0
	StatusActive      Status = 1
	StatusArchived    Status = 2
)

type ChoiceValue interface {
	isChoiceValue()
}

type ChoiceText struct {
	Text string
}

func (ChoiceText) isChoiceValue() {}

type ChoiceNumber struct {
	Number int32
}

func (ChoiceNumber) isChoiceValue() {}

type KitchenSink struct {
	BoolValue          bool
	Int32Value         int32
	Sint32Value        int32
	Sfixed32Value      int32
	Uint32Value        uint32
	Fixed32Value       uint32
	Int64Value         int
	Sint64Value        int
	Sfixed64Value      int
	Uint64Value        uint
	Fixed64Value       uint
	FloatValue         float32
	DoubleValue        float64
	StringValue        string
	BytesValue         []byte
	Status             Status
	Tags               []string
	Counts             map[string]int32
	WrappedBool        *bool
	WrappedString      *string
	CreatedAt          time.Time
	TTL                time.Duration
	StructValue        tego.Struct
	DynamicValue       tego.Value
	ListValue          tego.ListValue
	AnyValue           *anypb.Any
	EmptyValue         struct{}
	Choice             Choice
	WrappedStrings     []*string
	WrappedStringsByID map[string]*string
	WrappedBools       []*bool
	WrappedBoolsByID   map[string]*bool
	CreatedAtHistory   []time.Time
	CreatedAtByID      map[string]time.Time
	TTLs               []time.Duration
	TTLsByID           map[string]time.Duration
	StructValues       []tego.Struct
	StructValuesByID   map[string]tego.Struct
	DynamicValues      []tego.Value
	DynamicValuesByID  map[string]tego.Value
	ListValues         []tego.ListValue
	ListValuesByID     map[string]tego.ListValue
	AnyValues          []*anypb.Any
	AnyValuesByID      map[string]*anypb.Any
	EmptyValues        []struct{}
	EmptyValuesByID    map[string]struct{}
}

type Choice struct {
	Value ChoiceValue
}

func KitchenSinkFromProto(source *kitchensinkpbv1.KitchenSink) KitchenSink {
	var target KitchenSink
	if source == nil {
		return target
	}
	target.BoolValue = source.GetBoolValue()
	target.Int32Value = source.GetInt32Value()
	target.Sint32Value = source.GetSint32Value()
	target.Sfixed32Value = source.GetSfixed32Value()
	target.Uint32Value = source.GetUint32Value()
	target.Fixed32Value = source.GetFixed32Value()
	target.Int64Value = int(source.GetInt64Value())
	target.Sint64Value = int(source.GetSint64Value())
	target.Sfixed64Value = int(source.GetSfixed64Value())
	target.Uint64Value = uint(source.GetUint64Value())
	target.Fixed64Value = uint(source.GetFixed64Value())
	target.FloatValue = source.GetFloatValue()
	target.DoubleValue = source.GetDoubleValue()
	target.StringValue = source.GetStringValue()
	target.BytesValue = source.GetBytesValue()
	target.Status = Status(source.GetStatus())
	tags := make([]string, 0, len(source.GetTags()))
	for _, tagsItem := range source.GetTags() {
		tags = append(tags, tagsItem)
	}
	target.Tags = tags
	counts := make(map[string]int32, len(source.GetCounts()))
	for countsKey, countsValue := range source.GetCounts() {
		counts[countsKey] = countsValue
	}
	target.Counts = counts
	var wrappedBool *bool
	if source.GetWrappedBool() != nil {
		wrappedBool = new(source.GetWrappedBool().GetValue())
	}
	target.WrappedBool = wrappedBool
	var wrappedString *string
	if source.GetWrappedString() != nil {
		wrappedString = new(source.GetWrappedString().GetValue())
	}
	target.WrappedString = wrappedString
	var createdAt time.Time
	if source.GetCreatedAt() != nil {
		createdAt = source.GetCreatedAt().AsTime()
	}
	target.CreatedAt = createdAt
	var ttl time.Duration
	if source.GetTtl() != nil {
		ttl = source.GetTtl().AsDuration()
	}
	target.TTL = ttl
	var structValue tego.Struct
	if source.GetStructValue() != nil {
		structValue = source.GetStructValue().AsMap()
	}
	target.StructValue = structValue
	var dynamicValue tego.Value
	if source.GetDynamicValue() != nil {
		dynamicValue = source.GetDynamicValue().AsInterface()
	}
	target.DynamicValue = dynamicValue
	var listValue tego.ListValue
	if source.GetListValue() != nil {
		listValue = source.GetListValue().AsSlice()
	}
	target.ListValue = listValue
	target.AnyValue = source.GetAnyValue()
	target.EmptyValue = struct{}{}
	target.Choice = ChoiceFromProto(source.GetChoice())
	wrappedStrings := make([]*string, 0, len(source.GetWrappedStrings()))
	for _, wrappedStringsItem := range source.GetWrappedStrings() {
		var wrappedStringsItemTego *string
		if wrappedStringsItem != nil {
			wrappedStringsItemTego = new(wrappedStringsItem.GetValue())
		}
		wrappedStrings = append(wrappedStrings, wrappedStringsItemTego)
	}
	target.WrappedStrings = wrappedStrings
	wrappedStringsByID := make(map[string]*string, len(source.GetWrappedStringsById()))
	for wrappedStringsByIDKey, wrappedStringsByIDValue := range source.GetWrappedStringsById() {
		var wrappedStringsByIDValueTego *string
		if wrappedStringsByIDValue != nil {
			wrappedStringsByIDValueTego = new(wrappedStringsByIDValue.GetValue())
		}
		wrappedStringsByID[wrappedStringsByIDKey] = wrappedStringsByIDValueTego
	}
	target.WrappedStringsByID = wrappedStringsByID
	wrappedBools := make([]*bool, 0, len(source.GetWrappedBools()))
	for _, wrappedBoolsItem := range source.GetWrappedBools() {
		var wrappedBoolsItemTego *bool
		if wrappedBoolsItem != nil {
			wrappedBoolsItemTego = new(wrappedBoolsItem.GetValue())
		}
		wrappedBools = append(wrappedBools, wrappedBoolsItemTego)
	}
	target.WrappedBools = wrappedBools
	wrappedBoolsByID := make(map[string]*bool, len(source.GetWrappedBoolsById()))
	for wrappedBoolsByIDKey, wrappedBoolsByIDValue := range source.GetWrappedBoolsById() {
		var wrappedBoolsByIDValueTego *bool
		if wrappedBoolsByIDValue != nil {
			wrappedBoolsByIDValueTego = new(wrappedBoolsByIDValue.GetValue())
		}
		wrappedBoolsByID[wrappedBoolsByIDKey] = wrappedBoolsByIDValueTego
	}
	target.WrappedBoolsByID = wrappedBoolsByID
	createdAtHistory := make([]time.Time, 0, len(source.GetCreatedAtHistory()))
	for _, createdAtHistoryItem := range source.GetCreatedAtHistory() {
		var createdAtHistoryItemTego time.Time
		if createdAtHistoryItem != nil {
			createdAtHistoryItemTego = createdAtHistoryItem.AsTime()
		}
		createdAtHistory = append(createdAtHistory, createdAtHistoryItemTego)
	}
	target.CreatedAtHistory = createdAtHistory
	createdAtByID := make(map[string]time.Time, len(source.GetCreatedAtById()))
	for createdAtByIDKey, createdAtByIDValue := range source.GetCreatedAtById() {
		var createdAtByIDValueTego time.Time
		if createdAtByIDValue != nil {
			createdAtByIDValueTego = createdAtByIDValue.AsTime()
		}
		createdAtByID[createdAtByIDKey] = createdAtByIDValueTego
	}
	target.CreatedAtByID = createdAtByID
	ttLs := make([]time.Duration, 0, len(source.GetTtls()))
	for _, ttLsItem := range source.GetTtls() {
		var ttLsItemTego time.Duration
		if ttLsItem != nil {
			ttLsItemTego = ttLsItem.AsDuration()
		}
		ttLs = append(ttLs, ttLsItemTego)
	}
	target.TTLs = ttLs
	ttLsByID := make(map[string]time.Duration, len(source.GetTtlsById()))
	for ttLsByIDKey, ttLsByIDValue := range source.GetTtlsById() {
		var ttLsByIDValueTego time.Duration
		if ttLsByIDValue != nil {
			ttLsByIDValueTego = ttLsByIDValue.AsDuration()
		}
		ttLsByID[ttLsByIDKey] = ttLsByIDValueTego
	}
	target.TTLsByID = ttLsByID
	structValues := make([]tego.Struct, 0, len(source.GetStructValues()))
	for _, structValuesItem := range source.GetStructValues() {
		var structValuesItemTego tego.Struct
		if structValuesItem != nil {
			structValuesItemTego = structValuesItem.AsMap()
		}
		structValues = append(structValues, structValuesItemTego)
	}
	target.StructValues = structValues
	structValuesByID := make(map[string]tego.Struct, len(source.GetStructValuesById()))
	for structValuesByIDKey, structValuesByIDValue := range source.GetStructValuesById() {
		var structValuesByIDValueTego tego.Struct
		if structValuesByIDValue != nil {
			structValuesByIDValueTego = structValuesByIDValue.AsMap()
		}
		structValuesByID[structValuesByIDKey] = structValuesByIDValueTego
	}
	target.StructValuesByID = structValuesByID
	dynamicValues := make([]tego.Value, 0, len(source.GetDynamicValues()))
	for _, dynamicValuesItem := range source.GetDynamicValues() {
		var dynamicValuesItemTego tego.Value
		if dynamicValuesItem != nil {
			dynamicValuesItemTego = dynamicValuesItem.AsInterface()
		}
		dynamicValues = append(dynamicValues, dynamicValuesItemTego)
	}
	target.DynamicValues = dynamicValues
	dynamicValuesByID := make(map[string]tego.Value, len(source.GetDynamicValuesById()))
	for dynamicValuesByIDKey, dynamicValuesByIDValue := range source.GetDynamicValuesById() {
		var dynamicValuesByIDValueTego tego.Value
		if dynamicValuesByIDValue != nil {
			dynamicValuesByIDValueTego = dynamicValuesByIDValue.AsInterface()
		}
		dynamicValuesByID[dynamicValuesByIDKey] = dynamicValuesByIDValueTego
	}
	target.DynamicValuesByID = dynamicValuesByID
	listValues := make([]tego.ListValue, 0, len(source.GetListValues()))
	for _, listValuesItem := range source.GetListValues() {
		var listValuesItemTego tego.ListValue
		if listValuesItem != nil {
			listValuesItemTego = listValuesItem.AsSlice()
		}
		listValues = append(listValues, listValuesItemTego)
	}
	target.ListValues = listValues
	listValuesByID := make(map[string]tego.ListValue, len(source.GetListValuesById()))
	for listValuesByIDKey, listValuesByIDValue := range source.GetListValuesById() {
		var listValuesByIDValueTego tego.ListValue
		if listValuesByIDValue != nil {
			listValuesByIDValueTego = listValuesByIDValue.AsSlice()
		}
		listValuesByID[listValuesByIDKey] = listValuesByIDValueTego
	}
	target.ListValuesByID = listValuesByID
	anyValues := make([]*anypb.Any, 0, len(source.GetAnyValues()))
	for _, anyValuesItem := range source.GetAnyValues() {
		anyValues = append(anyValues, anyValuesItem)
	}
	target.AnyValues = anyValues
	anyValuesByID := make(map[string]*anypb.Any, len(source.GetAnyValuesById()))
	for anyValuesByIDKey, anyValuesByIDValue := range source.GetAnyValuesById() {
		anyValuesByID[anyValuesByIDKey] = anyValuesByIDValue
	}
	target.AnyValuesByID = anyValuesByID
	emptyValues := make([]struct{}, 0, len(source.GetEmptyValues()))
	for range source.GetEmptyValues() {
		emptyValues = append(emptyValues, struct{}{})
	}
	target.EmptyValues = emptyValues
	emptyValuesByID := make(map[string]struct{}, len(source.GetEmptyValuesById()))
	for emptyValuesByIDKey := range source.GetEmptyValuesById() {
		emptyValuesByID[emptyValuesByIDKey] = struct{}{}
	}
	target.EmptyValuesByID = emptyValuesByID
	return target
}

func KitchenSinkToProto(source KitchenSink) (*kitchensinkpbv1.KitchenSink, error) {
	target := new(kitchensinkpbv1.KitchenSink)
	target.SetBoolValue(source.BoolValue)
	target.SetInt32Value(source.Int32Value)
	target.SetSint32Value(source.Sint32Value)
	target.SetSfixed32Value(source.Sfixed32Value)
	target.SetUint32Value(source.Uint32Value)
	target.SetFixed32Value(source.Fixed32Value)
	target.SetInt64Value(int64(source.Int64Value))
	target.SetSint64Value(int64(source.Sint64Value))
	target.SetSfixed64Value(int64(source.Sfixed64Value))
	target.SetUint64Value(uint64(source.Uint64Value))
	target.SetFixed64Value(uint64(source.Fixed64Value))
	target.SetFloatValue(source.FloatValue)
	target.SetDoubleValue(source.DoubleValue)
	target.SetStringValue(source.StringValue)
	target.SetBytesValue(source.BytesValue)
	target.SetStatus(kitchensinkpbv1.Status(source.Status))
	tags := make([]string, 0, len(source.Tags))
	for _, tagsItem := range source.Tags {
		tags = append(tags, tagsItem)
	}
	target.SetTags(tags)
	counts := make(map[string]int32, len(source.Counts))
	for countsKey, countsValue := range source.Counts {
		counts[countsKey] = countsValue
	}
	target.SetCounts(counts)
	var wrappedBool *wrapperspb.BoolValue
	if source.WrappedBool != nil {
		wrappedBool = wrapperspb.Bool(*source.WrappedBool)
	}
	target.SetWrappedBool(wrappedBool)
	var wrappedString *wrapperspb.StringValue
	if source.WrappedString != nil {
		wrappedString = wrapperspb.String(*source.WrappedString)
	}
	target.SetWrappedString(wrappedString)
	target.SetCreatedAt(timestamppb.New(source.CreatedAt))
	target.SetTtl(durationpb.New(source.TTL))
	var structValue *structpb.Struct
	if source.StructValue != nil {
		structValue2, err := structpb.NewStruct(source.StructValue)
		if err != nil {
			return nil, err
		}
		structValue = structValue2
	}
	target.SetStructValue(structValue)
	dynamicValue, err := structpb.NewValue(source.DynamicValue)
	if err != nil {
		return nil, err
	}
	target.SetDynamicValue(dynamicValue)
	var listValue *structpb.ListValue
	if source.ListValue != nil {
		listValue2, err := structpb.NewList(source.ListValue)
		if err != nil {
			return nil, err
		}
		listValue = listValue2
	}
	target.SetListValue(listValue)
	target.SetAnyValue(source.AnyValue)
	target.SetEmptyValue(new(emptypb.Empty))
	choice, err := ChoiceToProto(source.Choice)
	if err != nil {
		return nil, err
	}
	target.SetChoice(choice)
	wrappedStrings := make([]*wrapperspb.StringValue, 0, len(source.WrappedStrings))
	for _, wrappedStringsItem := range source.WrappedStrings {
		var wrappedStringsItemProto *wrapperspb.StringValue
		if wrappedStringsItem != nil {
			wrappedStringsItemProto = wrapperspb.String(*wrappedStringsItem)
		}
		wrappedStrings = append(wrappedStrings, wrappedStringsItemProto)
	}
	target.SetWrappedStrings(wrappedStrings)
	wrappedStringsByID := make(map[string]*wrapperspb.StringValue, len(source.WrappedStringsByID))
	for wrappedStringsByIDKey, wrappedStringsByIDValue := range source.WrappedStringsByID {
		var wrappedStringsByIDValueProto *wrapperspb.StringValue
		if wrappedStringsByIDValue != nil {
			wrappedStringsByIDValueProto = wrapperspb.String(*wrappedStringsByIDValue)
		}
		wrappedStringsByID[wrappedStringsByIDKey] = wrappedStringsByIDValueProto
	}
	target.SetWrappedStringsById(wrappedStringsByID)
	wrappedBools := make([]*wrapperspb.BoolValue, 0, len(source.WrappedBools))
	for _, wrappedBoolsItem := range source.WrappedBools {
		var wrappedBoolsItemProto *wrapperspb.BoolValue
		if wrappedBoolsItem != nil {
			wrappedBoolsItemProto = wrapperspb.Bool(*wrappedBoolsItem)
		}
		wrappedBools = append(wrappedBools, wrappedBoolsItemProto)
	}
	target.SetWrappedBools(wrappedBools)
	wrappedBoolsByID := make(map[string]*wrapperspb.BoolValue, len(source.WrappedBoolsByID))
	for wrappedBoolsByIDKey, wrappedBoolsByIDValue := range source.WrappedBoolsByID {
		var wrappedBoolsByIDValueProto *wrapperspb.BoolValue
		if wrappedBoolsByIDValue != nil {
			wrappedBoolsByIDValueProto = wrapperspb.Bool(*wrappedBoolsByIDValue)
		}
		wrappedBoolsByID[wrappedBoolsByIDKey] = wrappedBoolsByIDValueProto
	}
	target.SetWrappedBoolsById(wrappedBoolsByID)
	createdAtHistory := make([]*timestamppb.Timestamp, 0, len(source.CreatedAtHistory))
	for _, createdAtHistoryItem := range source.CreatedAtHistory {
		createdAtHistory = append(createdAtHistory, timestamppb.New(createdAtHistoryItem))
	}
	target.SetCreatedAtHistory(createdAtHistory)
	createdAtByID := make(map[string]*timestamppb.Timestamp, len(source.CreatedAtByID))
	for createdAtByIDKey, createdAtByIDValue := range source.CreatedAtByID {
		createdAtByID[createdAtByIDKey] = timestamppb.New(createdAtByIDValue)
	}
	target.SetCreatedAtById(createdAtByID)
	ttLs := make([]*durationpb.Duration, 0, len(source.TTLs))
	for _, ttLsItem := range source.TTLs {
		ttLs = append(ttLs, durationpb.New(ttLsItem))
	}
	target.SetTtls(ttLs)
	ttLsByID := make(map[string]*durationpb.Duration, len(source.TTLsByID))
	for ttLsByIDKey, ttLsByIDValue := range source.TTLsByID {
		ttLsByID[ttLsByIDKey] = durationpb.New(ttLsByIDValue)
	}
	target.SetTtlsById(ttLsByID)
	structValues := make([]*structpb.Struct, 0, len(source.StructValues))
	for _, structValuesItem := range source.StructValues {
		var structValuesItemProto *structpb.Struct
		if structValuesItem != nil {
			structValuesItemProto2, err := structpb.NewStruct(structValuesItem)
			if err != nil {
				return nil, err
			}
			structValuesItemProto = structValuesItemProto2
		}
		structValues = append(structValues, structValuesItemProto)
	}
	target.SetStructValues(structValues)
	structValuesByID := make(map[string]*structpb.Struct, len(source.StructValuesByID))
	for structValuesByIDKey, structValuesByIDValue := range source.StructValuesByID {
		var structValuesByIDValueProto *structpb.Struct
		if structValuesByIDValue != nil {
			structValuesByIDValueProto2, err := structpb.NewStruct(structValuesByIDValue)
			if err != nil {
				return nil, err
			}
			structValuesByIDValueProto = structValuesByIDValueProto2
		}
		structValuesByID[structValuesByIDKey] = structValuesByIDValueProto
	}
	target.SetStructValuesById(structValuesByID)
	dynamicValues := make([]*structpb.Value, 0, len(source.DynamicValues))
	for _, dynamicValuesItem := range source.DynamicValues {
		dynamicValuesItemProto, err := structpb.NewValue(dynamicValuesItem)
		if err != nil {
			return nil, err
		}
		dynamicValues = append(dynamicValues, dynamicValuesItemProto)
	}
	target.SetDynamicValues(dynamicValues)
	dynamicValuesByID := make(map[string]*structpb.Value, len(source.DynamicValuesByID))
	for dynamicValuesByIDKey, dynamicValuesByIDValue := range source.DynamicValuesByID {
		dynamicValuesByIDValueProto, err := structpb.NewValue(dynamicValuesByIDValue)
		if err != nil {
			return nil, err
		}
		dynamicValuesByID[dynamicValuesByIDKey] = dynamicValuesByIDValueProto
	}
	target.SetDynamicValuesById(dynamicValuesByID)
	listValues := make([]*structpb.ListValue, 0, len(source.ListValues))
	for _, listValuesItem := range source.ListValues {
		var listValuesItemProto *structpb.ListValue
		if listValuesItem != nil {
			listValuesItemProto2, err := structpb.NewList(listValuesItem)
			if err != nil {
				return nil, err
			}
			listValuesItemProto = listValuesItemProto2
		}
		listValues = append(listValues, listValuesItemProto)
	}
	target.SetListValues(listValues)
	listValuesByID := make(map[string]*structpb.ListValue, len(source.ListValuesByID))
	for listValuesByIDKey, listValuesByIDValue := range source.ListValuesByID {
		var listValuesByIDValueProto *structpb.ListValue
		if listValuesByIDValue != nil {
			listValuesByIDValueProto2, err := structpb.NewList(listValuesByIDValue)
			if err != nil {
				return nil, err
			}
			listValuesByIDValueProto = listValuesByIDValueProto2
		}
		listValuesByID[listValuesByIDKey] = listValuesByIDValueProto
	}
	target.SetListValuesById(listValuesByID)
	anyValues := make([]*anypb.Any, 0, len(source.AnyValues))
	for _, anyValuesItem := range source.AnyValues {
		anyValues = append(anyValues, anyValuesItem)
	}
	target.SetAnyValues(anyValues)
	anyValuesByID := make(map[string]*anypb.Any, len(source.AnyValuesByID))
	for anyValuesByIDKey, anyValuesByIDValue := range source.AnyValuesByID {
		anyValuesByID[anyValuesByIDKey] = anyValuesByIDValue
	}
	target.SetAnyValuesById(anyValuesByID)
	emptyValues := make([]*emptypb.Empty, 0, len(source.EmptyValues))
	for range source.EmptyValues {
		emptyValues = append(emptyValues, new(emptypb.Empty))
	}
	target.SetEmptyValues(emptyValues)
	emptyValuesByID := make(map[string]*emptypb.Empty, len(source.EmptyValuesByID))
	for emptyValuesByIDKey := range source.EmptyValuesByID {
		emptyValuesByID[emptyValuesByIDKey] = new(emptypb.Empty)
	}
	target.SetEmptyValuesById(emptyValuesByID)
	return target, nil
}

func (ks KitchenSink) ToProto() (*kitchensinkpbv1.KitchenSink, error) {
	return KitchenSinkToProto(ks)
}

func ChoiceFromProto(source *kitchensinkpbv1.Choice) Choice {
	var target Choice
	if source == nil {
		return target
	}
	switch source.WhichValue() {
	case kitchensinkpbv1.Choice_Text_case:
		target.Value = ChoiceText{Text: source.GetText()}
	case kitchensinkpbv1.Choice_Number_case:
		target.Value = ChoiceNumber{Number: source.GetNumber()}
	}
	return target
}

func ChoiceToProto(source Choice) (*kitchensinkpbv1.Choice, error) {
	target := new(kitchensinkpbv1.Choice)
	switch value := source.Value.(type) {
	case nil:
	case ChoiceText:
		target.SetText(value.Text)
	case *ChoiceText:
		if value != nil {
			target.SetText(value.Text)
		}
	case ChoiceNumber:
		target.SetNumber(value.Number)
	case *ChoiceNumber:
		if value != nil {
			target.SetNumber(value.Number)
		}
	default:
		return nil, errors.New("unsupported oneof implementation")
	}
	return target, nil
}

func (c Choice) ToProto() (*kitchensinkpbv1.Choice, error) {
	return ChoiceToProto(c)
}
