// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/yirapb/v1/yira.proto

package yirapbv1

import (
	_ "github.com/seeruk/tego/tegopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketStatus int32

const (
	TicketStatus_TICKET_STATUS_UNSPECIFIED TicketStatus = 0
	TicketStatus_TICKET_STATUS_OPEN        TicketStatus = 1
	TicketStatus_TICKET_STATUS_IN_PROGRESS TicketStatus = 2
	TicketStatus_TICKET_STATUS_CLOSED      TicketStatus = 3
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "TICKET_STATUS_UNSPECIFIED",
		1: "TICKET_STATUS_OPEN",
		2: "TICKET_STATUS_IN_PROGRESS",
		3: "TICKET_STATUS_CLOSED",
	}
	TicketStatus_value = map[string]int32{
		"TICKET_STATUS_UNSPECIFIED": 0,
		"TICKET_STATUS_OPEN":        1,
		"TICKET_STATUS_IN_PROGRESS": 2,
		"TICKET_STATUS_CLOSED":      3,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_yirapb_v1_yira_proto_enumTypes[0].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_proto_yirapb_v1_yira_proto_enumTypes[0]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Ticket_Visibility int32

const (
	Ticket_VISIBILITY_UNSPECIFIED Ticket_Visibility = 0
	Ticket_VISIBILITY_PUBLIC      Ticket_Visibility = 1
	Ticket_VISIBILITY_PRIVATE     Ticket_Visibility = 2
)

// Enum value maps for Ticket_Visibility.
var (
	Ticket_Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_PRIVATE",
	}
	Ticket_Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_PRIVATE":     2,
	}
)

func (x Ticket_Visibility) Enum() *Ticket_Visibility {
	p := new(Ticket_Visibility)
	*p = x
	return p
}

func (x Ticket_Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ticket_Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_yirapb_v1_yira_proto_enumTypes[1].Descriptor()
}

func (Ticket_Visibility) Type() protoreflect.EnumType {
	return &file_proto_yirapb_v1_yira_proto_enumTypes[1]
}

func (x Ticket_Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Ticket struct {
	state                         protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Title              *string                 `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Description        *string                 `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Status             TicketStatus            `protobuf:"varint,4,opt,name=status,enum=yirapb.v1.TicketStatus"`
	xxx_hidden_Assignee           *NullablePerson         `protobuf:"bytes,5,opt,name=assignee"`
	xxx_hidden_Author             *Person                 `protobuf:"bytes,6,opt,name=author"`
	xxx_hidden_Version            *string                 `protobuf:"bytes,7,opt,name=version"`
	xxx_hidden_Metadata           map[string]string       `protobuf:"bytes,8,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_WatchersByRole     map[string]*Person      `protobuf:"bytes,9,rep,name=watchers_by_role,json=watchersByRole" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_WorkflowStatuses   map[string]TicketStatus `protobuf:"bytes,10,rep,name=workflow_statuses,json=workflowStatuses" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=yirapb.v1.TicketStatus"`
	xxx_hidden_WatcherIds         []string                `protobuf:"bytes,11,rep,name=watcher_ids,json=watcherIds"`
	xxx_hidden_Labels             []string                `protobuf:"bytes,12,rep,name=labels"`
	xxx_hidden_Visibility         Ticket_Visibility       `protobuf:"varint,13,opt,name=visibility,enum=yirapb.v1.Ticket_Visibility"`
	xxx_hidden_AuditEvents        *[]*Ticket_AuditEvent   `protobuf:"bytes,14,rep,name=audit_events,json=auditEvents"`
	xxx_hidden_History            *Ticket_History         `protobuf:"bytes,15,opt,name=history"`
	xxx_hidden_LatestHistoryEntry *Ticket_History_Entry   `protobuf:"bytes,16,opt,name=latest_history_entry,json=latestHistoryEntry"`
	xxx_hidden_Reviewer           isTicket_Reviewer       `protobuf_oneof:"reviewer"`
	xxx_hidden_StructData         *structpb.Struct        `protobuf:"bytes,19,opt,name=struct_data,json=structData"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetStatus() TicketStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Status
		}
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) GetAssignee() *NullablePerson {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return nil
}

func (x *Ticket) GetAuthor() *Person {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *Ticket) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Ticket) GetWatchersByRole() map[string]*Person {
	if x != nil {
		return x.xxx_hidden_WatchersByRole
	}
	return nil
}

func (x *Ticket) GetWorkflowStatuses() map[string]TicketStatus {
	if x != nil {
		return x.xxx_hidden_WorkflowStatuses
	}
	return nil
}

func (x *Ticket) GetWatcherIds() []string {
	if x != nil {
		return x.xxx_hidden_WatcherIds
	}
	return nil
}

func (x *Ticket) GetLabels() []string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Ticket) GetVisibility() Ticket_Visibility {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 12) {
			return x.xxx_hidden_Visibility
		}
	}
	return Ticket_VISIBILITY_UNSPECIFIED
}

func (x *Ticket) GetAuditEvents() []*Ticket_AuditEvent {
	if x != nil {
		if x.xxx_hidden_AuditEvents != nil {
			return *x.xxx_hidden_AuditEvents
		}
	}
	return nil
}

func (x *Ticket) GetHistory() *Ticket_History {
	if x != nil {
		return x.xxx_hidden_History
	}
	return nil
}

func (x *Ticket) GetLatestHistoryEntry() *Ticket_History_Entry {
	if x != nil {
		return x.xxx_hidden_LatestHistoryEntry
	}
	return nil
}

func (x *Ticket) GetInternal() *Person {
	if x != nil {
		if x, ok := x.xxx_hidden_Reviewer.(*ticket_Internal); ok {
			return x.Internal
		}
	}
	return nil
}

func (x *Ticket) GetExternalRef() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Reviewer.(*ticket_ExternalRef); ok {
			return x.ExternalRef
		}
	}
	return ""
}

func (x *Ticket) GetStructData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_StructData
	}
	return nil
}

func (x *Ticket) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 18)
}

func (x *Ticket) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 18)
}

func (x *Ticket) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 18)
}

func (x *Ticket) SetStatus(v TicketStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 18)
}

func (x *Ticket) SetAssignee(v *NullablePerson) {
	x.xxx_hidden_Assignee = v
}

func (x *Ticket) SetAuthor(v *Person) {
	x.xxx_hidden_Author = v
}

func (x *Ticket) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 18)
}

func (x *Ticket) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Ticket) SetWatchersByRole(v map[string]*Person) {
	x.xxx_hidden_WatchersByRole = v
}

func (x *Ticket) SetWorkflowStatuses(v map[string]TicketStatus) {
	x.xxx_hidden_WorkflowStatuses = v
}

func (x *Ticket) SetWatcherIds(v []string) {
	x.xxx_hidden_WatcherIds = v
}

func (x *Ticket) SetLabels(v []string) {
	x.xxx_hidden_Labels = v
}

func (x *Ticket) SetVisibility(v Ticket_Visibility) {
	x.xxx_hidden_Visibility = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 18)
}

func (x *Ticket) SetAuditEvents(v []*Ticket_AuditEvent) {
	x.xxx_hidden_AuditEvents = &v
}

func (x *Ticket) SetHistory(v *Ticket_History) {
	x.xxx_hidden_History = v
}

func (x *Ticket) SetLatestHistoryEntry(v *Ticket_History_Entry) {
	x.xxx_hidden_LatestHistoryEntry = v
}

func (x *Ticket) SetInternal(v *Person) {
	if v == nil {
		x.xxx_hidden_Reviewer = nil
		return
	}
	x.xxx_hidden_Reviewer = &ticket_Internal{v}
}

func (x *Ticket) SetExternalRef(v string) {
	x.xxx_hidden_Reviewer = &ticket_ExternalRef{v}
}

func (x *Ticket) SetStructData(v *structpb.Struct) {
	x.xxx_hidden_StructData = v
}

func (x *Ticket) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ticket) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Ticket) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Ticket) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Ticket) HasAssignee() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Assignee != nil
}

func (x *Ticket) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *Ticket) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Ticket) HasVisibility() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *Ticket) HasHistory() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_History != nil
}

func (x *Ticket) HasLatestHistoryEntry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LatestHistoryEntry != nil
}

func (x *Ticket) HasReviewer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Reviewer != nil
}

func (x *Ticket) HasInternal() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Reviewer.(*ticket_Internal)
	return ok
}

func (x *Ticket) HasExternalRef() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Reviewer.(*ticket_ExternalRef)
	return ok
}

func (x *Ticket) HasStructData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StructData != nil
}

func (x *Ticket) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Ticket) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *Ticket) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *Ticket) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Status = TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) ClearAssignee() {
	x.xxx_hidden_Assignee = nil
}

func (x *Ticket) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *Ticket) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Version = nil
}

func (x *Ticket) ClearVisibility() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_Visibility = Ticket_VISIBILITY_UNSPECIFIED
}

func (x *Ticket) ClearHistory() {
	x.xxx_hidden_History = nil
}

func (x *Ticket) ClearLatestHistoryEntry() {
	x.xxx_hidden_LatestHistoryEntry = nil
}

func (x *Ticket) ClearReviewer() {
	x.xxx_hidden_Reviewer = nil
}

func (x *Ticket) ClearInternal() {
	if _, ok := x.xxx_hidden_Reviewer.(*ticket_Internal); ok {
		x.xxx_hidden_Reviewer = nil
	}
}

func (x *Ticket) ClearExternalRef() {
	if _, ok := x.xxx_hidden_Reviewer.(*ticket_ExternalRef); ok {
		x.xxx_hidden_Reviewer = nil
	}
}

func (x *Ticket) ClearStructData() {
	x.xxx_hidden_StructData = nil
}

const Ticket_Reviewer_not_set_case case_Ticket_Reviewer = 0
const Ticket_Internal_case case_Ticket_Reviewer = 17
const Ticket_ExternalRef_case case_Ticket_Reviewer = 18

func (x *Ticket) WhichReviewer() case_Ticket_Reviewer {
	if x == nil {
		return Ticket_Reviewer_not_set_case
	}
	switch x.xxx_hidden_Reviewer.(type) {
	case *ticket_Internal:
		return Ticket_Internal_case
	case *ticket_ExternalRef:
		return Ticket_ExternalRef_case
	default:
		return Ticket_Reviewer_not_set_case
	}
}

type Ticket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	Title              *string
	Description        *string
	Status             *TicketStatus
	Assignee           *NullablePerson
	Author             *Person
	Version            *string
	Metadata           map[string]string
	WatchersByRole     map[string]*Person
	WorkflowStatuses   map[string]TicketStatus
	WatcherIds         []string
	Labels             []string
	Visibility         *Ticket_Visibility
	AuditEvents        []*Ticket_AuditEvent
	History            *Ticket_History
	LatestHistoryEntry *Ticket_History_Entry
	// Fields of oneof xxx_hidden_Reviewer:
	Internal    *Person
	ExternalRef *string
	// -- end of xxx_hidden_Reviewer
	StructData *structpb.Struct
}

func (b0 Ticket_builder) Build() *Ticket {
	m0 := &Ticket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 18)
		x.xxx_hidden_Id = b.Id
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 18)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 18)
		x.xxx_hidden_Description = b.Description
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 18)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Assignee = b.Assignee
	x.xxx_hidden_Author = b.Author
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 18)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_WatchersByRole = b.WatchersByRole
	x.xxx_hidden_WorkflowStatuses = b.WorkflowStatuses
	x.xxx_hidden_WatcherIds = b.WatcherIds
	x.xxx_hidden_Labels = b.Labels
	if b.Visibility != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 18)
		x.xxx_hidden_Visibility = *b.Visibility
	}
	x.xxx_hidden_AuditEvents = &b.AuditEvents
	x.xxx_hidden_History = b.History
	x.xxx_hidden_LatestHistoryEntry = b.LatestHistoryEntry
	if b.Internal != nil {
		x.xxx_hidden_Reviewer = &ticket_Internal{b.Internal}
	}
	if b.ExternalRef != nil {
		x.xxx_hidden_Reviewer = &ticket_ExternalRef{*b.ExternalRef}
	}
	x.xxx_hidden_StructData = b.StructData
	return m0
}

type case_Ticket_Reviewer protoreflect.FieldNumber

func (x case_Ticket_Reviewer) String() string {
	md := file_proto_yirapb_v1_yira_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTicket_Reviewer interface {
	isTicket_Reviewer()
}

type ticket_Internal struct {
	Internal *Person `protobuf:"bytes,17,opt,name=internal,oneof"`
}

type ticket_ExternalRef struct {
	ExternalRef string `protobuf:"bytes,18,opt,name=external_ref,json=externalRef,oneof"`
}

func (*ticket_Internal) isTicket_Reviewer() {}

func (*ticket_ExternalRef) isTicket_Reviewer() {}

type UpdateTicketRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Input       *TicketInput           `protobuf:"bytes,2,opt,name=input"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTicketRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateTicketRequest) GetInput() *TicketInput {
	if x != nil {
		return x.xxx_hidden_Input
	}
	return nil
}

func (x *UpdateTicketRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateTicketRequest) SetInput(v *TicketInput) {
	x.xxx_hidden_Input = v
}

func (x *UpdateTicketRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateTicketRequest) HasInput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Input != nil
}

func (x *UpdateTicketRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateTicketRequest) ClearInput() {
	x.xxx_hidden_Input = nil
}

type UpdateTicketRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    *string
	Input *TicketInput
}

func (b0 UpdateTicketRequest_builder) Build() *UpdateTicketRequest {
	m0 := &UpdateTicketRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Input = b.Input
	return m0
}

type TicketInput struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Status      TicketStatus           `protobuf:"varint,4,opt,name=status,enum=yirapb.v1.TicketStatus"`
	xxx_hidden_Assignee    *Person                `protobuf:"bytes,5,opt,name=assignee"`
	xxx_hidden_Version     *string                `protobuf:"bytes,6,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TicketInput) Reset() {
	*x = TicketInput{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInput) ProtoMessage() {}

func (x *TicketInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TicketInput) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *TicketInput) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *TicketInput) GetStatus() TicketStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Status
		}
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *TicketInput) GetAssignee() *Person {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return nil
}

func (x *TicketInput) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *TicketInput) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *TicketInput) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *TicketInput) SetStatus(v TicketStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *TicketInput) SetAssignee(v *Person) {
	x.xxx_hidden_Assignee = v
}

func (x *TicketInput) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *TicketInput) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TicketInput) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TicketInput) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TicketInput) HasAssignee() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Assignee != nil
}

func (x *TicketInput) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TicketInput) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *TicketInput) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *TicketInput) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Status = TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *TicketInput) ClearAssignee() {
	x.xxx_hidden_Assignee = nil
}

func (x *TicketInput) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = nil
}

type TicketInput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Description *string
	Status      *TicketStatus
	Assignee    *Person
	// Required fields would not be generated as omittable.
	Version *string
}

func (b0 TicketInput_builder) Build() *TicketInput {
	m0 := &TicketInput{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Description = b.Description
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Assignee = b.Assignee
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

type Person struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FirstName   *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName"`
	xxx_hidden_LastName    *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Person) GetFirstName() string {
	if x != nil {
		if x.xxx_hidden_FirstName != nil {
			return *x.xxx_hidden_FirstName
		}
		return ""
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		if x.xxx_hidden_LastName != nil {
			return *x.xxx_hidden_LastName
		}
		return ""
	}
	return ""
}

func (x *Person) SetFirstName(v string) {
	x.xxx_hidden_FirstName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Person) SetLastName(v string) {
	x.xxx_hidden_LastName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Person) HasFirstName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Person) HasLastName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Person) ClearFirstName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FirstName = nil
}

func (x *Person) ClearLastName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_LastName = nil
}

type Person_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FirstName *string
	LastName  *string
}

func (b0 Person_builder) Build() *Person {
	m0 := &Person{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FirstName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FirstName = b.FirstName
	}
	if b.LastName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_LastName = b.LastName
	}
	return m0
}

type People struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_People *[]*Person             `protobuf:"bytes,1,rep,name=people"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *People) Reset() {
	*x = People{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *People) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*People) ProtoMessage() {}

func (x *People) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *People) GetPeople() []*Person {
	if x != nil {
		if x.xxx_hidden_People != nil {
			return *x.xxx_hidden_People
		}
	}
	return nil
}

func (x *People) SetPeople(v []*Person) {
	x.xxx_hidden_People = &v
}

type People_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	People []*Person
}

func (b0 People_builder) Build() *People {
	m0 := &People{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_People = &b.People
	return m0
}

type NullablePerson struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isNullablePerson_Value `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NullablePerson) Reset() {
	*x = NullablePerson{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullablePerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullablePerson) ProtoMessage() {}

func (x *NullablePerson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullablePerson) GetPerson() *Person {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullablePerson_Person); ok {
			return x.Person
		}
	}
	return nil
}

func (x *NullablePerson) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullablePerson_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *NullablePerson) SetPerson(v *Person) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &nullablePerson_Person{v}
}

func (x *NullablePerson) SetNull(v structpb.NullValue) {
	x.xxx_hidden_Value = &nullablePerson_Null{v}
}

func (x *NullablePerson) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *NullablePerson) HasPerson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullablePerson_Person)
	return ok
}

func (x *NullablePerson) HasNull() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullablePerson_Null)
	return ok
}

func (x *NullablePerson) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *NullablePerson) ClearPerson() {
	if _, ok := x.xxx_hidden_Value.(*nullablePerson_Person); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *NullablePerson) ClearNull() {
	if _, ok := x.xxx_hidden_Value.(*nullablePerson_Null); ok {
		x.xxx_hidden_Value = nil
	}
}

const NullablePerson_Value_not_set_case case_NullablePerson_Value = 0
const NullablePerson_Person_case case_NullablePerson_Value = 1
const NullablePerson_Null_case case_NullablePerson_Value = 2

func (x *NullablePerson) WhichValue() case_NullablePerson_Value {
	if x == nil {
		return NullablePerson_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *nullablePerson_Person:
		return NullablePerson_Person_case
	case *nullablePerson_Null:
		return NullablePerson_Null_case
	default:
		return NullablePerson_Value_not_set_case
	}
}

type NullablePerson_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	Person *Person
	Null   *structpb.NullValue
	// -- end of xxx_hidden_Value
}

func (b0 NullablePerson_builder) Build() *NullablePerson {
	m0 := &NullablePerson{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Person != nil {
		x.xxx_hidden_Value = &nullablePerson_Person{b.Person}
	}
	if b.Null != nil {
		x.xxx_hidden_Value = &nullablePerson_Null{*b.Null}
	}
	return m0
}

type case_NullablePerson_Value protoreflect.FieldNumber

func (x case_NullablePerson_Value) String() string {
	md := file_proto_yirapb_v1_yira_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNullablePerson_Value interface {
	isNullablePerson_Value()
}

type nullablePerson_Person struct {
	Person *Person `protobuf:"bytes,1,opt,name=person,oneof"`
}

type nullablePerson_Null struct {
	Null structpb.NullValue `protobuf:"varint,2,opt,name=null,enum=google.protobuf.NullValue,oneof"`
}

func (*nullablePerson_Person) isNullablePerson_Value() {}

func (*nullablePerson_Null) isNullablePerson_Value() {}

type NullablePersonValue struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *Person                `protobuf:"bytes,1,opt,name=value"`
	xxx_hidden_Valid       bool                   `protobuf:"varint,2,opt,name=valid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NullablePersonValue) Reset() {
	*x = NullablePersonValue{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullablePersonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullablePersonValue) ProtoMessage() {}

func (x *NullablePersonValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullablePersonValue) GetValue() *Person {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *NullablePersonValue) GetValid() bool {
	if x != nil {
		return x.xxx_hidden_Valid
	}
	return false
}

func (x *NullablePersonValue) SetValue(v *Person) {
	x.xxx_hidden_Value = v
}

func (x *NullablePersonValue) SetValid(v bool) {
	x.xxx_hidden_Valid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *NullablePersonValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *NullablePersonValue) HasValid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NullablePersonValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *NullablePersonValue) ClearValid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Valid = false
}

type NullablePersonValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *Person
	Valid *bool
}

func (b0 NullablePersonValue_builder) Build() *NullablePersonValue {
	m0 := &NullablePersonValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	if b.Valid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Valid = *b.Valid
	}
	return m0
}

type NullablePeople struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_People *[]*NullablePerson     `protobuf:"bytes,1,rep,name=people"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NullablePeople) Reset() {
	*x = NullablePeople{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullablePeople) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullablePeople) ProtoMessage() {}

func (x *NullablePeople) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullablePeople) GetPeople() []*NullablePerson {
	if x != nil {
		if x.xxx_hidden_People != nil {
			return *x.xxx_hidden_People
		}
	}
	return nil
}

func (x *NullablePeople) SetPeople(v []*NullablePerson) {
	x.xxx_hidden_People = &v
}

type NullablePeople_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	People []*NullablePerson
}

func (b0 NullablePeople_builder) Build() *NullablePeople {
	m0 := &NullablePeople{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_People = &b.People
	return m0
}

type NullableNullablePeople struct {
	state            protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Value isNullableNullablePeople_Value `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NullableNullablePeople) Reset() {
	*x = NullableNullablePeople{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableNullablePeople) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableNullablePeople) ProtoMessage() {}

func (x *NullableNullablePeople) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullableNullablePeople) GetPeople() *NullablePeople {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullableNullablePeople_People); ok {
			return x.People
		}
	}
	return nil
}

func (x *NullableNullablePeople) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullableNullablePeople_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *NullableNullablePeople) SetPeople(v *NullablePeople) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &nullableNullablePeople_People{v}
}

func (x *NullableNullablePeople) SetNull(v structpb.NullValue) {
	x.xxx_hidden_Value = &nullableNullablePeople_Null{v}
}

func (x *NullableNullablePeople) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *NullableNullablePeople) HasPeople() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullableNullablePeople_People)
	return ok
}

func (x *NullableNullablePeople) HasNull() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullableNullablePeople_Null)
	return ok
}

func (x *NullableNullablePeople) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *NullableNullablePeople) ClearPeople() {
	if _, ok := x.xxx_hidden_Value.(*nullableNullablePeople_People); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *NullableNullablePeople) ClearNull() {
	if _, ok := x.xxx_hidden_Value.(*nullableNullablePeople_Null); ok {
		x.xxx_hidden_Value = nil
	}
}

const NullableNullablePeople_Value_not_set_case case_NullableNullablePeople_Value = 0
const NullableNullablePeople_People_case case_NullableNullablePeople_Value = 1
const NullableNullablePeople_Null_case case_NullableNullablePeople_Value = 2

func (x *NullableNullablePeople) WhichValue() case_NullableNullablePeople_Value {
	if x == nil {
		return NullableNullablePeople_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *nullableNullablePeople_People:
		return NullableNullablePeople_People_case
	case *nullableNullablePeople_Null:
		return NullableNullablePeople_Null_case
	default:
		return NullableNullablePeople_Value_not_set_case
	}
}

type NullableNullablePeople_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	People *NullablePeople
	Null   *structpb.NullValue
	// -- end of xxx_hidden_Value
}

func (b0 NullableNullablePeople_builder) Build() *NullableNullablePeople {
	m0 := &NullableNullablePeople{}
	b, x := &b0, m0
	_, _ = b, x
	if b.People != nil {
		x.xxx_hidden_Value = &nullableNullablePeople_People{b.People}
	}
	if b.Null != nil {
		x.xxx_hidden_Value = &nullableNullablePeople_Null{*b.Null}
	}
	return m0
}

type case_NullableNullablePeople_Value protoreflect.FieldNumber

func (x case_NullableNullablePeople_Value) String() string {
	md := file_proto_yirapb_v1_yira_proto_msgTypes[8].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNullableNullablePeople_Value interface {
	isNullableNullablePeople_Value()
}

type nullableNullablePeople_People struct {
	People *NullablePeople `protobuf:"bytes,1,opt,name=people,oneof"`
}

type nullableNullablePeople_Null struct {
	Null structpb.NullValue `protobuf:"varint,2,opt,name=null,enum=google.protobuf.NullValue,oneof"`
}

func (*nullableNullablePeople_People) isNullableNullablePeople_Value() {}

func (*nullableNullablePeople_Null) isNullableNullablePeople_Value() {}

type TicketsByPeople struct {
	state              protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*TicketsByPeople_Map `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TicketsByPeople) Reset() {
	*x = TicketsByPeople{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketsByPeople) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketsByPeople) ProtoMessage() {}

func (x *TicketsByPeople) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TicketsByPeople) GetEntries() []*TicketsByPeople_Map {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *TicketsByPeople) SetEntries(v []*TicketsByPeople_Map) {
	x.xxx_hidden_Entries = &v
}

type TicketsByPeople_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*TicketsByPeople_Map
}

func (b0 TicketsByPeople_builder) Build() *TicketsByPeople {
	m0 := &TicketsByPeople{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Ticket_AuditEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Actor       *string                `protobuf:"bytes,1,opt,name=actor"`
	xxx_hidden_Status      TicketStatus           `protobuf:"varint,2,opt,name=status,enum=yirapb.v1.TicketStatus"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ticket_AuditEvent) Reset() {
	*x = Ticket_AuditEvent{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket_AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket_AuditEvent) ProtoMessage() {}

func (x *Ticket_AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket_AuditEvent) GetActor() string {
	if x != nil {
		if x.xxx_hidden_Actor != nil {
			return *x.xxx_hidden_Actor
		}
		return ""
	}
	return ""
}

func (x *Ticket_AuditEvent) GetStatus() TicketStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Status
		}
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket_AuditEvent) SetActor(v string) {
	x.xxx_hidden_Actor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Ticket_AuditEvent) SetStatus(v TicketStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Ticket_AuditEvent) HasActor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ticket_AuditEvent) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Ticket_AuditEvent) ClearActor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Actor = nil
}

func (x *Ticket_AuditEvent) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Status = TicketStatus_TICKET_STATUS_UNSPECIFIED
}

type Ticket_AuditEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Actor  *string
	Status *TicketStatus
}

func (b0 Ticket_AuditEvent_builder) Build() *Ticket_AuditEvent {
	m0 := &Ticket_AuditEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Actor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Actor = b.Actor
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

type Ticket_History struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*Ticket_History_Entry `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ticket_History) Reset() {
	*x = Ticket_History{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket_History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket_History) ProtoMessage() {}

func (x *Ticket_History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket_History) GetEntries() []*Ticket_History_Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Ticket_History) SetEntries(v []*Ticket_History_Entry) {
	x.xxx_hidden_Entries = &v
}

type Ticket_History_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*Ticket_History_Entry
}

func (b0 Ticket_History_builder) Build() *Ticket_History {
	m0 := &Ticket_History{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Ticket_History_Entry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Note        *string                `protobuf:"bytes,1,opt,name=note"`
	xxx_hidden_Visibility  Ticket_Visibility      `protobuf:"varint,2,opt,name=visibility,enum=yirapb.v1.Ticket_Visibility"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ticket_History_Entry) Reset() {
	*x = Ticket_History_Entry{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket_History_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket_History_Entry) ProtoMessage() {}

func (x *Ticket_History_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket_History_Entry) GetNote() string {
	if x != nil {
		if x.xxx_hidden_Note != nil {
			return *x.xxx_hidden_Note
		}
		return ""
	}
	return ""
}

func (x *Ticket_History_Entry) GetVisibility() Ticket_Visibility {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Visibility
		}
	}
	return Ticket_VISIBILITY_UNSPECIFIED
}

func (x *Ticket_History_Entry) SetNote(v string) {
	x.xxx_hidden_Note = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Ticket_History_Entry) SetVisibility(v Ticket_Visibility) {
	x.xxx_hidden_Visibility = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Ticket_History_Entry) HasNote() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ticket_History_Entry) HasVisibility() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Ticket_History_Entry) ClearNote() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Note = nil
}

func (x *Ticket_History_Entry) ClearVisibility() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Visibility = Ticket_VISIBILITY_UNSPECIFIED
}

type Ticket_History_Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Note       *string
	Visibility *Ticket_Visibility
}

func (b0 Ticket_History_Entry_builder) Build() *Ticket_History_Entry {
	m0 := &Ticket_History_Entry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Note != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Note = b.Note
	}
	if b.Visibility != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Visibility = *b.Visibility
	}
	return m0
}

type TicketsByPeople_Map struct {
	state            protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Key   *Person                    `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value *[]*NullableNullablePeople `protobuf:"bytes,2,rep,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketsByPeople_Map) Reset() {
	*x = TicketsByPeople_Map{}
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketsByPeople_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketsByPeople_Map) ProtoMessage() {}

func (x *TicketsByPeople_Map) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yirapb_v1_yira_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TicketsByPeople_Map) GetKey() *Person {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *TicketsByPeople_Map) GetValue() []*NullableNullablePeople {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
	}
	return nil
}

func (x *TicketsByPeople_Map) SetKey(v *Person) {
	x.xxx_hidden_Key = v
}

func (x *TicketsByPeople_Map) SetValue(v []*NullableNullablePeople) {
	x.xxx_hidden_Value = &v
}

func (x *TicketsByPeople_Map) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *TicketsByPeople_Map) ClearKey() {
	x.xxx_hidden_Key = nil
}

type TicketsByPeople_Map_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *Person
	Value []*NullableNullablePeople
}

func (b0 TicketsByPeople_Map_builder) Build() *TicketsByPeople_Map {
	m0 := &TicketsByPeople_Map{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = &b.Value
	return m0
}

var File_proto_yirapb_v1_yira_proto protoreflect.FileDescriptor

const file_proto_yirapb_v1_yira_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/yirapb/v1/yira.proto\x12\tyirapb.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12tego/options.proto\"\xeb\x10\n" +
	"\x06Ticket\x12*\n" +
	"\x02id\x18\x01 \x01(\tB\x1a҅\n" +
	"\x16*\x14\n" +
	"\x04json\x12\fid,omitemptyR\x02id\x12%\n" +
	"\x05title\x18\x02 \x01(\tB\x0f҅\n" +
	"\v2\t\n" +
	"\x05title\x10\x01R\x05title\x12\x94\x02\n" +
	"\vdescription\x18\x03 \x01(\tB\xf1\x01҅\n" +
	"\xec\x01\x1a\xe9\x01\n" +
	"Egithub.com/seeruk/tego/internal/tego/testdata/plannertest.Description\x12Ngithub.com/seeruk/tego/internal/tego/testdata/plannertest.DescriptionFromProto\x1aLgithub.com/seeruk/tego/internal/tego/testdata/plannertest.DescriptionToProto \x01(\x01R\vdescription\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.yirapb.v1.TicketStatusR\x06status\x125\n" +
	"\bassignee\x18\x05 \x01(\v2\x19.yirapb.v1.NullablePersonR\bassignee\x12)\n" +
	"\x06author\x18\x06 \x01(\v2\x11.yirapb.v1.PersonR\x06author\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12;\n" +
	"\bmetadata\x18\b \x03(\v2\x1f.yirapb.v1.Ticket.MetadataEntryR\bmetadata\x12O\n" +
	"\x10watchers_by_role\x18\t \x03(\v2%.yirapb.v1.Ticket.WatchersByRoleEntryR\x0ewatchersByRole\x12T\n" +
	"\x11workflow_statuses\x18\n" +
	" \x03(\v2'.yirapb.v1.Ticket.WorkflowStatusesEntryR\x10workflowStatuses\x12\x1f\n" +
	"\vwatcher_ids\x18\v \x03(\tR\n" +
	"watcherIds\x12\xd8\x02\n" +
	"\x06labels\x18\f \x03(\tB\xbf\x02҅\n" +
	"\xba\x02\x1a\xb7\x02\n" +
	"@github.com/seeruk/tego/internal/tego/testdata/plannertest.Set[T]\x12Rgithub.com/seeruk/tego/internal/tego/testdata/plannertest.CustomStringSetFromProto\x1aPgithub.com/seeruk/tego/internal/tego/testdata/plannertest.CustomStringSetToProto2M\n" +
	"\x01T\x12H\n" +
	"Fgithub.com/seeruk/tego/internal/tego/testdata/plannertest.CustomStringR\x06labels\x12<\n" +
	"\n" +
	"visibility\x18\r \x01(\x0e2\x1c.yirapb.v1.Ticket.VisibilityR\n" +
	"visibility\x12?\n" +
	"\faudit_events\x18\x0e \x03(\v2\x1c.yirapb.v1.Ticket.AuditEventR\vauditEvents\x123\n" +
	"\ahistory\x18\x0f \x01(\v2\x19.yirapb.v1.Ticket.HistoryR\ahistory\x12Q\n" +
	"\x14latest_history_entry\x18\x10 \x01(\v2\x1f.yirapb.v1.Ticket.History.EntryR\x12latestHistoryEntry\x12/\n" +
	"\binternal\x18\x11 \x01(\v2\x11.yirapb.v1.PersonH\x00R\binternal\x12+\n" +
	"\fexternal_ref\x18\x12 \x01(\tB\x06҅\n" +
	"\x02 \x01H\x00R\vexternalRef\x128\n" +
	"\vstruct_data\x18\x13 \x01(\v2\x17.google.protobuf.StructR\n" +
	"structData\x1aS\n" +
	"\n" +
	"AuditEvent\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.yirapb.v1.TicketStatusR\x06status\x1a\x9f\x01\n" +
	"\aHistory\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.yirapb.v1.Ticket.History.EntryR\aentries\x1aY\n" +
	"\x05Entry\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\x12<\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2\x1c.yirapb.v1.Ticket.VisibilityR\n" +
	"visibility\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x13WatchersByRoleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.yirapb.v1.PersonR\x05value:\x028\x01\x1a\\\n" +
	"\x15WorkflowStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\x0e2\x17.yirapb.v1.TicketStatusR\x05value:\x028\x01\"W\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x02B\n" +
	"\n" +
	"\breviewer\"S\n" +
	"\x13UpdateTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x05input\x18\x02 \x01(\v2\x16.yirapb.v1.TicketInputR\x05input\"\xd9\x01\n" +
	"\vTicketInput\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.yirapb.v1.TicketStatusR\x06status\x125\n" +
	"\bassignee\x18\x05 \x01(\v2\x11.yirapb.v1.PersonB\x06҅\n" +
	"\x02@\x01R\bassignee\x12 \n" +
	"\aversion\x18\x06 \x01(\tB\x06҅\n" +
	"\x028\x00R\aversion:\b҅\n" +
	"\x04*\x02\b\x01\"D\n" +
	"\x06Person\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"3\n" +
	"\x06People\x12)\n" +
	"\x06people\x18\x01 \x03(\v2\x11.yirapb.v1.PersonR\x06people\"x\n" +
	"\x0eNullablePerson\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x11.yirapb.v1.PersonH\x00R\x06person\x120\n" +
	"\x04null\x18\x02 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04nullB\a\n" +
	"\x05value\"T\n" +
	"\x13NullablePersonValue\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.yirapb.v1.PersonR\x05value\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"C\n" +
	"\x0eNullablePeople\x121\n" +
	"\x06people\x18\x01 \x03(\v2\x19.yirapb.v1.NullablePersonR\x06people\"\x88\x01\n" +
	"\x16NullableNullablePeople\x123\n" +
	"\x06people\x18\x01 \x01(\v2\x19.yirapb.v1.NullablePeopleH\x00R\x06people\x120\n" +
	"\x04null\x18\x02 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04nullB\a\n" +
	"\x05value\"\xb0\x01\n" +
	"\x0fTicketsByPeople\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.yirapb.v1.TicketsByPeople.MapR\aentries\x1ac\n" +
	"\x03Map\x12#\n" +
	"\x03key\x18\x01 \x01(\v2\x11.yirapb.v1.PersonR\x03key\x127\n" +
	"\x05value\x18\x02 \x03(\v2!.yirapb.v1.NullableNullablePeopleR\x05value*\x90\x02\n" +
	"\fTicketStatus\x12\x1d\n" +
	"\x19TICKET_STATUS_UNSPECIFIED\x10\x00\x12X\n" +
	"\x12TICKET_STATUS_OPEN\x10\x01\x1a@҅\n" +
	"<\n" +
	"\x10TicketStatusOpen\x12&TicketStatusOpen means work can begin. \x01\x12\x1d\n" +
	"\x19TICKET_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14TICKET_STATUS_CLOSED\x10\x03\x1aN҅\n" +
	"J\n" +
	"\fTicketStatus\x128TicketStatus is the current lifecycle state of a ticket. \x01BX҅\n" +
	"&\n" +
	"$github.com/seeruk/tego/lab/yira;yiraZ,github.com/seeruk/tego/lab/yirapbv1;yirapbv1b\beditionsp\xe9\a"

var file_proto_yirapb_v1_yira_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_yirapb_v1_yira_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_yirapb_v1_yira_proto_goTypes = []any{
	(TicketStatus)(0),              // 0: yirapb.v1.TicketStatus
	(Ticket_Visibility)(0),         // 1: yirapb.v1.Ticket.Visibility
	(*Ticket)(nil),                 // 2: yirapb.v1.Ticket
	(*UpdateTicketRequest)(nil),    // 3: yirapb.v1.UpdateTicketRequest
	(*TicketInput)(nil),            // 4: yirapb.v1.TicketInput
	(*Person)(nil),                 // 5: yirapb.v1.Person
	(*People)(nil),                 // 6: yirapb.v1.People
	(*NullablePerson)(nil),         // 7: yirapb.v1.NullablePerson
	(*NullablePersonValue)(nil),    // 8: yirapb.v1.NullablePersonValue
	(*NullablePeople)(nil),         // 9: yirapb.v1.NullablePeople
	(*NullableNullablePeople)(nil), // 10: yirapb.v1.NullableNullablePeople
	(*TicketsByPeople)(nil),        // 11: yirapb.v1.TicketsByPeople
	(*Ticket_AuditEvent)(nil),      // 12: yirapb.v1.Ticket.AuditEvent
	(*Ticket_History)(nil),         // 13: yirapb.v1.Ticket.History
	nil,                            // 14: yirapb.v1.Ticket.MetadataEntry
	nil,                            // 15: yirapb.v1.Ticket.WatchersByRoleEntry
	nil,                            // 16: yirapb.v1.Ticket.WorkflowStatusesEntry
	(*Ticket_History_Entry)(nil),   // 17: yirapb.v1.Ticket.History.Entry
	(*TicketsByPeople_Map)(nil),    // 18: yirapb.v1.TicketsByPeople.Map
	(*structpb.Struct)(nil),        // 19: google.protobuf.Struct
	(structpb.NullValue)(0),        // 20: google.protobuf.NullValue
}
var file_proto_yirapb_v1_yira_proto_depIdxs = []int32{
	0,  // 0: yirapb.v1.Ticket.status:type_name -> yirapb.v1.TicketStatus
	7,  // 1: yirapb.v1.Ticket.assignee:type_name -> yirapb.v1.NullablePerson
	5,  // 2: yirapb.v1.Ticket.author:type_name -> yirapb.v1.Person
	14, // 3: yirapb.v1.Ticket.metadata:type_name -> yirapb.v1.Ticket.MetadataEntry
	15, // 4: yirapb.v1.Ticket.watchers_by_role:type_name -> yirapb.v1.Ticket.WatchersByRoleEntry
	16, // 5: yirapb.v1.Ticket.workflow_statuses:type_name -> yirapb.v1.Ticket.WorkflowStatusesEntry
	1,  // 6: yirapb.v1.Ticket.visibility:type_name -> yirapb.v1.Ticket.Visibility
	12, // 7: yirapb.v1.Ticket.audit_events:type_name -> yirapb.v1.Ticket.AuditEvent
	13, // 8: yirapb.v1.Ticket.history:type_name -> yirapb.v1.Ticket.History
	17, // 9: yirapb.v1.Ticket.latest_history_entry:type_name -> yirapb.v1.Ticket.History.Entry
	5,  // 10: yirapb.v1.Ticket.internal:type_name -> yirapb.v1.Person
	19, // 11: yirapb.v1.Ticket.struct_data:type_name -> google.protobuf.Struct
	4,  // 12: yirapb.v1.UpdateTicketRequest.input:type_name -> yirapb.v1.TicketInput
	0,  // 13: yirapb.v1.TicketInput.status:type_name -> yirapb.v1.TicketStatus
	5,  // 14: yirapb.v1.TicketInput.assignee:type_name -> yirapb.v1.Person
	5,  // 15: yirapb.v1.People.people:type_name -> yirapb.v1.Person
	5,  // 16: yirapb.v1.NullablePerson.person:type_name -> yirapb.v1.Person
	20, // 17: yirapb.v1.NullablePerson.null:type_name -> google.protobuf.NullValue
	5,  // 18: yirapb.v1.NullablePersonValue.value:type_name -> yirapb.v1.Person
	7,  // 19: yirapb.v1.NullablePeople.people:type_name -> yirapb.v1.NullablePerson
	9,  // 20: yirapb.v1.NullableNullablePeople.people:type_name -> yirapb.v1.NullablePeople
	20, // 21: yirapb.v1.NullableNullablePeople.null:type_name -> google.protobuf.NullValue
	18, // 22: yirapb.v1.TicketsByPeople.entries:type_name -> yirapb.v1.TicketsByPeople.Map
	0,  // 23: yirapb.v1.Ticket.AuditEvent.status:type_name -> yirapb.v1.TicketStatus
	17, // 24: yirapb.v1.Ticket.History.entries:type_name -> yirapb.v1.Ticket.History.Entry
	5,  // 25: yirapb.v1.Ticket.WatchersByRoleEntry.value:type_name -> yirapb.v1.Person
	0,  // 26: yirapb.v1.Ticket.WorkflowStatusesEntry.value:type_name -> yirapb.v1.TicketStatus
	1,  // 27: yirapb.v1.Ticket.History.Entry.visibility:type_name -> yirapb.v1.Ticket.Visibility
	5,  // 28: yirapb.v1.TicketsByPeople.Map.key:type_name -> yirapb.v1.Person
	10, // 29: yirapb.v1.TicketsByPeople.Map.value:type_name -> yirapb.v1.NullableNullablePeople
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_yirapb_v1_yira_proto_init() }
func file_proto_yirapb_v1_yira_proto_init() {
	if File_proto_yirapb_v1_yira_proto != nil {
		return
	}
	file_proto_yirapb_v1_yira_proto_msgTypes[0].OneofWrappers = []any{
		(*ticket_Internal)(nil),
		(*ticket_ExternalRef)(nil),
	}
	file_proto_yirapb_v1_yira_proto_msgTypes[5].OneofWrappers = []any{
		(*nullablePerson_Person)(nil),
		(*nullablePerson_Null)(nil),
	}
	file_proto_yirapb_v1_yira_proto_msgTypes[8].OneofWrappers = []any{
		(*nullableNullablePeople_People)(nil),
		(*nullableNullablePeople_Null)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yirapb_v1_yira_proto_rawDesc), len(file_proto_yirapb_v1_yira_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_yirapb_v1_yira_proto_goTypes,
		DependencyIndexes: file_proto_yirapb_v1_yira_proto_depIdxs,
		EnumInfos:         file_proto_yirapb_v1_yira_proto_enumTypes,
		MessageInfos:      file_proto_yirapb_v1_yira_proto_msgTypes,
	}.Build()
	File_proto_yirapb_v1_yira_proto = out.File
	file_proto_yirapb_v1_yira_proto_goTypes = nil
	file_proto_yirapb_v1_yira_proto_depIdxs = nil
}
