// Code generated by protoc-gen-tego. DO NOT EDIT.
package patch

import (
	tego "github.com/seeruk/tego"
	patchpbv1 "github.com/seeruk/tego/examples/presence-patch/patchpbv1"
	omittable "github.com/seeruk/tego/omittable"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// UpdateProfileRequest is an example of what a "patching" update request might look like.
//
// You can control omittability across the whole message with the message-level fields options, and
// also individually toggle field omittability back off with the field-level options.
//
// Fields can still be nullable while omittable, and this is very useful (e.g. only update this
// database column if a value is set, but allow it to be null). To achieve this though, the value
// must be wrapped in a nullable-shape wrapper in Protobuf, otherwise there's no way to distinguish
// between "not set" and "set to null" at the Protobuf level. This will still translate cleanly to
// an omittable.Of[*T] in your Tego Go output.
type UpdateProfileRequest struct {
	DisplayName omittable.Of[string]
	Bio         omittable.Of[*string]
	Preferences omittable.Of[tego.Struct]
	ActorID     string
}

func UpdateProfileRequestFromProto(source *patchpbv1.UpdateProfileRequest) UpdateProfileRequest {
	var target UpdateProfileRequest
	if source == nil {
		return target
	}
	if source.HasDisplayName() {
		target.DisplayName = omittable.Some(source.GetDisplayName())
	} else {
		target.DisplayName = omittable.None[string]()
	}
	if source.HasBio() {
		var bio *string
		if source.GetBio() != nil && source.GetBio().WhichValue() == patchpbv1.NullableString_Text_case {
			bio = new(source.GetBio().GetText())
		}
		target.Bio = omittable.Some(bio)
	} else {
		target.Bio = omittable.None[*string]()
	}
	if source.HasPreferences() {
		var preferences tego.Struct
		if source.GetPreferences() != nil {
			preferences = source.GetPreferences().AsMap()
		}
		target.Preferences = omittable.Some(preferences)
	} else {
		target.Preferences = omittable.None[tego.Struct]()
	}
	target.ActorID = source.GetActorId()
	return target
}

func UpdateProfileRequestToProto(source UpdateProfileRequest) (*patchpbv1.UpdateProfileRequest, error) {
	target := new(patchpbv1.UpdateProfileRequest)
	if source.DisplayName.Valid {
		target.SetDisplayName(source.DisplayName.Value)
	}
	if source.Bio.Valid {
		var bio *patchpbv1.NullableString
		if source.Bio.Value != nil {
			bio = new(patchpbv1.NullableString)
			bio.SetText(*source.Bio.Value)
		} else {
			bio = new(patchpbv1.NullableString)
			bio.SetNull(structpb.NullValue_NULL_VALUE)
		}
		target.SetBio(bio)
	}
	if source.Preferences.Valid {
		var preferences *structpb.Struct
		if source.Preferences.Value != nil {
			preferences2, err := structpb.NewStruct(source.Preferences.Value)
			if err != nil {
				return nil, err
			}
			preferences = preferences2
		}
		target.SetPreferences(preferences)
	}
	target.SetActorId(source.ActorID)
	return target, nil
}

func (upr UpdateProfileRequest) ToProto() (*patchpbv1.UpdateProfileRequest, error) {
	return UpdateProfileRequestToProto(upr)
}
