// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/kitchensink/v1/kitchen_sink.proto

package kitchensinkpbv1

import (
	_ "github.com/seeruk/tego/tegopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_ARCHIVED    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_ARCHIVED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_ARCHIVED":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kitchensink_v1_kitchen_sink_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_kitchensink_v1_kitchen_sink_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type KitchenSink struct {
	state                         protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_BoolValue          bool                               `protobuf:"varint,1,opt,name=bool_value,json=boolValue"`
	xxx_hidden_Int32Value         int32                              `protobuf:"varint,2,opt,name=int32_value,json=int32Value"`
	xxx_hidden_Sint32Value        int32                              `protobuf:"zigzag32,3,opt,name=sint32_value,json=sint32Value"`
	xxx_hidden_Sfixed32Value      int32                              `protobuf:"fixed32,4,opt,name=sfixed32_value,json=sfixed32Value"`
	xxx_hidden_Uint32Value        uint32                             `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value"`
	xxx_hidden_Fixed32Value       uint32                             `protobuf:"fixed32,6,opt,name=fixed32_value,json=fixed32Value"`
	xxx_hidden_Int64Value         int64                              `protobuf:"varint,7,opt,name=int64_value,json=int64Value"`
	xxx_hidden_Sint64Value        int64                              `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value"`
	xxx_hidden_Sfixed64Value      int64                              `protobuf:"fixed64,9,opt,name=sfixed64_value,json=sfixed64Value"`
	xxx_hidden_Uint64Value        uint64                             `protobuf:"varint,10,opt,name=uint64_value,json=uint64Value"`
	xxx_hidden_Fixed64Value       uint64                             `protobuf:"fixed64,11,opt,name=fixed64_value,json=fixed64Value"`
	xxx_hidden_FloatValue         float32                            `protobuf:"fixed32,12,opt,name=float_value,json=floatValue"`
	xxx_hidden_DoubleValue        float64                            `protobuf:"fixed64,13,opt,name=double_value,json=doubleValue"`
	xxx_hidden_StringValue        *string                            `protobuf:"bytes,14,opt,name=string_value,json=stringValue"`
	xxx_hidden_BytesValue         []byte                             `protobuf:"bytes,15,opt,name=bytes_value,json=bytesValue"`
	xxx_hidden_Status             Status                             `protobuf:"varint,16,opt,name=status,enum=kitchensink.v1.Status"`
	xxx_hidden_Tags               []string                           `protobuf:"bytes,17,rep,name=tags"`
	xxx_hidden_Counts             map[string]int32                   `protobuf:"bytes,18,rep,name=counts" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_WrappedBool        *wrapperspb.BoolValue              `protobuf:"bytes,19,opt,name=wrapped_bool,json=wrappedBool"`
	xxx_hidden_WrappedString      *wrapperspb.StringValue            `protobuf:"bytes,20,opt,name=wrapped_string,json=wrappedString"`
	xxx_hidden_CreatedAt          *timestamppb.Timestamp             `protobuf:"bytes,21,opt,name=created_at,json=createdAt"`
	xxx_hidden_Ttl                *durationpb.Duration               `protobuf:"bytes,22,opt,name=ttl"`
	xxx_hidden_StructValue        *structpb.Struct                   `protobuf:"bytes,23,opt,name=struct_value,json=structValue"`
	xxx_hidden_DynamicValue       *structpb.Value                    `protobuf:"bytes,24,opt,name=dynamic_value,json=dynamicValue"`
	xxx_hidden_ListValue          *structpb.ListValue                `protobuf:"bytes,25,opt,name=list_value,json=listValue"`
	xxx_hidden_AnyValue           *anypb.Any                         `protobuf:"bytes,26,opt,name=any_value,json=anyValue"`
	xxx_hidden_EmptyValue         *emptypb.Empty                     `protobuf:"bytes,27,opt,name=empty_value,json=emptyValue"`
	xxx_hidden_Choice             *Choice                            `protobuf:"bytes,28,opt,name=choice"`
	xxx_hidden_WrappedStrings     *[]*wrapperspb.StringValue         `protobuf:"bytes,29,rep,name=wrapped_strings,json=wrappedStrings"`
	xxx_hidden_WrappedStringsById map[string]*wrapperspb.StringValue `protobuf:"bytes,30,rep,name=wrapped_strings_by_id,json=wrappedStringsById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_WrappedBools       *[]*wrapperspb.BoolValue           `protobuf:"bytes,31,rep,name=wrapped_bools,json=wrappedBools"`
	xxx_hidden_WrappedBoolsById   map[string]*wrapperspb.BoolValue   `protobuf:"bytes,32,rep,name=wrapped_bools_by_id,json=wrappedBoolsById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_CreatedAtHistory   *[]*timestamppb.Timestamp          `protobuf:"bytes,33,rep,name=created_at_history,json=createdAtHistory"`
	xxx_hidden_CreatedAtById      map[string]*timestamppb.Timestamp  `protobuf:"bytes,34,rep,name=created_at_by_id,json=createdAtById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Ttls               *[]*durationpb.Duration            `protobuf:"bytes,35,rep,name=ttls"`
	xxx_hidden_TtlsById           map[string]*durationpb.Duration    `protobuf:"bytes,36,rep,name=ttls_by_id,json=ttlsById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_StructValues       *[]*structpb.Struct                `protobuf:"bytes,37,rep,name=struct_values,json=structValues"`
	xxx_hidden_StructValuesById   map[string]*structpb.Struct        `protobuf:"bytes,38,rep,name=struct_values_by_id,json=structValuesById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DynamicValues      *[]*structpb.Value                 `protobuf:"bytes,39,rep,name=dynamic_values,json=dynamicValues"`
	xxx_hidden_DynamicValuesById  map[string]*structpb.Value         `protobuf:"bytes,40,rep,name=dynamic_values_by_id,json=dynamicValuesById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ListValues         *[]*structpb.ListValue             `protobuf:"bytes,41,rep,name=list_values,json=listValues"`
	xxx_hidden_ListValuesById     map[string]*structpb.ListValue     `protobuf:"bytes,42,rep,name=list_values_by_id,json=listValuesById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_AnyValues          *[]*anypb.Any                      `protobuf:"bytes,43,rep,name=any_values,json=anyValues"`
	xxx_hidden_AnyValuesById      map[string]*anypb.Any              `protobuf:"bytes,44,rep,name=any_values_by_id,json=anyValuesById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_EmptyValues        *[]*emptypb.Empty                  `protobuf:"bytes,45,rep,name=empty_values,json=emptyValues"`
	xxx_hidden_EmptyValuesById    map[string]*emptypb.Empty          `protobuf:"bytes,46,rep,name=empty_values_by_id,json=emptyValuesById" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [2]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *KitchenSink) Reset() {
	*x = KitchenSink{}
	mi := &file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenSink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenSink) ProtoMessage() {}

func (x *KitchenSink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KitchenSink) GetBoolValue() bool {
	if x != nil {
		return x.xxx_hidden_BoolValue
	}
	return false
}

func (x *KitchenSink) GetInt32Value() int32 {
	if x != nil {
		return x.xxx_hidden_Int32Value
	}
	return 0
}

func (x *KitchenSink) GetSint32Value() int32 {
	if x != nil {
		return x.xxx_hidden_Sint32Value
	}
	return 0
}

func (x *KitchenSink) GetSfixed32Value() int32 {
	if x != nil {
		return x.xxx_hidden_Sfixed32Value
	}
	return 0
}

func (x *KitchenSink) GetUint32Value() uint32 {
	if x != nil {
		return x.xxx_hidden_Uint32Value
	}
	return 0
}

func (x *KitchenSink) GetFixed32Value() uint32 {
	if x != nil {
		return x.xxx_hidden_Fixed32Value
	}
	return 0
}

func (x *KitchenSink) GetInt64Value() int64 {
	if x != nil {
		return x.xxx_hidden_Int64Value
	}
	return 0
}

func (x *KitchenSink) GetSint64Value() int64 {
	if x != nil {
		return x.xxx_hidden_Sint64Value
	}
	return 0
}

func (x *KitchenSink) GetSfixed64Value() int64 {
	if x != nil {
		return x.xxx_hidden_Sfixed64Value
	}
	return 0
}

func (x *KitchenSink) GetUint64Value() uint64 {
	if x != nil {
		return x.xxx_hidden_Uint64Value
	}
	return 0
}

func (x *KitchenSink) GetFixed64Value() uint64 {
	if x != nil {
		return x.xxx_hidden_Fixed64Value
	}
	return 0
}

func (x *KitchenSink) GetFloatValue() float32 {
	if x != nil {
		return x.xxx_hidden_FloatValue
	}
	return 0
}

func (x *KitchenSink) GetDoubleValue() float64 {
	if x != nil {
		return x.xxx_hidden_DoubleValue
	}
	return 0
}

func (x *KitchenSink) GetStringValue() string {
	if x != nil {
		if x.xxx_hidden_StringValue != nil {
			return *x.xxx_hidden_StringValue
		}
		return ""
	}
	return ""
}

func (x *KitchenSink) GetBytesValue() []byte {
	if x != nil {
		return x.xxx_hidden_BytesValue
	}
	return nil
}

func (x *KitchenSink) GetStatus() Status {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 15) {
			return x.xxx_hidden_Status
		}
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *KitchenSink) GetTags() []string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *KitchenSink) GetCounts() map[string]int32 {
	if x != nil {
		return x.xxx_hidden_Counts
	}
	return nil
}

func (x *KitchenSink) GetWrappedBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_WrappedBool
	}
	return nil
}

func (x *KitchenSink) GetWrappedString() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_WrappedString
	}
	return nil
}

func (x *KitchenSink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *KitchenSink) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Ttl
	}
	return nil
}

func (x *KitchenSink) GetStructValue() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_StructValue
	}
	return nil
}

func (x *KitchenSink) GetDynamicValue() *structpb.Value {
	if x != nil {
		return x.xxx_hidden_DynamicValue
	}
	return nil
}

func (x *KitchenSink) GetListValue() *structpb.ListValue {
	if x != nil {
		return x.xxx_hidden_ListValue
	}
	return nil
}

func (x *KitchenSink) GetAnyValue() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_AnyValue
	}
	return nil
}

func (x *KitchenSink) GetEmptyValue() *emptypb.Empty {
	if x != nil {
		return x.xxx_hidden_EmptyValue
	}
	return nil
}

func (x *KitchenSink) GetChoice() *Choice {
	if x != nil {
		return x.xxx_hidden_Choice
	}
	return nil
}

func (x *KitchenSink) GetWrappedStrings() []*wrapperspb.StringValue {
	if x != nil {
		if x.xxx_hidden_WrappedStrings != nil {
			return *x.xxx_hidden_WrappedStrings
		}
	}
	return nil
}

func (x *KitchenSink) GetWrappedStringsById() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_WrappedStringsById
	}
	return nil
}

func (x *KitchenSink) GetWrappedBools() []*wrapperspb.BoolValue {
	if x != nil {
		if x.xxx_hidden_WrappedBools != nil {
			return *x.xxx_hidden_WrappedBools
		}
	}
	return nil
}

func (x *KitchenSink) GetWrappedBoolsById() map[string]*wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_WrappedBoolsById
	}
	return nil
}

func (x *KitchenSink) GetCreatedAtHistory() []*timestamppb.Timestamp {
	if x != nil {
		if x.xxx_hidden_CreatedAtHistory != nil {
			return *x.xxx_hidden_CreatedAtHistory
		}
	}
	return nil
}

func (x *KitchenSink) GetCreatedAtById() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAtById
	}
	return nil
}

func (x *KitchenSink) GetTtls() []*durationpb.Duration {
	if x != nil {
		if x.xxx_hidden_Ttls != nil {
			return *x.xxx_hidden_Ttls
		}
	}
	return nil
}

func (x *KitchenSink) GetTtlsById() map[string]*durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_TtlsById
	}
	return nil
}

func (x *KitchenSink) GetStructValues() []*structpb.Struct {
	if x != nil {
		if x.xxx_hidden_StructValues != nil {
			return *x.xxx_hidden_StructValues
		}
	}
	return nil
}

func (x *KitchenSink) GetStructValuesById() map[string]*structpb.Struct {
	if x != nil {
		return x.xxx_hidden_StructValuesById
	}
	return nil
}

func (x *KitchenSink) GetDynamicValues() []*structpb.Value {
	if x != nil {
		if x.xxx_hidden_DynamicValues != nil {
			return *x.xxx_hidden_DynamicValues
		}
	}
	return nil
}

func (x *KitchenSink) GetDynamicValuesById() map[string]*structpb.Value {
	if x != nil {
		return x.xxx_hidden_DynamicValuesById
	}
	return nil
}

func (x *KitchenSink) GetListValues() []*structpb.ListValue {
	if x != nil {
		if x.xxx_hidden_ListValues != nil {
			return *x.xxx_hidden_ListValues
		}
	}
	return nil
}

func (x *KitchenSink) GetListValuesById() map[string]*structpb.ListValue {
	if x != nil {
		return x.xxx_hidden_ListValuesById
	}
	return nil
}

func (x *KitchenSink) GetAnyValues() []*anypb.Any {
	if x != nil {
		if x.xxx_hidden_AnyValues != nil {
			return *x.xxx_hidden_AnyValues
		}
	}
	return nil
}

func (x *KitchenSink) GetAnyValuesById() map[string]*anypb.Any {
	if x != nil {
		return x.xxx_hidden_AnyValuesById
	}
	return nil
}

func (x *KitchenSink) GetEmptyValues() []*emptypb.Empty {
	if x != nil {
		if x.xxx_hidden_EmptyValues != nil {
			return *x.xxx_hidden_EmptyValues
		}
	}
	return nil
}

func (x *KitchenSink) GetEmptyValuesById() map[string]*emptypb.Empty {
	if x != nil {
		return x.xxx_hidden_EmptyValuesById
	}
	return nil
}

func (x *KitchenSink) SetBoolValue(v bool) {
	x.xxx_hidden_BoolValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 46)
}

func (x *KitchenSink) SetInt32Value(v int32) {
	x.xxx_hidden_Int32Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 46)
}

func (x *KitchenSink) SetSint32Value(v int32) {
	x.xxx_hidden_Sint32Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 46)
}

func (x *KitchenSink) SetSfixed32Value(v int32) {
	x.xxx_hidden_Sfixed32Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 46)
}

func (x *KitchenSink) SetUint32Value(v uint32) {
	x.xxx_hidden_Uint32Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 46)
}

func (x *KitchenSink) SetFixed32Value(v uint32) {
	x.xxx_hidden_Fixed32Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 46)
}

func (x *KitchenSink) SetInt64Value(v int64) {
	x.xxx_hidden_Int64Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 46)
}

func (x *KitchenSink) SetSint64Value(v int64) {
	x.xxx_hidden_Sint64Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 46)
}

func (x *KitchenSink) SetSfixed64Value(v int64) {
	x.xxx_hidden_Sfixed64Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 46)
}

func (x *KitchenSink) SetUint64Value(v uint64) {
	x.xxx_hidden_Uint64Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 46)
}

func (x *KitchenSink) SetFixed64Value(v uint64) {
	x.xxx_hidden_Fixed64Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 46)
}

func (x *KitchenSink) SetFloatValue(v float32) {
	x.xxx_hidden_FloatValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 46)
}

func (x *KitchenSink) SetDoubleValue(v float64) {
	x.xxx_hidden_DoubleValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 46)
}

func (x *KitchenSink) SetStringValue(v string) {
	x.xxx_hidden_StringValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 46)
}

func (x *KitchenSink) SetBytesValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_BytesValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 46)
}

func (x *KitchenSink) SetStatus(v Status) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 46)
}

func (x *KitchenSink) SetTags(v []string) {
	x.xxx_hidden_Tags = v
}

func (x *KitchenSink) SetCounts(v map[string]int32) {
	x.xxx_hidden_Counts = v
}

func (x *KitchenSink) SetWrappedBool(v *wrapperspb.BoolValue) {
	x.xxx_hidden_WrappedBool = v
}

func (x *KitchenSink) SetWrappedString(v *wrapperspb.StringValue) {
	x.xxx_hidden_WrappedString = v
}

func (x *KitchenSink) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *KitchenSink) SetTtl(v *durationpb.Duration) {
	x.xxx_hidden_Ttl = v
}

func (x *KitchenSink) SetStructValue(v *structpb.Struct) {
	x.xxx_hidden_StructValue = v
}

func (x *KitchenSink) SetDynamicValue(v *structpb.Value) {
	x.xxx_hidden_DynamicValue = v
}

func (x *KitchenSink) SetListValue(v *structpb.ListValue) {
	x.xxx_hidden_ListValue = v
}

func (x *KitchenSink) SetAnyValue(v *anypb.Any) {
	x.xxx_hidden_AnyValue = v
}

func (x *KitchenSink) SetEmptyValue(v *emptypb.Empty) {
	x.xxx_hidden_EmptyValue = v
}

func (x *KitchenSink) SetChoice(v *Choice) {
	x.xxx_hidden_Choice = v
}

func (x *KitchenSink) SetWrappedStrings(v []*wrapperspb.StringValue) {
	x.xxx_hidden_WrappedStrings = &v
}

func (x *KitchenSink) SetWrappedStringsById(v map[string]*wrapperspb.StringValue) {
	x.xxx_hidden_WrappedStringsById = v
}

func (x *KitchenSink) SetWrappedBools(v []*wrapperspb.BoolValue) {
	x.xxx_hidden_WrappedBools = &v
}

func (x *KitchenSink) SetWrappedBoolsById(v map[string]*wrapperspb.BoolValue) {
	x.xxx_hidden_WrappedBoolsById = v
}

func (x *KitchenSink) SetCreatedAtHistory(v []*timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAtHistory = &v
}

func (x *KitchenSink) SetCreatedAtById(v map[string]*timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAtById = v
}

func (x *KitchenSink) SetTtls(v []*durationpb.Duration) {
	x.xxx_hidden_Ttls = &v
}

func (x *KitchenSink) SetTtlsById(v map[string]*durationpb.Duration) {
	x.xxx_hidden_TtlsById = v
}

func (x *KitchenSink) SetStructValues(v []*structpb.Struct) {
	x.xxx_hidden_StructValues = &v
}

func (x *KitchenSink) SetStructValuesById(v map[string]*structpb.Struct) {
	x.xxx_hidden_StructValuesById = v
}

func (x *KitchenSink) SetDynamicValues(v []*structpb.Value) {
	x.xxx_hidden_DynamicValues = &v
}

func (x *KitchenSink) SetDynamicValuesById(v map[string]*structpb.Value) {
	x.xxx_hidden_DynamicValuesById = v
}

func (x *KitchenSink) SetListValues(v []*structpb.ListValue) {
	x.xxx_hidden_ListValues = &v
}

func (x *KitchenSink) SetListValuesById(v map[string]*structpb.ListValue) {
	x.xxx_hidden_ListValuesById = v
}

func (x *KitchenSink) SetAnyValues(v []*anypb.Any) {
	x.xxx_hidden_AnyValues = &v
}

func (x *KitchenSink) SetAnyValuesById(v map[string]*anypb.Any) {
	x.xxx_hidden_AnyValuesById = v
}

func (x *KitchenSink) SetEmptyValues(v []*emptypb.Empty) {
	x.xxx_hidden_EmptyValues = &v
}

func (x *KitchenSink) SetEmptyValuesById(v map[string]*emptypb.Empty) {
	x.xxx_hidden_EmptyValuesById = v
}

func (x *KitchenSink) HasBoolValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KitchenSink) HasInt32Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KitchenSink) HasSint32Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *KitchenSink) HasSfixed32Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *KitchenSink) HasUint32Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *KitchenSink) HasFixed32Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *KitchenSink) HasInt64Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *KitchenSink) HasSint64Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *KitchenSink) HasSfixed64Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *KitchenSink) HasUint64Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *KitchenSink) HasFixed64Value() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *KitchenSink) HasFloatValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *KitchenSink) HasDoubleValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *KitchenSink) HasStringValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *KitchenSink) HasBytesValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *KitchenSink) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *KitchenSink) HasWrappedBool() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WrappedBool != nil
}

func (x *KitchenSink) HasWrappedString() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WrappedString != nil
}

func (x *KitchenSink) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *KitchenSink) HasTtl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ttl != nil
}

func (x *KitchenSink) HasStructValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StructValue != nil
}

func (x *KitchenSink) HasDynamicValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DynamicValue != nil
}

func (x *KitchenSink) HasListValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ListValue != nil
}

func (x *KitchenSink) HasAnyValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AnyValue != nil
}

func (x *KitchenSink) HasEmptyValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EmptyValue != nil
}

func (x *KitchenSink) HasChoice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Choice != nil
}

func (x *KitchenSink) ClearBoolValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BoolValue = false
}

func (x *KitchenSink) ClearInt32Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Int32Value = 0
}

func (x *KitchenSink) ClearSint32Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sint32Value = 0
}

func (x *KitchenSink) ClearSfixed32Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Sfixed32Value = 0
}

func (x *KitchenSink) ClearUint32Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Uint32Value = 0
}

func (x *KitchenSink) ClearFixed32Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Fixed32Value = 0
}

func (x *KitchenSink) ClearInt64Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Int64Value = 0
}

func (x *KitchenSink) ClearSint64Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Sint64Value = 0
}

func (x *KitchenSink) ClearSfixed64Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Sfixed64Value = 0
}

func (x *KitchenSink) ClearUint64Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Uint64Value = 0
}

func (x *KitchenSink) ClearFixed64Value() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Fixed64Value = 0
}

func (x *KitchenSink) ClearFloatValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_FloatValue = 0
}

func (x *KitchenSink) ClearDoubleValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_DoubleValue = 0
}

func (x *KitchenSink) ClearStringValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_StringValue = nil
}

func (x *KitchenSink) ClearBytesValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_BytesValue = nil
}

func (x *KitchenSink) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_Status = Status_STATUS_UNSPECIFIED
}

func (x *KitchenSink) ClearWrappedBool() {
	x.xxx_hidden_WrappedBool = nil
}

func (x *KitchenSink) ClearWrappedString() {
	x.xxx_hidden_WrappedString = nil
}

func (x *KitchenSink) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *KitchenSink) ClearTtl() {
	x.xxx_hidden_Ttl = nil
}

func (x *KitchenSink) ClearStructValue() {
	x.xxx_hidden_StructValue = nil
}

func (x *KitchenSink) ClearDynamicValue() {
	x.xxx_hidden_DynamicValue = nil
}

func (x *KitchenSink) ClearListValue() {
	x.xxx_hidden_ListValue = nil
}

func (x *KitchenSink) ClearAnyValue() {
	x.xxx_hidden_AnyValue = nil
}

func (x *KitchenSink) ClearEmptyValue() {
	x.xxx_hidden_EmptyValue = nil
}

func (x *KitchenSink) ClearChoice() {
	x.xxx_hidden_Choice = nil
}

type KitchenSink_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BoolValue          *bool
	Int32Value         *int32
	Sint32Value        *int32
	Sfixed32Value      *int32
	Uint32Value        *uint32
	Fixed32Value       *uint32
	Int64Value         *int64
	Sint64Value        *int64
	Sfixed64Value      *int64
	Uint64Value        *uint64
	Fixed64Value       *uint64
	FloatValue         *float32
	DoubleValue        *float64
	StringValue        *string
	BytesValue         []byte
	Status             *Status
	Tags               []string
	Counts             map[string]int32
	WrappedBool        *wrapperspb.BoolValue
	WrappedString      *wrapperspb.StringValue
	CreatedAt          *timestamppb.Timestamp
	Ttl                *durationpb.Duration
	StructValue        *structpb.Struct
	DynamicValue       *structpb.Value
	ListValue          *structpb.ListValue
	AnyValue           *anypb.Any
	EmptyValue         *emptypb.Empty
	Choice             *Choice
	WrappedStrings     []*wrapperspb.StringValue
	WrappedStringsById map[string]*wrapperspb.StringValue
	WrappedBools       []*wrapperspb.BoolValue
	WrappedBoolsById   map[string]*wrapperspb.BoolValue
	CreatedAtHistory   []*timestamppb.Timestamp
	CreatedAtById      map[string]*timestamppb.Timestamp
	Ttls               []*durationpb.Duration
	TtlsById           map[string]*durationpb.Duration
	StructValues       []*structpb.Struct
	StructValuesById   map[string]*structpb.Struct
	DynamicValues      []*structpb.Value
	DynamicValuesById  map[string]*structpb.Value
	ListValues         []*structpb.ListValue
	ListValuesById     map[string]*structpb.ListValue
	AnyValues          []*anypb.Any
	AnyValuesById      map[string]*anypb.Any
	EmptyValues        []*emptypb.Empty
	EmptyValuesById    map[string]*emptypb.Empty
}

func (b0 KitchenSink_builder) Build() *KitchenSink {
	m0 := &KitchenSink{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BoolValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 46)
		x.xxx_hidden_BoolValue = *b.BoolValue
	}
	if b.Int32Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 46)
		x.xxx_hidden_Int32Value = *b.Int32Value
	}
	if b.Sint32Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 46)
		x.xxx_hidden_Sint32Value = *b.Sint32Value
	}
	if b.Sfixed32Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 46)
		x.xxx_hidden_Sfixed32Value = *b.Sfixed32Value
	}
	if b.Uint32Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 46)
		x.xxx_hidden_Uint32Value = *b.Uint32Value
	}
	if b.Fixed32Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 46)
		x.xxx_hidden_Fixed32Value = *b.Fixed32Value
	}
	if b.Int64Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 46)
		x.xxx_hidden_Int64Value = *b.Int64Value
	}
	if b.Sint64Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 46)
		x.xxx_hidden_Sint64Value = *b.Sint64Value
	}
	if b.Sfixed64Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 46)
		x.xxx_hidden_Sfixed64Value = *b.Sfixed64Value
	}
	if b.Uint64Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 46)
		x.xxx_hidden_Uint64Value = *b.Uint64Value
	}
	if b.Fixed64Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 46)
		x.xxx_hidden_Fixed64Value = *b.Fixed64Value
	}
	if b.FloatValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 46)
		x.xxx_hidden_FloatValue = *b.FloatValue
	}
	if b.DoubleValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 46)
		x.xxx_hidden_DoubleValue = *b.DoubleValue
	}
	if b.StringValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 46)
		x.xxx_hidden_StringValue = b.StringValue
	}
	if b.BytesValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 46)
		x.xxx_hidden_BytesValue = b.BytesValue
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 46)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Tags = b.Tags
	x.xxx_hidden_Counts = b.Counts
	x.xxx_hidden_WrappedBool = b.WrappedBool
	x.xxx_hidden_WrappedString = b.WrappedString
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Ttl = b.Ttl
	x.xxx_hidden_StructValue = b.StructValue
	x.xxx_hidden_DynamicValue = b.DynamicValue
	x.xxx_hidden_ListValue = b.ListValue
	x.xxx_hidden_AnyValue = b.AnyValue
	x.xxx_hidden_EmptyValue = b.EmptyValue
	x.xxx_hidden_Choice = b.Choice
	x.xxx_hidden_WrappedStrings = &b.WrappedStrings
	x.xxx_hidden_WrappedStringsById = b.WrappedStringsById
	x.xxx_hidden_WrappedBools = &b.WrappedBools
	x.xxx_hidden_WrappedBoolsById = b.WrappedBoolsById
	x.xxx_hidden_CreatedAtHistory = &b.CreatedAtHistory
	x.xxx_hidden_CreatedAtById = b.CreatedAtById
	x.xxx_hidden_Ttls = &b.Ttls
	x.xxx_hidden_TtlsById = b.TtlsById
	x.xxx_hidden_StructValues = &b.StructValues
	x.xxx_hidden_StructValuesById = b.StructValuesById
	x.xxx_hidden_DynamicValues = &b.DynamicValues
	x.xxx_hidden_DynamicValuesById = b.DynamicValuesById
	x.xxx_hidden_ListValues = &b.ListValues
	x.xxx_hidden_ListValuesById = b.ListValuesById
	x.xxx_hidden_AnyValues = &b.AnyValues
	x.xxx_hidden_AnyValuesById = b.AnyValuesById
	x.xxx_hidden_EmptyValues = &b.EmptyValues
	x.xxx_hidden_EmptyValuesById = b.EmptyValuesById
	return m0
}

type Choice struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isChoice_Value         `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Choice) GetText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*choice_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Choice) GetNumber() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*choice_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Choice) SetText(v string) {
	x.xxx_hidden_Value = &choice_Text{v}
}

func (x *Choice) SetNumber(v int32) {
	x.xxx_hidden_Value = &choice_Number{v}
}

func (x *Choice) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *Choice) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*choice_Text)
	return ok
}

func (x *Choice) HasNumber() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*choice_Number)
	return ok
}

func (x *Choice) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *Choice) ClearText() {
	if _, ok := x.xxx_hidden_Value.(*choice_Text); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *Choice) ClearNumber() {
	if _, ok := x.xxx_hidden_Value.(*choice_Number); ok {
		x.xxx_hidden_Value = nil
	}
}

const Choice_Value_not_set_case case_Choice_Value = 0
const Choice_Text_case case_Choice_Value = 1
const Choice_Number_case case_Choice_Value = 2

func (x *Choice) WhichValue() case_Choice_Value {
	if x == nil {
		return Choice_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *choice_Text:
		return Choice_Text_case
	case *choice_Number:
		return Choice_Number_case
	default:
		return Choice_Value_not_set_case
	}
}

type Choice_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	Text   *string
	Number *int32
	// -- end of xxx_hidden_Value
}

func (b0 Choice_builder) Build() *Choice {
	m0 := &Choice{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		x.xxx_hidden_Value = &choice_Text{*b.Text}
	}
	if b.Number != nil {
		x.xxx_hidden_Value = &choice_Number{*b.Number}
	}
	return m0
}

type case_Choice_Value protoreflect.FieldNumber

func (x case_Choice_Value) String() string {
	md := file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isChoice_Value interface {
	isChoice_Value()
}

type choice_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,oneof"`
}

type choice_Number struct {
	Number int32 `protobuf:"varint,2,opt,name=number,oneof"`
}

func (*choice_Text) isChoice_Value() {}

func (*choice_Number) isChoice_Value() {}

var File_proto_kitchensink_v1_kitchen_sink_proto protoreflect.FileDescriptor

const file_proto_kitchensink_v1_kitchen_sink_proto_rawDesc = "" +
	"\n" +
	"'proto/kitchensink/v1/kitchen_sink.proto\x12\x0ekitchensink.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12tego/options.proto\"\xd3\x1b\n" +
	"\vKitchenSink\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bR\tboolValue\x12\x1f\n" +
	"\vint32_value\x18\x02 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fsint32_value\x18\x03 \x01(\x11R\vsint32Value\x12%\n" +
	"\x0esfixed32_value\x18\x04 \x01(\x0fR\rsfixed32Value\x12!\n" +
	"\fuint32_value\x18\x05 \x01(\rR\vuint32Value\x12#\n" +
	"\rfixed32_value\x18\x06 \x01(\aR\ffixed32Value\x12\x1f\n" +
	"\vint64_value\x18\a \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fsint64_value\x18\b \x01(\x12R\vsint64Value\x12%\n" +
	"\x0esfixed64_value\x18\t \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fuint64_value\x18\n" +
	" \x01(\x04R\vuint64Value\x12#\n" +
	"\rfixed64_value\x18\v \x01(\x06R\ffixed64Value\x12\x1f\n" +
	"\vfloat_value\x18\f \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\r \x01(\x01R\vdoubleValue\x12!\n" +
	"\fstring_value\x18\x0e \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x0f \x01(\fR\n" +
	"bytesValue\x12.\n" +
	"\x06status\x18\x10 \x01(\x0e2\x16.kitchensink.v1.StatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x11 \x03(\tR\x04tags\x12?\n" +
	"\x06counts\x18\x12 \x03(\v2'.kitchensink.v1.KitchenSink.CountsEntryR\x06counts\x12=\n" +
	"\fwrapped_bool\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueR\vwrappedBool\x12C\n" +
	"\x0ewrapped_string\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\rwrappedString\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x03ttl\x18\x16 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12:\n" +
	"\fstruct_value\x18\x17 \x01(\v2\x17.google.protobuf.StructR\vstructValue\x12;\n" +
	"\rdynamic_value\x18\x18 \x01(\v2\x16.google.protobuf.ValueR\fdynamicValue\x129\n" +
	"\n" +
	"list_value\x18\x19 \x01(\v2\x1a.google.protobuf.ListValueR\tlistValue\x121\n" +
	"\tany_value\x18\x1a \x01(\v2\x14.google.protobuf.AnyR\banyValue\x127\n" +
	"\vempty_value\x18\x1b \x01(\v2\x16.google.protobuf.EmptyR\n" +
	"emptyValue\x12.\n" +
	"\x06choice\x18\x1c \x01(\v2\x16.kitchensink.v1.ChoiceR\x06choice\x12E\n" +
	"\x0fwrapped_strings\x18\x1d \x03(\v2\x1c.google.protobuf.StringValueR\x0ewrappedStrings\x12f\n" +
	"\x15wrapped_strings_by_id\x18\x1e \x03(\v23.kitchensink.v1.KitchenSink.WrappedStringsByIdEntryR\x12wrappedStringsById\x12?\n" +
	"\rwrapped_bools\x18\x1f \x03(\v2\x1a.google.protobuf.BoolValueR\fwrappedBools\x12`\n" +
	"\x13wrapped_bools_by_id\x18  \x03(\v21.kitchensink.v1.KitchenSink.WrappedBoolsByIdEntryR\x10wrappedBoolsById\x12H\n" +
	"\x12created_at_history\x18! \x03(\v2\x1a.google.protobuf.TimestampR\x10createdAtHistory\x12W\n" +
	"\x10created_at_by_id\x18\" \x03(\v2..kitchensink.v1.KitchenSink.CreatedAtByIdEntryR\rcreatedAtById\x12-\n" +
	"\x04ttls\x18# \x03(\v2\x19.google.protobuf.DurationR\x04ttls\x12G\n" +
	"\n" +
	"ttls_by_id\x18$ \x03(\v2).kitchensink.v1.KitchenSink.TtlsByIdEntryR\bttlsById\x12<\n" +
	"\rstruct_values\x18% \x03(\v2\x17.google.protobuf.StructR\fstructValues\x12`\n" +
	"\x13struct_values_by_id\x18& \x03(\v21.kitchensink.v1.KitchenSink.StructValuesByIdEntryR\x10structValuesById\x12=\n" +
	"\x0edynamic_values\x18' \x03(\v2\x16.google.protobuf.ValueR\rdynamicValues\x12c\n" +
	"\x14dynamic_values_by_id\x18( \x03(\v22.kitchensink.v1.KitchenSink.DynamicValuesByIdEntryR\x11dynamicValuesById\x12;\n" +
	"\vlist_values\x18) \x03(\v2\x1a.google.protobuf.ListValueR\n" +
	"listValues\x12Z\n" +
	"\x11list_values_by_id\x18* \x03(\v2/.kitchensink.v1.KitchenSink.ListValuesByIdEntryR\x0elistValuesById\x123\n" +
	"\n" +
	"any_values\x18+ \x03(\v2\x14.google.protobuf.AnyR\tanyValues\x12W\n" +
	"\x10any_values_by_id\x18, \x03(\v2..kitchensink.v1.KitchenSink.AnyValuesByIdEntryR\ranyValuesById\x129\n" +
	"\fempty_values\x18- \x03(\v2\x16.google.protobuf.EmptyR\vemptyValues\x12]\n" +
	"\x12empty_values_by_id\x18. \x03(\v20.kitchensink.v1.KitchenSink.EmptyValuesByIdEntryR\x0femptyValuesById\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1ac\n" +
	"\x17WrappedStringsByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1a_\n" +
	"\x15WrappedBoolsByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x05value:\x028\x01\x1a\\\n" +
	"\x12CreatedAtByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1aV\n" +
	"\rTtlsByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1a\\\n" +
	"\x15StructValuesByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\x1a\\\n" +
	"\x16DynamicValuesByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1a]\n" +
	"\x13ListValuesByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.ListValueR\x05value:\x028\x01\x1aV\n" +
	"\x12AnyValuesByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1aZ\n" +
	"\x14EmptyValuesByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.EmptyR\x05value:\x028\x01\"A\n" +
	"\x06Choice\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x02 \x01(\x05H\x00R\x06numberB\a\n" +
	"\x05value*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_ARCHIVED\x10\x02B\x98\x01҅\n" +
	"F\n" +
	"Dgithub.com/seeruk/tego/examples/kitchen-sink/kitchensink;kitchensinkZLgithub.com/seeruk/tego/examples/kitchen-sink/kitchensinkpbv1;kitchensinkpbv1b\beditionsp\xe9\a"

var file_proto_kitchensink_v1_kitchen_sink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_kitchensink_v1_kitchen_sink_proto_goTypes = []any{
	(Status)(0),                    // 0: kitchensink.v1.Status
	(*KitchenSink)(nil),            // 1: kitchensink.v1.KitchenSink
	(*Choice)(nil),                 // 2: kitchensink.v1.Choice
	nil,                            // 3: kitchensink.v1.KitchenSink.CountsEntry
	nil,                            // 4: kitchensink.v1.KitchenSink.WrappedStringsByIdEntry
	nil,                            // 5: kitchensink.v1.KitchenSink.WrappedBoolsByIdEntry
	nil,                            // 6: kitchensink.v1.KitchenSink.CreatedAtByIdEntry
	nil,                            // 7: kitchensink.v1.KitchenSink.TtlsByIdEntry
	nil,                            // 8: kitchensink.v1.KitchenSink.StructValuesByIdEntry
	nil,                            // 9: kitchensink.v1.KitchenSink.DynamicValuesByIdEntry
	nil,                            // 10: kitchensink.v1.KitchenSink.ListValuesByIdEntry
	nil,                            // 11: kitchensink.v1.KitchenSink.AnyValuesByIdEntry
	nil,                            // 12: kitchensink.v1.KitchenSink.EmptyValuesByIdEntry
	(*wrapperspb.BoolValue)(nil),   // 13: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 14: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 16: google.protobuf.Duration
	(*structpb.Struct)(nil),        // 17: google.protobuf.Struct
	(*structpb.Value)(nil),         // 18: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 19: google.protobuf.ListValue
	(*anypb.Any)(nil),              // 20: google.protobuf.Any
	(*emptypb.Empty)(nil),          // 21: google.protobuf.Empty
}
var file_proto_kitchensink_v1_kitchen_sink_proto_depIdxs = []int32{
	0,  // 0: kitchensink.v1.KitchenSink.status:type_name -> kitchensink.v1.Status
	3,  // 1: kitchensink.v1.KitchenSink.counts:type_name -> kitchensink.v1.KitchenSink.CountsEntry
	13, // 2: kitchensink.v1.KitchenSink.wrapped_bool:type_name -> google.protobuf.BoolValue
	14, // 3: kitchensink.v1.KitchenSink.wrapped_string:type_name -> google.protobuf.StringValue
	15, // 4: kitchensink.v1.KitchenSink.created_at:type_name -> google.protobuf.Timestamp
	16, // 5: kitchensink.v1.KitchenSink.ttl:type_name -> google.protobuf.Duration
	17, // 6: kitchensink.v1.KitchenSink.struct_value:type_name -> google.protobuf.Struct
	18, // 7: kitchensink.v1.KitchenSink.dynamic_value:type_name -> google.protobuf.Value
	19, // 8: kitchensink.v1.KitchenSink.list_value:type_name -> google.protobuf.ListValue
	20, // 9: kitchensink.v1.KitchenSink.any_value:type_name -> google.protobuf.Any
	21, // 10: kitchensink.v1.KitchenSink.empty_value:type_name -> google.protobuf.Empty
	2,  // 11: kitchensink.v1.KitchenSink.choice:type_name -> kitchensink.v1.Choice
	14, // 12: kitchensink.v1.KitchenSink.wrapped_strings:type_name -> google.protobuf.StringValue
	4,  // 13: kitchensink.v1.KitchenSink.wrapped_strings_by_id:type_name -> kitchensink.v1.KitchenSink.WrappedStringsByIdEntry
	13, // 14: kitchensink.v1.KitchenSink.wrapped_bools:type_name -> google.protobuf.BoolValue
	5,  // 15: kitchensink.v1.KitchenSink.wrapped_bools_by_id:type_name -> kitchensink.v1.KitchenSink.WrappedBoolsByIdEntry
	15, // 16: kitchensink.v1.KitchenSink.created_at_history:type_name -> google.protobuf.Timestamp
	6,  // 17: kitchensink.v1.KitchenSink.created_at_by_id:type_name -> kitchensink.v1.KitchenSink.CreatedAtByIdEntry
	16, // 18: kitchensink.v1.KitchenSink.ttls:type_name -> google.protobuf.Duration
	7,  // 19: kitchensink.v1.KitchenSink.ttls_by_id:type_name -> kitchensink.v1.KitchenSink.TtlsByIdEntry
	17, // 20: kitchensink.v1.KitchenSink.struct_values:type_name -> google.protobuf.Struct
	8,  // 21: kitchensink.v1.KitchenSink.struct_values_by_id:type_name -> kitchensink.v1.KitchenSink.StructValuesByIdEntry
	18, // 22: kitchensink.v1.KitchenSink.dynamic_values:type_name -> google.protobuf.Value
	9,  // 23: kitchensink.v1.KitchenSink.dynamic_values_by_id:type_name -> kitchensink.v1.KitchenSink.DynamicValuesByIdEntry
	19, // 24: kitchensink.v1.KitchenSink.list_values:type_name -> google.protobuf.ListValue
	10, // 25: kitchensink.v1.KitchenSink.list_values_by_id:type_name -> kitchensink.v1.KitchenSink.ListValuesByIdEntry
	20, // 26: kitchensink.v1.KitchenSink.any_values:type_name -> google.protobuf.Any
	11, // 27: kitchensink.v1.KitchenSink.any_values_by_id:type_name -> kitchensink.v1.KitchenSink.AnyValuesByIdEntry
	21, // 28: kitchensink.v1.KitchenSink.empty_values:type_name -> google.protobuf.Empty
	12, // 29: kitchensink.v1.KitchenSink.empty_values_by_id:type_name -> kitchensink.v1.KitchenSink.EmptyValuesByIdEntry
	14, // 30: kitchensink.v1.KitchenSink.WrappedStringsByIdEntry.value:type_name -> google.protobuf.StringValue
	13, // 31: kitchensink.v1.KitchenSink.WrappedBoolsByIdEntry.value:type_name -> google.protobuf.BoolValue
	15, // 32: kitchensink.v1.KitchenSink.CreatedAtByIdEntry.value:type_name -> google.protobuf.Timestamp
	16, // 33: kitchensink.v1.KitchenSink.TtlsByIdEntry.value:type_name -> google.protobuf.Duration
	17, // 34: kitchensink.v1.KitchenSink.StructValuesByIdEntry.value:type_name -> google.protobuf.Struct
	18, // 35: kitchensink.v1.KitchenSink.DynamicValuesByIdEntry.value:type_name -> google.protobuf.Value
	19, // 36: kitchensink.v1.KitchenSink.ListValuesByIdEntry.value:type_name -> google.protobuf.ListValue
	20, // 37: kitchensink.v1.KitchenSink.AnyValuesByIdEntry.value:type_name -> google.protobuf.Any
	21, // 38: kitchensink.v1.KitchenSink.EmptyValuesByIdEntry.value:type_name -> google.protobuf.Empty
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_proto_kitchensink_v1_kitchen_sink_proto_init() }
func file_proto_kitchensink_v1_kitchen_sink_proto_init() {
	if File_proto_kitchensink_v1_kitchen_sink_proto != nil {
		return
	}
	file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes[1].OneofWrappers = []any{
		(*choice_Text)(nil),
		(*choice_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kitchensink_v1_kitchen_sink_proto_rawDesc), len(file_proto_kitchensink_v1_kitchen_sink_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kitchensink_v1_kitchen_sink_proto_goTypes,
		DependencyIndexes: file_proto_kitchensink_v1_kitchen_sink_proto_depIdxs,
		EnumInfos:         file_proto_kitchensink_v1_kitchen_sink_proto_enumTypes,
		MessageInfos:      file_proto_kitchensink_v1_kitchen_sink_proto_msgTypes,
	}.Build()
	File_proto_kitchensink_v1_kitchen_sink_proto = out.File
	file_proto_kitchensink_v1_kitchen_sink_proto_goTypes = nil
	file_proto_kitchensink_v1_kitchen_sink_proto_depIdxs = nil
}
