// Code generated by protoc-gen-tego. DO NOT EDIT.
package custom

import (
	custompbv1 "github.com/seeruk/tego/examples/custom-types/custompbv1"
	types "github.com/seeruk/tego/examples/custom-types/types"
)

type Customer struct {
	ID             types.UUID
	Email          types.Email
	CreditCents    types.Money
	DisplayName    *types.DisplayName
	Labels         types.Set[types.Label]
	ContactAliases types.Box[*[]*types.Email]
}

func CustomerFromProto(source *custompbv1.Customer) (Customer, error) {
	var target Customer
	if source == nil {
		return target, nil
	}
	id, err := types.UUIDFromProto(source.GetId())
	if err != nil {
		return target, err
	}
	target.ID = id
	var email types.Email
	if source.GetEmail() != nil {
		emailValue, err := types.EmailFromProto(source.GetEmail().GetValue())
		if err != nil {
			return target, err
		}
		email = emailValue
	}
	target.Email = email
	target.CreditCents = types.MoneyFromProto(source.GetCreditCents())
	target.DisplayName = types.DisplayNameFromProto(source.GetDisplayName())
	target.Labels = types.LabelSetFromProto(source.GetLabels())
	contactAliases, err := types.ContactAliasesFromProto(source.GetContactAliases())
	if err != nil {
		return target, err
	}
	target.ContactAliases = contactAliases
	return target, nil
}

func CustomerToProto(source Customer) (*custompbv1.Customer, error) {
	emailValue, err := types.EmailToProto(source.Email)
	if err != nil {
		return nil, err
	}
	email := custompbv1.EmailAddress_builder{
		Value: &emailValue,
	}.Build()
	contactAliases, err := types.ContactAliasesToProto(source.ContactAliases)
	if err != nil {
		return nil, err
	}
	target := custompbv1.Customer_builder{
		Id:             types.UUIDToProto(source.ID),
		Email:          email,
		CreditCents:    new(types.MoneyToProto(source.CreditCents)),
		DisplayName:    new(types.DisplayNameToProto(source.DisplayName)),
		Labels:         types.LabelSetToProto(source.Labels),
		ContactAliases: contactAliases,
	}.Build()
	return target, nil
}

func (c Customer) ToProto() (*custompbv1.Customer, error) {
	return CustomerToProto(c)
}
