// Code generated by protoc-gen-tego. DO NOT EDIT.
package books

import (
	connect "connectrpc.com/connect"
	context "context"
	fmt "fmt"
	tego "github.com/seeruk/tego"
	bookspbv1 "github.com/seeruk/tego/examples/error-mapping/bookspbv1"
	bookspbv1connect "github.com/seeruk/tego/examples/error-mapping/bookspbv1/bookspbv1connect"
	grpc "google.golang.org/grpc"
	http "net/http"
)

type GetBookRequest struct {
	ID string
}

type GetBookResponse struct {
	Book Book
}

type Book struct {
	ID     string
	Title  string
	Author string
}

func GetBookRequestToInline(ctx context.Context, request GetBookRequest) (context.Context, string) {
	return ctx, request.ID
}

func GetBookRequestFromInline(ctx context.Context, id string) (context.Context, GetBookRequest) {
	return ctx, GetBookRequest{ID: id}
}

func GetBookResponseToInline(response GetBookResponse, err error) (Book, error) {
	if err != nil {
		var zeroBook Book
		return zeroBook, err
	}
	return response.Book, nil
}

func GetBookResponseFromInline(book Book, err error) (GetBookResponse, error) {
	if err != nil {
		var zero GetBookResponse
		return zero, err
	}
	return GetBookResponse{Book: book}, nil
}

type BookService interface {
	GetBook(ctx context.Context, id string) (Book, error)
}

type UnimplementedBookService struct{}

func (UnimplementedBookService) GetBook(ctx context.Context, id string) (Book, error) {
	var zeroBook Book
	return zeroBook, unimplementedBookServiceError("GetBook")
}

func unimplementedBookServiceError(method string) error {
	return fmt.Errorf("BookService.%s: %w", method, tego.ErrUnimplemented)
}

func RegisterBookServiceGRPCServer(registrar grpc.ServiceRegistrar, service BookService, opts ...tego.GRPCServerOption) {
	bookspbv1.RegisterBookServiceServer(registrar, NewBookServiceGRPCServer(service, opts...))
}

func NewBookServiceGRPCServer(service BookService, opts ...tego.GRPCServerOption) bookspbv1.BookServiceServer {
	return NewBookServiceGRPCServerWithAdapter(NewBookServiceGRPCAdapter(service), opts...)
}

func NewBookServiceGRPCServerWithAdapter(adapter *BookServiceGRPCAdapter, opts ...tego.GRPCServerOption) bookspbv1.BookServiceServer {
	options := tego.NewGRPCServerOptions(opts...)
	adapter.errorMapper = options.ErrorMapper(adapter.errorMapper)
	return &bookServiceGRPCServer{BookServiceGRPCAdapter: adapter}
}

type bookServiceGRPCServer struct {
	bookspbv1.UnimplementedBookServiceServer
	*BookServiceGRPCAdapter
}

type BookServiceGRPCAdapter struct {
	service     BookService
	errorMapper tego.ErrorMapper
}

func NewBookServiceGRPCAdapter(service BookService, opts ...tego.GRPCAdapterOption) *BookServiceGRPCAdapter {
	options := tego.NewGRPCAdapterOptions(opts...)
	return &BookServiceGRPCAdapter{service: service, errorMapper: options.ErrorMapper(tego.GRPCError)}
}

func (a *BookServiceGRPCAdapter) mapError(err error) error {
	if err == nil {
		return nil
	}
	if a.errorMapper == nil {
		return tego.GRPCError(err)
	}
	return a.errorMapper(err)
}

func (s *bookServiceGRPCServer) GetBook(ctx context.Context, requestProto *bookspbv1.GetBookRequest) (*bookspbv1.GetBookResponse, error) {
	return s.AdaptGetBook(ctx, requestProto)
}

func (a *BookServiceGRPCAdapter) AdaptGetBook(ctx context.Context, requestProto *bookspbv1.GetBookRequest) (*bookspbv1.GetBookResponse, error) {
	request := GetBookRequestFromProto(requestProto)
	response, err := GetBookResponseFromInline(a.service.GetBook(GetBookRequestToInline(ctx, request)))
	if err != nil {
		return nil, a.mapError(err)
	}
	responseProto := GetBookResponseToProto(response)
	return responseProto, nil
}

func NewBookServiceGRPCClient(client bookspbv1.BookServiceClient, opts ...tego.GRPCClientOption) BookService {
	options := tego.NewGRPCClientOptions(opts...)
	return &bookServiceGRPCClient{client: client, errorMapper: options.ErrorMapper(nil)}
}

type bookServiceGRPCClient struct {
	client      bookspbv1.BookServiceClient
	errorMapper tego.ErrorMapper
}

func (c *bookServiceGRPCClient) mapError(err error) error {
	if err == nil {
		return nil
	}
	if c.errorMapper == nil {
		return err
	}
	return c.errorMapper(err)
}

func (c *bookServiceGRPCClient) GetBook(ctx context.Context, id string) (Book, error) {
	var zero GetBookResponse
	ctx, request := GetBookRequestFromInline(ctx, id)
	requestProto := GetBookRequestToProto(request)
	responseProto, err := c.client.GetBook(ctx, requestProto)
	if err != nil {
		return GetBookResponseToInline(zero, c.mapError(err))
	}
	response := GetBookResponseFromProto(responseProto)
	return GetBookResponseToInline(response, nil)
}

func NewBookServiceConnectHandler(service BookService, opts ...tego.ConnectHandlerOption) (string, http.Handler) {
	return NewBookServiceConnectHandlerWithAdapter(NewBookServiceConnectAdapter(service), opts...)
}

func NewBookServiceConnectHandlerWithAdapter(adapter *BookServiceConnectAdapter, opts ...tego.ConnectHandlerOption) (string, http.Handler) {
	options := tego.NewConnectHandlerOptions(opts...)
	adapter.errorMapper = options.ErrorMapper(adapter.errorMapper)
	return bookspbv1connect.NewBookServiceHandler(&bookServiceConnectHandler{BookServiceConnectAdapter: adapter}, options.ConnectHandlerOptions()...)
}

type bookServiceConnectHandler struct {
	*BookServiceConnectAdapter
}

type BookServiceConnectAdapter struct {
	service     BookService
	errorMapper tego.ErrorMapper
}

func NewBookServiceConnectAdapter(service BookService, opts ...tego.ConnectAdapterOption) *BookServiceConnectAdapter {
	options := tego.NewConnectAdapterOptions(opts...)
	return &BookServiceConnectAdapter{service: service, errorMapper: options.ErrorMapper(tego.ConnectError)}
}

func (a *BookServiceConnectAdapter) mapError(err error) error {
	if err == nil {
		return nil
	}
	if a.errorMapper == nil {
		return tego.ConnectError(err)
	}
	return a.errorMapper(err)
}

func (s *bookServiceConnectHandler) GetBook(ctx context.Context, requestProto *connect.Request[bookspbv1.GetBookRequest]) (*connect.Response[bookspbv1.GetBookResponse], error) {
	return s.AdaptGetBook(ctx, requestProto)
}

func (a *BookServiceConnectAdapter) AdaptGetBook(ctx context.Context, requestProto *connect.Request[bookspbv1.GetBookRequest]) (*connect.Response[bookspbv1.GetBookResponse], error) {
	request := GetBookRequestFromProto(requestProto.Msg)
	response, err := GetBookResponseFromInline(a.service.GetBook(GetBookRequestToInline(ctx, request)))
	if err != nil {
		return nil, a.mapError(err)
	}
	responseProto := GetBookResponseToProto(response)
	return connect.NewResponse(responseProto), nil
}

func NewBookServiceConnectClient(client bookspbv1connect.BookServiceClient, opts ...tego.ConnectClientOption) BookService {
	options := tego.NewConnectClientOptions(opts...)
	return &bookServiceConnectClient{client: client, errorMapper: options.ErrorMapper(nil)}
}

type bookServiceConnectClient struct {
	client      bookspbv1connect.BookServiceClient
	errorMapper tego.ErrorMapper
}

func (c *bookServiceConnectClient) mapError(err error) error {
	if err == nil {
		return nil
	}
	if c.errorMapper == nil {
		return err
	}
	return c.errorMapper(err)
}

func (c *bookServiceConnectClient) GetBook(ctx context.Context, id string) (Book, error) {
	var zero GetBookResponse
	ctx, request := GetBookRequestFromInline(ctx, id)
	requestProto := GetBookRequestToProto(request)
	responseProto, err := c.client.GetBook(ctx, connect.NewRequest(requestProto))
	if err != nil {
		return GetBookResponseToInline(zero, c.mapError(err))
	}
	response := GetBookResponseFromProto(responseProto.Msg)
	return GetBookResponseToInline(response, nil)
}

func GetBookRequestFromProto(source *bookspbv1.GetBookRequest) GetBookRequest {
	var target GetBookRequest
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	return target
}

func GetBookRequestToProto(source GetBookRequest) *bookspbv1.GetBookRequest {
	target := new(bookspbv1.GetBookRequest)
	target.SetId(source.ID)
	return target
}

func (gbr GetBookRequest) ToProto() *bookspbv1.GetBookRequest {
	return GetBookRequestToProto(gbr)
}

func GetBookResponseFromProto(source *bookspbv1.GetBookResponse) GetBookResponse {
	var target GetBookResponse
	if source == nil {
		return target
	}
	target.Book = BookFromProto(source.GetBook())
	return target
}

func GetBookResponseToProto(source GetBookResponse) *bookspbv1.GetBookResponse {
	target := new(bookspbv1.GetBookResponse)
	target.SetBook(BookToProto(source.Book))
	return target
}

func (gbr GetBookResponse) ToProto() *bookspbv1.GetBookResponse {
	return GetBookResponseToProto(gbr)
}

func BookFromProto(source *bookspbv1.Book) Book {
	var target Book
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	target.Title = source.GetTitle()
	target.Author = source.GetAuthor()
	return target
}

func BookToProto(source Book) *bookspbv1.Book {
	target := new(bookspbv1.Book)
	target.SetId(source.ID)
	target.SetTitle(source.Title)
	target.SetAuthor(source.Author)
	return target
}

func (b Book) ToProto() *bookspbv1.Book {
	return BookToProto(b)
}
