// Code generated by protoc-gen-tego. DO NOT EDIT.
package books

import (
	connect "connectrpc.com/connect"
	context "context"
	fmt "fmt"
	tego "github.com/seeruk/tego"
	bookspbv1 "github.com/seeruk/tego/examples/error-mapping/bookspbv1"
	bookspbv1connect "github.com/seeruk/tego/examples/error-mapping/bookspbv1/bookspbv1connect"
	grpc "google.golang.org/grpc"
	http "net/http"
)

type GetBookRequest struct {
	ID string
}

type GetBookResponse struct {
	Book Book
}

type Book struct {
	ID     string
	Title  string
	Author string
}

func GetBookRequestToInline(ctx context.Context, request GetBookRequest) (context.Context, string) {
	return ctx, request.ID
}

func GetBookRequestFromInline(ctx context.Context, id string) (context.Context, GetBookRequest) {
	return ctx, GetBookRequest{ID: id}
}

func GetBookResponseToInline(response GetBookResponse, err error) (Book, error) {
	if err != nil {
		var zeroBook Book
		return zeroBook, err
	}
	return response.Book, nil
}

func GetBookResponseFromInline(book Book, err error) (GetBookResponse, error) {
	if err != nil {
		var zero GetBookResponse
		return zero, err
	}
	return GetBookResponse{Book: book}, nil
}

type BookService interface {
	GetBook(ctx context.Context, id string) (Book, error)
}

type UnimplementedBookService struct{}

func (UnimplementedBookService) GetBook(ctx context.Context, id string) (Book, error) {
	var zeroBook Book
	return zeroBook, unimplementedBookServiceError("GetBook")
}

func unimplementedBookServiceError(method string) error {
	return fmt.Errorf("BookService.%s: %w", method, tego.ErrUnimplemented)
}

type BookServiceHooks struct {
	BeforeGetBookRequestMapping  []BookServiceBeforeGetBookRequestMappingHook
	AfterGetBookRequestMapping   []BookServiceAfterGetBookRequestMappingHook
	BeforeGetBookResponseMapping []BookServiceBeforeGetBookResponseMappingHook
	AfterGetBookResponseMapping  []BookServiceAfterGetBookResponseMappingHook
}

type BookServiceBeforeGetBookRequestMappingHook func(context.Context, tego.RPCInfo, *bookspbv1.GetBookRequest) (context.Context, *bookspbv1.GetBookRequest, error)

type BookServiceAfterGetBookRequestMappingHook func(context.Context, tego.RPCInfo, GetBookRequest) (context.Context, GetBookRequest, error)

type BookServiceBeforeGetBookResponseMappingHook func(context.Context, tego.RPCInfo, GetBookResponse) (GetBookResponse, error)

type BookServiceAfterGetBookResponseMappingHook func(context.Context, tego.RPCInfo, *bookspbv1.GetBookResponse) (*bookspbv1.GetBookResponse, error)

func (h *BookServiceHooks) AddBeforeGetBookRequestMappingHook(hooks ...BookServiceBeforeGetBookRequestMappingHook) *BookServiceHooks {
	h.BeforeGetBookRequestMapping = append(h.BeforeGetBookRequestMapping, hooks...)
	return h
}

func (h *BookServiceHooks) SetBeforeGetBookRequestMappingHooks(hooks ...BookServiceBeforeGetBookRequestMappingHook) *BookServiceHooks {
	h.BeforeGetBookRequestMapping = hooks
	return h
}

func (h *BookServiceHooks) AddAfterGetBookRequestMappingHook(hooks ...BookServiceAfterGetBookRequestMappingHook) *BookServiceHooks {
	h.AfterGetBookRequestMapping = append(h.AfterGetBookRequestMapping, hooks...)
	return h
}

func (h *BookServiceHooks) SetAfterGetBookRequestMappingHooks(hooks ...BookServiceAfterGetBookRequestMappingHook) *BookServiceHooks {
	h.AfterGetBookRequestMapping = hooks
	return h
}

func (h *BookServiceHooks) AddBeforeGetBookResponseMappingHook(hooks ...BookServiceBeforeGetBookResponseMappingHook) *BookServiceHooks {
	h.BeforeGetBookResponseMapping = append(h.BeforeGetBookResponseMapping, hooks...)
	return h
}

func (h *BookServiceHooks) SetBeforeGetBookResponseMappingHooks(hooks ...BookServiceBeforeGetBookResponseMappingHook) *BookServiceHooks {
	h.BeforeGetBookResponseMapping = hooks
	return h
}

func (h *BookServiceHooks) AddAfterGetBookResponseMappingHook(hooks ...BookServiceAfterGetBookResponseMappingHook) *BookServiceHooks {
	h.AfterGetBookResponseMapping = append(h.AfterGetBookResponseMapping, hooks...)
	return h
}

func (h *BookServiceHooks) SetAfterGetBookResponseMappingHooks(hooks ...BookServiceAfterGetBookResponseMappingHook) *BookServiceHooks {
	h.AfterGetBookResponseMapping = hooks
	return h
}

func mergeBookServiceHooks(hooks ...BookServiceHooks) BookServiceHooks {
	var merged BookServiceHooks
	for _, hooks := range hooks {
		merged.BeforeGetBookRequestMapping = append(merged.BeforeGetBookRequestMapping, hooks.BeforeGetBookRequestMapping...)
		merged.AfterGetBookRequestMapping = append(merged.AfterGetBookRequestMapping, hooks.AfterGetBookRequestMapping...)
		merged.BeforeGetBookResponseMapping = append(merged.BeforeGetBookResponseMapping, hooks.BeforeGetBookResponseMapping...)
		merged.AfterGetBookResponseMapping = append(merged.AfterGetBookResponseMapping, hooks.AfterGetBookResponseMapping...)
	}
	return merged
}

func RegisterBookServiceGRPCServer(registrar grpc.ServiceRegistrar, service BookService, opts ...tego.GRPCServerOption) {
	bookspbv1.RegisterBookServiceServer(registrar, NewBookServiceGRPCServer(service, opts...))
}

func RegisterBookServiceGRPCServerWithAdapter(registrar grpc.ServiceRegistrar, adapter *BookServiceGRPCAdapter, opts ...tego.GRPCServerOption) {
	bookspbv1.RegisterBookServiceServer(registrar, NewBookServiceGRPCServerWithAdapter(adapter, opts...))
}

func NewBookServiceGRPCServer(service BookService, opts ...tego.GRPCServerOption) bookspbv1.BookServiceServer {
	return NewBookServiceGRPCServerWithAdapter(NewBookServiceGRPCAdapter(service), opts...)
}

func NewBookServiceGRPCServerWithAdapter(adapter *BookServiceGRPCAdapter, opts ...tego.GRPCServerOption) bookspbv1.BookServiceServer {
	options := tego.NewGRPCServerOptions(opts...)
	adapter.errorMapper = options.ErrorMapper(adapter.errorMapper)
	return &bookServiceGRPCServer{BookServiceGRPCAdapter: adapter}
}

type bookServiceGRPCServer struct {
	bookspbv1.UnimplementedBookServiceServer
	*BookServiceGRPCAdapter
}

type BookServiceGRPCAdapter struct {
	service        BookService
	errorMapper    tego.ErrorMapper
	serviceHooks   BookServiceHooks
	interfaceHooks tego.InterfaceHooks
}

func NewBookServiceGRPCAdapter(service BookService, opts ...tego.GRPCAdapterOption) *BookServiceGRPCAdapter {
	options := tego.NewGRPCAdapterOptions(opts...)
	return &BookServiceGRPCAdapter{service: service, errorMapper: options.ErrorMapper(tego.GRPCError)}
}

func (a *BookServiceGRPCAdapter) mapError(err error) error {
	if err == nil {
		return nil
	}
	if a.errorMapper == nil {
		return tego.GRPCError(err)
	}
	return a.errorMapper(err)
}

func (a *BookServiceGRPCAdapter) AddServiceHooks(hooks BookServiceHooks) *BookServiceGRPCAdapter {
	a.serviceHooks = mergeBookServiceHooks(a.serviceHooks, hooks)
	return a
}

func (a *BookServiceGRPCAdapter) SetServiceHooks(hooks BookServiceHooks) *BookServiceGRPCAdapter {
	a.serviceHooks = mergeBookServiceHooks(hooks)
	return a
}

func (a *BookServiceGRPCAdapter) AddInterfaceHooks(hooks tego.InterfaceHooks) *BookServiceGRPCAdapter {
	a.interfaceHooks = tego.MergeInterfaceHooks(a.interfaceHooks, hooks)
	return a
}

func (a *BookServiceGRPCAdapter) SetInterfaceHooks(hooks tego.InterfaceHooks) *BookServiceGRPCAdapter {
	a.interfaceHooks = tego.MergeInterfaceHooks(hooks)
	return a
}

func (a *BookServiceGRPCAdapter) runBeforeGetBookRequestMapping(ctx context.Context, info tego.RPCInfo, value *bookspbv1.GetBookRequest) (context.Context, *bookspbv1.GetBookRequest, error) {
	for _, hook := range a.serviceHooks.BeforeGetBookRequestMapping {
		var err error
		ctx, value, err = hook(ctx, info, value)
		if err != nil {
			return ctx, value, err
		}
	}
	var err error
	ctx, err = tego.RunBeforeRequestMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.BeforeRequestMapping)
	if err != nil {
		return ctx, value, err
	}
	return ctx, value, nil
}

func (a *BookServiceGRPCAdapter) runAfterGetBookRequestMapping(ctx context.Context, info tego.RPCInfo, value GetBookRequest) (context.Context, GetBookRequest, error) {
	for _, hook := range a.serviceHooks.AfterGetBookRequestMapping {
		var err error
		ctx, value, err = hook(ctx, info, value)
		if err != nil {
			return ctx, value, err
		}
	}
	var err error
	ctx, err = tego.RunAfterRequestMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.AfterRequestMapping)
	if err != nil {
		return ctx, value, err
	}
	return ctx, value, nil
}

func (a *BookServiceGRPCAdapter) runBeforeGetBookResponseMapping(ctx context.Context, info tego.RPCInfo, value GetBookResponse) (GetBookResponse, error) {
	for _, hook := range a.serviceHooks.BeforeGetBookResponseMapping {
		var err error
		value, err = hook(ctx, info, value)
		if err != nil {
			return value, err
		}
	}
	if err := tego.RunBeforeResponseMappingInterfaceHooks(ctx, info, &value, a.interfaceHooks.BeforeResponseMapping); err != nil {
		return value, err
	}
	return value, nil
}

func (a *BookServiceGRPCAdapter) runAfterGetBookResponseMapping(ctx context.Context, info tego.RPCInfo, value *bookspbv1.GetBookResponse) (*bookspbv1.GetBookResponse, error) {
	for _, hook := range a.serviceHooks.AfterGetBookResponseMapping {
		var err error
		value, err = hook(ctx, info, value)
		if err != nil {
			return value, err
		}
	}
	if err := tego.RunAfterResponseMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.AfterResponseMapping); err != nil {
		return value, err
	}
	return value, nil
}

func (s *bookServiceGRPCServer) GetBook(ctx context.Context, requestProto *bookspbv1.GetBookRequest) (*bookspbv1.GetBookResponse, error) {
	return s.AdaptGetBook(ctx, requestProto)
}

func (a *BookServiceGRPCAdapter) AdaptGetBook(ctx context.Context, requestProto *bookspbv1.GetBookRequest) (*bookspbv1.GetBookResponse, error) {
	info := tego.RPCInfo{Service: "books.v1.BookService", Method: "GetBook", Procedure: "/books.v1.BookService/GetBook"}
	ctx, requestProto, err := a.runBeforeGetBookRequestMapping(ctx, info, requestProto)
	if err != nil {
		return nil, a.mapError(err)
	}
	request := GetBookRequestFromProto(requestProto)
	ctx, request, err = a.runAfterGetBookRequestMapping(ctx, info, request)
	if err != nil {
		return nil, a.mapError(err)
	}
	response, err := GetBookResponseFromInline(a.service.GetBook(GetBookRequestToInline(ctx, request)))
	if err != nil {
		return nil, a.mapError(err)
	}
	response, err = a.runBeforeGetBookResponseMapping(ctx, info, response)
	if err != nil {
		return nil, a.mapError(err)
	}
	responseProto := GetBookResponseToProto(response)
	responseProto, err = a.runAfterGetBookResponseMapping(ctx, info, responseProto)
	if err != nil {
		return nil, a.mapError(err)
	}
	return responseProto, nil
}

func NewBookServiceGRPCClient(client bookspbv1.BookServiceClient, opts ...tego.GRPCClientOption) BookService {
	options := tego.NewGRPCClientOptions(opts...)
	return &bookServiceGRPCClient{client: client, errorMapper: options.ErrorMapper(nil)}
}

type bookServiceGRPCClient struct {
	client      bookspbv1.BookServiceClient
	errorMapper tego.ErrorMapper
}

func (c *bookServiceGRPCClient) mapError(err error) error {
	if err == nil {
		return nil
	}
	if c.errorMapper == nil {
		return err
	}
	return c.errorMapper(err)
}

func (c *bookServiceGRPCClient) GetBook(ctx context.Context, id string) (Book, error) {
	var zero GetBookResponse
	ctx, request := GetBookRequestFromInline(ctx, id)
	requestProto := GetBookRequestToProto(request)
	responseProto, err := c.client.GetBook(ctx, requestProto)
	if err != nil {
		return GetBookResponseToInline(zero, c.mapError(err))
	}
	response := GetBookResponseFromProto(responseProto)
	return GetBookResponseToInline(response, nil)
}

func NewBookServiceConnectHandler(service BookService, opts ...tego.ConnectHandlerOption) (string, http.Handler) {
	return NewBookServiceConnectHandlerWithAdapter(NewBookServiceConnectAdapter(service), opts...)
}

func NewBookServiceConnectHandlerWithAdapter(adapter *BookServiceConnectAdapter, opts ...tego.ConnectHandlerOption) (string, http.Handler) {
	options := tego.NewConnectHandlerOptions(opts...)
	adapter.errorMapper = options.ErrorMapper(adapter.errorMapper)
	return bookspbv1connect.NewBookServiceHandler(&bookServiceConnectHandler{BookServiceConnectAdapter: adapter}, options.ConnectHandlerOptions()...)
}

type bookServiceConnectHandler struct {
	*BookServiceConnectAdapter
}

type BookServiceConnectAdapter struct {
	service        BookService
	errorMapper    tego.ErrorMapper
	serviceHooks   BookServiceHooks
	interfaceHooks tego.InterfaceHooks
}

func NewBookServiceConnectAdapter(service BookService, opts ...tego.ConnectAdapterOption) *BookServiceConnectAdapter {
	options := tego.NewConnectAdapterOptions(opts...)
	return &BookServiceConnectAdapter{service: service, errorMapper: options.ErrorMapper(tego.ConnectError)}
}

func (a *BookServiceConnectAdapter) mapError(err error) error {
	if err == nil {
		return nil
	}
	if a.errorMapper == nil {
		return tego.ConnectError(err)
	}
	return a.errorMapper(err)
}

func (a *BookServiceConnectAdapter) AddServiceHooks(hooks BookServiceHooks) *BookServiceConnectAdapter {
	a.serviceHooks = mergeBookServiceHooks(a.serviceHooks, hooks)
	return a
}

func (a *BookServiceConnectAdapter) SetServiceHooks(hooks BookServiceHooks) *BookServiceConnectAdapter {
	a.serviceHooks = mergeBookServiceHooks(hooks)
	return a
}

func (a *BookServiceConnectAdapter) AddInterfaceHooks(hooks tego.InterfaceHooks) *BookServiceConnectAdapter {
	a.interfaceHooks = tego.MergeInterfaceHooks(a.interfaceHooks, hooks)
	return a
}

func (a *BookServiceConnectAdapter) SetInterfaceHooks(hooks tego.InterfaceHooks) *BookServiceConnectAdapter {
	a.interfaceHooks = tego.MergeInterfaceHooks(hooks)
	return a
}

func (a *BookServiceConnectAdapter) runBeforeGetBookRequestMapping(ctx context.Context, info tego.RPCInfo, value *bookspbv1.GetBookRequest) (context.Context, *bookspbv1.GetBookRequest, error) {
	for _, hook := range a.serviceHooks.BeforeGetBookRequestMapping {
		var err error
		ctx, value, err = hook(ctx, info, value)
		if err != nil {
			return ctx, value, err
		}
	}
	var err error
	ctx, err = tego.RunBeforeRequestMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.BeforeRequestMapping)
	if err != nil {
		return ctx, value, err
	}
	return ctx, value, nil
}

func (a *BookServiceConnectAdapter) runAfterGetBookRequestMapping(ctx context.Context, info tego.RPCInfo, value GetBookRequest) (context.Context, GetBookRequest, error) {
	for _, hook := range a.serviceHooks.AfterGetBookRequestMapping {
		var err error
		ctx, value, err = hook(ctx, info, value)
		if err != nil {
			return ctx, value, err
		}
	}
	var err error
	ctx, err = tego.RunAfterRequestMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.AfterRequestMapping)
	if err != nil {
		return ctx, value, err
	}
	return ctx, value, nil
}

func (a *BookServiceConnectAdapter) runBeforeGetBookResponseMapping(ctx context.Context, info tego.RPCInfo, value GetBookResponse) (GetBookResponse, error) {
	for _, hook := range a.serviceHooks.BeforeGetBookResponseMapping {
		var err error
		value, err = hook(ctx, info, value)
		if err != nil {
			return value, err
		}
	}
	if err := tego.RunBeforeResponseMappingInterfaceHooks(ctx, info, &value, a.interfaceHooks.BeforeResponseMapping); err != nil {
		return value, err
	}
	return value, nil
}

func (a *BookServiceConnectAdapter) runAfterGetBookResponseMapping(ctx context.Context, info tego.RPCInfo, value *bookspbv1.GetBookResponse) (*bookspbv1.GetBookResponse, error) {
	for _, hook := range a.serviceHooks.AfterGetBookResponseMapping {
		var err error
		value, err = hook(ctx, info, value)
		if err != nil {
			return value, err
		}
	}
	if err := tego.RunAfterResponseMappingInterfaceHooks(ctx, info, value, a.interfaceHooks.AfterResponseMapping); err != nil {
		return value, err
	}
	return value, nil
}

func (s *bookServiceConnectHandler) GetBook(ctx context.Context, requestProto *connect.Request[bookspbv1.GetBookRequest]) (*connect.Response[bookspbv1.GetBookResponse], error) {
	return s.AdaptGetBook(ctx, requestProto)
}

func (a *BookServiceConnectAdapter) AdaptGetBook(ctx context.Context, requestProto *connect.Request[bookspbv1.GetBookRequest]) (*connect.Response[bookspbv1.GetBookResponse], error) {
	info := tego.RPCInfo{Service: "books.v1.BookService", Method: "GetBook", Procedure: "/books.v1.BookService/GetBook"}
	requestProtoMsg := requestProto.Msg
	ctx, requestProtoMsg, err := a.runBeforeGetBookRequestMapping(ctx, info, requestProtoMsg)
	if err != nil {
		return nil, a.mapError(err)
	}
	request := GetBookRequestFromProto(requestProtoMsg)
	ctx, request, err = a.runAfterGetBookRequestMapping(ctx, info, request)
	if err != nil {
		return nil, a.mapError(err)
	}
	response, err := GetBookResponseFromInline(a.service.GetBook(GetBookRequestToInline(ctx, request)))
	if err != nil {
		return nil, a.mapError(err)
	}
	response, err = a.runBeforeGetBookResponseMapping(ctx, info, response)
	if err != nil {
		return nil, a.mapError(err)
	}
	responseProto := GetBookResponseToProto(response)
	responseProto, err = a.runAfterGetBookResponseMapping(ctx, info, responseProto)
	if err != nil {
		return nil, a.mapError(err)
	}
	return connect.NewResponse(responseProto), nil
}

func NewBookServiceConnectClient(client bookspbv1connect.BookServiceClient, opts ...tego.ConnectClientOption) BookService {
	options := tego.NewConnectClientOptions(opts...)
	return &bookServiceConnectClient{client: client, errorMapper: options.ErrorMapper(nil)}
}

type bookServiceConnectClient struct {
	client      bookspbv1connect.BookServiceClient
	errorMapper tego.ErrorMapper
}

func (c *bookServiceConnectClient) mapError(err error) error {
	if err == nil {
		return nil
	}
	if c.errorMapper == nil {
		return err
	}
	return c.errorMapper(err)
}

func (c *bookServiceConnectClient) GetBook(ctx context.Context, id string) (Book, error) {
	var zero GetBookResponse
	ctx, request := GetBookRequestFromInline(ctx, id)
	requestProto := GetBookRequestToProto(request)
	responseProto, err := c.client.GetBook(ctx, connect.NewRequest(requestProto))
	if err != nil {
		return GetBookResponseToInline(zero, c.mapError(err))
	}
	response := GetBookResponseFromProto(responseProto.Msg)
	return GetBookResponseToInline(response, nil)
}

func GetBookRequestFromProto(source *bookspbv1.GetBookRequest) GetBookRequest {
	var target GetBookRequest
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	return target
}

func GetBookRequestToProto(source GetBookRequest) *bookspbv1.GetBookRequest {
	target := bookspbv1.GetBookRequest_builder{
		Id: &source.ID,
	}.Build()
	return target
}

func (gbr GetBookRequest) ToProto() *bookspbv1.GetBookRequest {
	return GetBookRequestToProto(gbr)
}

func GetBookResponseFromProto(source *bookspbv1.GetBookResponse) GetBookResponse {
	var target GetBookResponse
	if source == nil {
		return target
	}
	target.Book = BookFromProto(source.GetBook())
	return target
}

func GetBookResponseToProto(source GetBookResponse) *bookspbv1.GetBookResponse {
	target := bookspbv1.GetBookResponse_builder{
		Book: BookToProto(source.Book),
	}.Build()
	return target
}

func (gbr GetBookResponse) ToProto() *bookspbv1.GetBookResponse {
	return GetBookResponseToProto(gbr)
}

func BookFromProto(source *bookspbv1.Book) Book {
	var target Book
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	target.Title = source.GetTitle()
	target.Author = source.GetAuthor()
	return target
}

func BookToProto(source Book) *bookspbv1.Book {
	target := bookspbv1.Book_builder{
		Id:     &source.ID,
		Title:  &source.Title,
		Author: &source.Author,
	}.Build()
	return target
}

func (b Book) ToProto() *bookspbv1.Book {
	return BookToProto(b)
}
