// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yirapb/v1/yira.proto

package yirapbv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketStatus int32

const (
	TicketStatus_TICKET_STATUS_UNSPECIFIED TicketStatus = 0
	TicketStatus_TICKET_STATUS_OPEN        TicketStatus = 1
	TicketStatus_TICKET_STATUS_IN_PROGRESS TicketStatus = 2
	TicketStatus_TICKET_STATUS_CLOSED      TicketStatus = 3
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "TICKET_STATUS_UNSPECIFIED",
		1: "TICKET_STATUS_OPEN",
		2: "TICKET_STATUS_IN_PROGRESS",
		3: "TICKET_STATUS_CLOSED",
	}
	TicketStatus_value = map[string]int32{
		"TICKET_STATUS_UNSPECIFIED": 0,
		"TICKET_STATUS_OPEN":        1,
		"TICKET_STATUS_IN_PROGRESS": 2,
		"TICKET_STATUS_CLOSED":      3,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yirapb_v1_yira_proto_enumTypes[0].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_yirapb_v1_yira_proto_enumTypes[0]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Ticket struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Status      TicketStatus           `protobuf:"varint,3,opt,name=status,enum=yirapb.v1.TicketStatus"`
	xxx_hidden_Assignee    *NullablePerson        `protobuf:"bytes,4,opt,name=assignee"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_yirapb_v1_yira_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_yirapb_v1_yira_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Ticket) GetStatus() TicketStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Status
		}
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) GetAssignee() *NullablePerson {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return nil
}

func (x *Ticket) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Ticket) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Ticket) SetStatus(v TicketStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Ticket) SetAssignee(v *NullablePerson) {
	x.xxx_hidden_Assignee = v
}

func (x *Ticket) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Ticket) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Ticket) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Ticket) HasAssignee() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Assignee != nil
}

func (x *Ticket) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *Ticket) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *Ticket) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Status = TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) ClearAssignee() {
	x.xxx_hidden_Assignee = nil
}

type Ticket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Description *string
	Status      *TicketStatus
	Assignee    *NullablePerson
}

func (b0 Ticket_builder) Build() *Ticket {
	m0 := &Ticket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Description = b.Description
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Assignee = b.Assignee
	return m0
}

type Person struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FirstName   *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName"`
	xxx_hidden_LastName    *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_yirapb_v1_yira_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_yirapb_v1_yira_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Person) GetFirstName() string {
	if x != nil {
		if x.xxx_hidden_FirstName != nil {
			return *x.xxx_hidden_FirstName
		}
		return ""
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		if x.xxx_hidden_LastName != nil {
			return *x.xxx_hidden_LastName
		}
		return ""
	}
	return ""
}

func (x *Person) SetFirstName(v string) {
	x.xxx_hidden_FirstName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Person) SetLastName(v string) {
	x.xxx_hidden_LastName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Person) HasFirstName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Person) HasLastName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Person) ClearFirstName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FirstName = nil
}

func (x *Person) ClearLastName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_LastName = nil
}

type Person_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FirstName *string
	LastName  *string
}

func (b0 Person_builder) Build() *Person {
	m0 := &Person{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FirstName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FirstName = b.FirstName
	}
	if b.LastName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_LastName = b.LastName
	}
	return m0
}

type NullablePerson struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isNullablePerson_Value `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NullablePerson) Reset() {
	*x = NullablePerson{}
	mi := &file_yirapb_v1_yira_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullablePerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullablePerson) ProtoMessage() {}

func (x *NullablePerson) ProtoReflect() protoreflect.Message {
	mi := &file_yirapb_v1_yira_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullablePerson) GetPerson() *Person {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullablePerson_Person); ok {
			return x.Person
		}
	}
	return nil
}

func (x *NullablePerson) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullablePerson_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *NullablePerson) SetPerson(v *Person) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &nullablePerson_Person{v}
}

func (x *NullablePerson) SetNull(v structpb.NullValue) {
	x.xxx_hidden_Value = &nullablePerson_Null{v}
}

func (x *NullablePerson) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *NullablePerson) HasPerson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullablePerson_Person)
	return ok
}

func (x *NullablePerson) HasNull() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullablePerson_Null)
	return ok
}

func (x *NullablePerson) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *NullablePerson) ClearPerson() {
	if _, ok := x.xxx_hidden_Value.(*nullablePerson_Person); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *NullablePerson) ClearNull() {
	if _, ok := x.xxx_hidden_Value.(*nullablePerson_Null); ok {
		x.xxx_hidden_Value = nil
	}
}

const NullablePerson_Value_not_set_case case_NullablePerson_Value = 0
const NullablePerson_Person_case case_NullablePerson_Value = 1
const NullablePerson_Null_case case_NullablePerson_Value = 2

func (x *NullablePerson) WhichValue() case_NullablePerson_Value {
	if x == nil {
		return NullablePerson_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *nullablePerson_Person:
		return NullablePerson_Person_case
	case *nullablePerson_Null:
		return NullablePerson_Null_case
	default:
		return NullablePerson_Value_not_set_case
	}
}

type NullablePerson_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	Person *Person
	Null   *structpb.NullValue
	// -- end of xxx_hidden_Value
}

func (b0 NullablePerson_builder) Build() *NullablePerson {
	m0 := &NullablePerson{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Person != nil {
		x.xxx_hidden_Value = &nullablePerson_Person{b.Person}
	}
	if b.Null != nil {
		x.xxx_hidden_Value = &nullablePerson_Null{*b.Null}
	}
	return m0
}

type case_NullablePerson_Value protoreflect.FieldNumber

func (x case_NullablePerson_Value) String() string {
	md := file_yirapb_v1_yira_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNullablePerson_Value interface {
	isNullablePerson_Value()
}

type nullablePerson_Person struct {
	Person *Person `protobuf:"bytes,1,opt,name=person,oneof"`
}

type nullablePerson_Null struct {
	Null structpb.NullValue `protobuf:"varint,2,opt,name=null,enum=google.protobuf.NullValue,oneof"`
}

func (*nullablePerson_Person) isNullablePerson_Value() {}

func (*nullablePerson_Null) isNullablePerson_Value() {}

var File_yirapb_v1_yira_proto protoreflect.FileDescriptor

const file_yirapb_v1_yira_proto_rawDesc = "" +
	"\n" +
	"\x14yirapb/v1/yira.proto\x12\tyirapb.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc0\x01\n" +
	"\x06Ticket\x12\x1c\n" +
	"\x05title\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12(\n" +
	"\vdescription\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.yirapb.v1.TicketStatusB\x06\xbaH\x03\xc8\x01\x01R\x06status\x125\n" +
	"\bassignee\x18\x04 \x01(\v2\x19.yirapb.v1.NullablePersonR\bassignee\"D\n" +
	"\x06Person\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\"x\n" +
	"\x0eNullablePerson\x12+\n" +
	"\x06person\x18\x01 \x01(\v2\x11.yirapb.v1.PersonH\x00R\x06person\x120\n" +
	"\x04null\x18\x02 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04nullB\a\n" +
	"\x05value*~\n" +
	"\fTicketStatus\x12\x1d\n" +
	"\x19TICKET_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TICKET_STATUS_OPEN\x10\x01\x12\x1d\n" +
	"\x19TICKET_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14TICKET_STATUS_CLOSED\x10\x03B4Z2github.com/seeruk/tego/lab/proto/yirapbv1;yirapbv1b\beditionsp\xe9\a"

var file_yirapb_v1_yira_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yirapb_v1_yira_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yirapb_v1_yira_proto_goTypes = []any{
	(TicketStatus)(0),       // 0: yirapb.v1.TicketStatus
	(*Ticket)(nil),          // 1: yirapb.v1.Ticket
	(*Person)(nil),          // 2: yirapb.v1.Person
	(*NullablePerson)(nil),  // 3: yirapb.v1.NullablePerson
	(structpb.NullValue)(0), // 4: google.protobuf.NullValue
}
var file_yirapb_v1_yira_proto_depIdxs = []int32{
	0, // 0: yirapb.v1.Ticket.status:type_name -> yirapb.v1.TicketStatus
	3, // 1: yirapb.v1.Ticket.assignee:type_name -> yirapb.v1.NullablePerson
	2, // 2: yirapb.v1.NullablePerson.person:type_name -> yirapb.v1.Person
	4, // 3: yirapb.v1.NullablePerson.null:type_name -> google.protobuf.NullValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_yirapb_v1_yira_proto_init() }
func file_yirapb_v1_yira_proto_init() {
	if File_yirapb_v1_yira_proto != nil {
		return
	}
	file_yirapb_v1_yira_proto_msgTypes[2].OneofWrappers = []any{
		(*nullablePerson_Person)(nil),
		(*nullablePerson_Null)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yirapb_v1_yira_proto_rawDesc), len(file_yirapb_v1_yira_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yirapb_v1_yira_proto_goTypes,
		DependencyIndexes: file_yirapb_v1_yira_proto_depIdxs,
		EnumInfos:         file_yirapb_v1_yira_proto_enumTypes,
		MessageInfos:      file_yirapb_v1_yira_proto_msgTypes,
	}.Build()
	File_yirapb_v1_yira_proto = out.File
	file_yirapb_v1_yira_proto_goTypes = nil
	file_yirapb_v1_yira_proto_depIdxs = nil
}
