// Code generated by protoc-gen-tego. DO NOT EDIT.
package yira

import (
	errors "errors"
	plannertest "github.com/seeruk/tego/internal/tego/testdata/plannertest"
	yirapbv1 "github.com/seeruk/tego/lab/yirapbv1"
	omittable "github.com/seeruk/tego/omittable"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// TicketStatus is the current lifecycle state of a ticket.
type TicketStatus uint

const (
	TicketStatusUnspecified TicketStatus = 0
	// TicketStatusOpen means work can begin.
	TicketStatusOpen       TicketStatus = 1
	TicketStatusInProgress TicketStatus = 2
	TicketStatusClosed     TicketStatus = 3
)

type TicketVisibility uint

const (
	TicketVisibilityUnspecified TicketVisibility = 0
	TicketVisibilityPublic      TicketVisibility = 1
	TicketVisibilityPrivate     TicketVisibility = 2
)

type TicketReviewer interface {
	isTicketReviewer()
}

type TicketInternal struct {
	Internal Person
}

func (TicketInternal) isTicketReviewer() {}

type Ticket struct {
	ID                 string `json:"id,omitempty"`
	Title              string `json:"title,omitempty"`
	Description        *plannertest.Description
	Status             TicketStatus
	Assignee           *Person
	Author             Person
	Version            string
	Metadata           map[string]string
	WatchersByRole     map[string]Person
	WorkflowStatuses   map[string]TicketStatus
	WatcherIDs         []string
	Labels             plannertest.Set[plannertest.CustomString]
	Visibility         TicketVisibility
	AuditEvents        []TicketAuditEvent
	History            TicketHistory
	LatestHistoryEntry TicketHistoryEntry
	Reviewer           TicketReviewer
	StructData         map[string]any
}

type TicketAuditEvent struct {
	Actor  string
	Status TicketStatus
}

type TicketHistory struct {
	Entries []TicketHistoryEntry
}

type TicketHistoryEntry struct {
	Note       string
	Visibility TicketVisibility
}

type UpdateTicketRequest struct {
	ID    string
	Input TicketInput
}

type TicketInput struct {
	Title       omittable.Of[string]
	Description omittable.Of[string]
	Status      omittable.Of[TicketStatus]
	Assignee    omittable.Of[*Person]
	Version     string
}

type Person struct {
	FirstName string
	LastName  string
}

func TicketFromProto(source *yirapbv1.Ticket) (Ticket, error) {
	var target Ticket
	if source == nil {
		return target, nil
	}
	target.ID = source.GetId()
	target.Title = source.GetTitle()
	mapped1, err := plannertest.DescriptionFromProto(source.GetDescription())
	if err != nil {
		return target, err
	}
	target.Description = mapped1
	target.Status = TicketStatus(source.GetStatus())
	var nullable2 *Person
	if source.GetAssignee() != nil && source.GetAssignee().WhichValue() == yirapbv1.NullablePerson_Person_case {
		nullable2 = new(PersonFromProto(source.GetAssignee().GetPerson()))
	}
	target.Assignee = nullable2
	target.Author = PersonFromProto(source.GetAuthor())
	target.Version = source.GetVersion()
	items3 := make(map[string]string, len(source.GetMetadata()))
	for key4, value5 := range source.GetMetadata() {
		items3[key4] = value5
	}
	target.Metadata = items3
	items6 := make(map[string]Person, len(source.GetWatchersByRole()))
	for key7, value8 := range source.GetWatchersByRole() {
		items6[key7] = PersonFromProto(value8)
	}
	target.WatchersByRole = items6
	items9 := make(map[string]TicketStatus, len(source.GetWorkflowStatuses()))
	for key10, value11 := range source.GetWorkflowStatuses() {
		items9[key10] = TicketStatus(value11)
	}
	target.WorkflowStatuses = items9
	items12 := make([]string, 0, len(source.GetWatcherIds()))
	for _, item13 := range source.GetWatcherIds() {
		items12 = append(items12, item13)
	}
	target.WatcherIDs = items12
	mapped14, err := plannertest.CustomStringSetFromProto(source.GetLabels())
	if err != nil {
		return target, err
	}
	target.Labels = mapped14
	target.Visibility = TicketVisibility(source.GetVisibility())
	items15 := make([]TicketAuditEvent, 0, len(source.GetAuditEvents()))
	for _, item16 := range source.GetAuditEvents() {
		items15 = append(items15, TicketAuditEventFromProto(item16))
	}
	target.AuditEvents = items15
	target.History = TicketHistoryFromProto(source.GetHistory())
	target.LatestHistoryEntry = TicketHistoryEntryFromProto(source.GetLatestHistoryEntry())
	switch source.WhichReviewer() {
	case yirapbv1.Ticket_Internal_case:
		target.Reviewer = TicketInternal{Internal: PersonFromProto(source.GetInternal())}
	}
	var structMap17 map[string]any
	if source.GetStructData() != nil {
		structMap17 = source.GetStructData().AsMap()
	}
	target.StructData = structMap17
	return target, nil
}

func TicketToProto(source Ticket) (*yirapbv1.Ticket, error) {
	target := new(yirapbv1.Ticket)
	target.SetId(source.ID)
	target.SetTitle(source.Title)
	mapped1, err := plannertest.DescriptionToProto(source.Description)
	if err != nil {
		return nil, err
	}
	target.SetDescription(mapped1)
	target.SetStatus(yirapbv1.TicketStatus(source.Status))
	var nullable2 *yirapbv1.NullablePerson
	if source.Assignee != nil {
		nullable2 = new(yirapbv1.NullablePerson)
		nullable2.SetPerson(PersonToProto(*source.Assignee))
	} else {
		nullable2 = new(yirapbv1.NullablePerson)
		nullable2.SetNull(structpb.NullValue_NULL_VALUE)
	}
	target.SetAssignee(nullable2)
	target.SetAuthor(PersonToProto(source.Author))
	target.SetVersion(source.Version)
	items3 := make(map[string]string, len(source.Metadata))
	for key4, value5 := range source.Metadata {
		items3[key4] = value5
	}
	target.SetMetadata(items3)
	items6 := make(map[string]*yirapbv1.Person, len(source.WatchersByRole))
	for key7, value8 := range source.WatchersByRole {
		items6[key7] = PersonToProto(value8)
	}
	target.SetWatchersByRole(items6)
	items9 := make(map[string]yirapbv1.TicketStatus, len(source.WorkflowStatuses))
	for key10, value11 := range source.WorkflowStatuses {
		items9[key10] = yirapbv1.TicketStatus(value11)
	}
	target.SetWorkflowStatuses(items9)
	items12 := make([]string, 0, len(source.WatcherIDs))
	for _, item13 := range source.WatcherIDs {
		items12 = append(items12, item13)
	}
	target.SetWatcherIds(items12)
	mapped14, err := plannertest.CustomStringSetToProto(source.Labels)
	if err != nil {
		return nil, err
	}
	target.SetLabels(mapped14)
	target.SetVisibility(yirapbv1.Ticket_Visibility(source.Visibility))
	items15 := make([]*yirapbv1.Ticket_AuditEvent, 0, len(source.AuditEvents))
	for _, item16 := range source.AuditEvents {
		items15 = append(items15, TicketAuditEventToProto(item16))
	}
	target.SetAuditEvents(items15)
	target.SetHistory(TicketHistoryToProto(source.History))
	target.SetLatestHistoryEntry(TicketHistoryEntryToProto(source.LatestHistoryEntry))
	switch value17 := source.Reviewer.(type) {
	case nil:
	case TicketInternal:
		target.SetInternal(PersonToProto(value17.Internal))
	case *TicketInternal:
		if value17 != nil {
			target.SetInternal(PersonToProto(value17.Internal))
		}
	default:
		return nil, errors.New("unsupported oneof implementation")
	}
	var struct18 *structpb.Struct
	if source.StructData != nil {
		mapped19, err := structpb.NewStruct(source.StructData)
		if err != nil {
			return nil, err
		}
		struct18 = mapped19
	}
	target.SetStructData(struct18)
	return target, nil
}

func (t Ticket) ToProto() (*yirapbv1.Ticket, error) {
	return TicketToProto(t)
}

func TicketAuditEventFromProto(source *yirapbv1.Ticket_AuditEvent) TicketAuditEvent {
	var target TicketAuditEvent
	if source == nil {
		return target
	}
	target.Actor = source.GetActor()
	target.Status = TicketStatus(source.GetStatus())
	return target
}

func TicketAuditEventToProto(source TicketAuditEvent) *yirapbv1.Ticket_AuditEvent {
	target := new(yirapbv1.Ticket_AuditEvent)
	target.SetActor(source.Actor)
	target.SetStatus(yirapbv1.TicketStatus(source.Status))
	return target
}

func (tae TicketAuditEvent) ToProto() *yirapbv1.Ticket_AuditEvent {
	return TicketAuditEventToProto(tae)
}

func TicketHistoryFromProto(source *yirapbv1.Ticket_History) TicketHistory {
	var target TicketHistory
	if source == nil {
		return target
	}
	items1 := make([]TicketHistoryEntry, 0, len(source.GetEntries()))
	for _, item2 := range source.GetEntries() {
		items1 = append(items1, TicketHistoryEntryFromProto(item2))
	}
	target.Entries = items1
	return target
}

func TicketHistoryToProto(source TicketHistory) *yirapbv1.Ticket_History {
	target := new(yirapbv1.Ticket_History)
	items1 := make([]*yirapbv1.Ticket_History_Entry, 0, len(source.Entries))
	for _, item2 := range source.Entries {
		items1 = append(items1, TicketHistoryEntryToProto(item2))
	}
	target.SetEntries(items1)
	return target
}

func (th TicketHistory) ToProto() *yirapbv1.Ticket_History {
	return TicketHistoryToProto(th)
}

func TicketHistoryEntryFromProto(source *yirapbv1.Ticket_History_Entry) TicketHistoryEntry {
	var target TicketHistoryEntry
	if source == nil {
		return target
	}
	target.Note = source.GetNote()
	target.Visibility = TicketVisibility(source.GetVisibility())
	return target
}

func TicketHistoryEntryToProto(source TicketHistoryEntry) *yirapbv1.Ticket_History_Entry {
	target := new(yirapbv1.Ticket_History_Entry)
	target.SetNote(source.Note)
	target.SetVisibility(yirapbv1.Ticket_Visibility(source.Visibility))
	return target
}

func (the TicketHistoryEntry) ToProto() *yirapbv1.Ticket_History_Entry {
	return TicketHistoryEntryToProto(the)
}

func UpdateTicketRequestFromProto(source *yirapbv1.UpdateTicketRequest) UpdateTicketRequest {
	var target UpdateTicketRequest
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	target.Input = TicketInputFromProto(source.GetInput())
	return target
}

func UpdateTicketRequestToProto(source UpdateTicketRequest) *yirapbv1.UpdateTicketRequest {
	target := new(yirapbv1.UpdateTicketRequest)
	target.SetId(source.ID)
	target.SetInput(TicketInputToProto(source.Input))
	return target
}

func (utr UpdateTicketRequest) ToProto() *yirapbv1.UpdateTicketRequest {
	return UpdateTicketRequestToProto(utr)
}

func TicketInputFromProto(source *yirapbv1.TicketInput) TicketInput {
	var target TicketInput
	if source == nil {
		return target
	}
	if source.HasTitle() {
		target.Title = omittable.Some(source.GetTitle())
	} else {
		target.Title = omittable.None[string]()
	}
	if source.HasDescription() {
		target.Description = omittable.Some(source.GetDescription())
	} else {
		target.Description = omittable.None[string]()
	}
	if source.HasStatus() {
		target.Status = omittable.Some(TicketStatus(source.GetStatus()))
	} else {
		target.Status = omittable.None[TicketStatus]()
	}
	if source.HasAssignee() {
		var nullable1 *Person
		if source.GetAssignee() != nil {
			nullable1 = new(PersonFromProto(source.GetAssignee()))
		}
		target.Assignee = omittable.Some(nullable1)
	} else {
		target.Assignee = omittable.None[*Person]()
	}
	target.Version = source.GetVersion()
	return target
}

func TicketInputToProto(source TicketInput) *yirapbv1.TicketInput {
	target := new(yirapbv1.TicketInput)
	if source.Title.Valid {
		target.SetTitle(source.Title.Value)
	}
	if source.Description.Valid {
		target.SetDescription(source.Description.Value)
	}
	if source.Status.Valid {
		target.SetStatus(yirapbv1.TicketStatus(source.Status.Value))
	}
	if source.Assignee.Valid {
		var nullable1 *yirapbv1.Person
		if source.Assignee.Value != nil {
			nullable1 = new(yirapbv1.Person)
			nullable1 = PersonToProto(*source.Assignee.Value)
		} else {
		}
		target.SetAssignee(nullable1)
	}
	target.SetVersion(source.Version)
	return target
}

func (ti TicketInput) ToProto() *yirapbv1.TicketInput {
	return TicketInputToProto(ti)
}

func PersonFromProto(source *yirapbv1.Person) Person {
	var target Person
	if source == nil {
		return target
	}
	target.FirstName = source.GetFirstName()
	target.LastName = source.GetLastName()
	return target
}

func PersonToProto(source Person) *yirapbv1.Person {
	target := new(yirapbv1.Person)
	target.SetFirstName(source.FirstName)
	target.SetLastName(source.LastName)
	return target
}

func (p Person) ToProto() *yirapbv1.Person {
	return PersonToProto(p)
}
