// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/options.proto

package optionspbv1

import (
	_ "github.com/seeruk/tego/tegopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_VIEWER      Role = 1
	Role_ROLE_EDITOR      Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_VIEWER",
		2: "ROLE_EDITOR",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_VIEWER":      1,
		"ROLE_EDITOR":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_options_v1_options_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_options_v1_options_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type LookupAccountRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccountId   *string                `protobuf:"bytes,1,opt,name=account_id,json=accountId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LookupAccountRequest) Reset() {
	*x = LookupAccountRequest{}
	mi := &file_options_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountRequest) ProtoMessage() {}

func (x *LookupAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LookupAccountRequest) GetAccountId() string {
	if x != nil {
		if x.xxx_hidden_AccountId != nil {
			return *x.xxx_hidden_AccountId
		}
		return ""
	}
	return ""
}

func (x *LookupAccountRequest) SetAccountId(v string) {
	x.xxx_hidden_AccountId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LookupAccountRequest) HasAccountId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LookupAccountRequest) ClearAccountId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccountId = nil
}

type LookupAccountRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccountId *string
}

func (b0 LookupAccountRequest_builder) Build() *LookupAccountRequest {
	m0 := &LookupAccountRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccountId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_AccountId = b.AccountId
	}
	return m0
}

type LookupAccountResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Account *Account               `protobuf:"bytes,1,opt,name=account"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LookupAccountResponse) Reset() {
	*x = LookupAccountResponse{}
	mi := &file_options_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAccountResponse) ProtoMessage() {}

func (x *LookupAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LookupAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.xxx_hidden_Account
	}
	return nil
}

func (x *LookupAccountResponse) SetAccount(v *Account) {
	x.xxx_hidden_Account = v
}

func (x *LookupAccountResponse) HasAccount() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Account != nil
}

func (x *LookupAccountResponse) ClearAccount() {
	x.xxx_hidden_Account = nil
}

type LookupAccountResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Account *Account
}

func (b0 LookupAccountResponse_builder) Build() *LookupAccountResponse {
	m0 := &LookupAccountResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Account = b.Account
	return m0
}

type Account struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_DisplayName  *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName"`
	xxx_hidden_Email        *string                `protobuf:"bytes,3,opt,name=email"`
	xxx_hidden_Role         Role                   `protobuf:"varint,4,opt,name=role,enum=options.v1.Role"`
	xxx_hidden_InternalNote *string                `protobuf:"bytes,5,opt,name=internal_note,json=internalNote"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_options_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Account) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Account) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *Account) GetRole() Role {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Role
		}
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Account) GetInternalNote() string {
	if x != nil {
		if x.xxx_hidden_InternalNote != nil {
			return *x.xxx_hidden_InternalNote
		}
		return ""
	}
	return ""
}

func (x *Account) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Account) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Account) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Account) SetRole(v Role) {
	x.xxx_hidden_Role = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Account) SetInternalNote(v string) {
	x.xxx_hidden_InternalNote = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Account) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Account) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Account) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Account) HasRole() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Account) HasInternalNote() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Account) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Account) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DisplayName = nil
}

func (x *Account) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Email = nil
}

func (x *Account) ClearRole() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Role = Role_ROLE_UNSPECIFIED
}

func (x *Account) ClearInternalNote() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_InternalNote = nil
}

type Account_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *string
	DisplayName  *string
	Email        *string
	Role         *Role
	InternalNote *string
}

func (b0 Account_builder) Build() *Account {
	m0 := &Account{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Email = b.Email
	}
	if b.Role != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Role = *b.Role
	}
	if b.InternalNote != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_InternalNote = b.InternalNote
	}
	return m0
}

type AccountPatch struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,1,opt,name=display_name,json=displayName"`
	xxx_hidden_Email       *NullableString        `protobuf:"bytes,2,opt,name=email"`
	xxx_hidden_Role        Role                   `protobuf:"varint,3,opt,name=role,enum=options.v1.Role"`
	xxx_hidden_Metadata    *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata"`
	xxx_hidden_ActorId     *string                `protobuf:"bytes,5,opt,name=actor_id,json=actorId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AccountPatch) Reset() {
	*x = AccountPatch{}
	mi := &file_options_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPatch) ProtoMessage() {}

func (x *AccountPatch) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccountPatch) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *AccountPatch) GetEmail() *NullableString {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return nil
}

func (x *AccountPatch) GetRole() Role {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Role
		}
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *AccountPatch) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AccountPatch) GetActorId() string {
	if x != nil {
		if x.xxx_hidden_ActorId != nil {
			return *x.xxx_hidden_ActorId
		}
		return ""
	}
	return ""
}

func (x *AccountPatch) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *AccountPatch) SetEmail(v *NullableString) {
	x.xxx_hidden_Email = v
}

func (x *AccountPatch) SetRole(v Role) {
	x.xxx_hidden_Role = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *AccountPatch) SetMetadata(v *structpb.Struct) {
	x.xxx_hidden_Metadata = v
}

func (x *AccountPatch) SetActorId(v string) {
	x.xxx_hidden_ActorId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *AccountPatch) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccountPatch) HasEmail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Email != nil
}

func (x *AccountPatch) HasRole() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccountPatch) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AccountPatch) HasActorId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccountPatch) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DisplayName = nil
}

func (x *AccountPatch) ClearEmail() {
	x.xxx_hidden_Email = nil
}

func (x *AccountPatch) ClearRole() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Role = Role_ROLE_UNSPECIFIED
}

func (x *AccountPatch) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *AccountPatch) ClearActorId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ActorId = nil
}

type AccountPatch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DisplayName *string
	Email       *NullableString
	Role        *Role
	Metadata    *structpb.Struct
	ActorId     *string
}

func (b0 AccountPatch_builder) Build() *AccountPatch {
	m0 := &AccountPatch{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	x.xxx_hidden_Email = b.Email
	if b.Role != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Role = *b.Role
	}
	x.xxx_hidden_Metadata = b.Metadata
	if b.ActorId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ActorId = b.ActorId
	}
	return m0
}

type AccountMetrics struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventCount       int64                  `protobuf:"varint,1,opt,name=event_count,json=eventCount"`
	xxx_hidden_ByteCount        uint64                 `protobuf:"varint,2,opt,name=byte_count,json=byteCount"`
	xxx_hidden_ApproximateCount int64                  `protobuf:"varint,3,opt,name=approximate_count,json=approximateCount"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AccountMetrics) Reset() {
	*x = AccountMetrics{}
	mi := &file_options_v1_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMetrics) ProtoMessage() {}

func (x *AccountMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccountMetrics) GetEventCount() int64 {
	if x != nil {
		return x.xxx_hidden_EventCount
	}
	return 0
}

func (x *AccountMetrics) GetByteCount() uint64 {
	if x != nil {
		return x.xxx_hidden_ByteCount
	}
	return 0
}

func (x *AccountMetrics) GetApproximateCount() int64 {
	if x != nil {
		return x.xxx_hidden_ApproximateCount
	}
	return 0
}

func (x *AccountMetrics) SetEventCount(v int64) {
	x.xxx_hidden_EventCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AccountMetrics) SetByteCount(v uint64) {
	x.xxx_hidden_ByteCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AccountMetrics) SetApproximateCount(v int64) {
	x.xxx_hidden_ApproximateCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AccountMetrics) HasEventCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccountMetrics) HasByteCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccountMetrics) HasApproximateCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccountMetrics) ClearEventCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EventCount = 0
}

func (x *AccountMetrics) ClearByteCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ByteCount = 0
}

func (x *AccountMetrics) ClearApproximateCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ApproximateCount = 0
}

type AccountMetrics_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventCount       *int64
	ByteCount        *uint64
	ApproximateCount *int64
}

func (b0 AccountMetrics_builder) Build() *AccountMetrics {
	m0 := &AccountMetrics{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EventCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EventCount = *b.EventCount
	}
	if b.ByteCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ByteCount = *b.ByteCount
	}
	if b.ApproximateCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ApproximateCount = *b.ApproximateCount
	}
	return m0
}

type LegacyCounter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count       int64                  `protobuf:"varint,1,opt,name=count"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LegacyCounter) Reset() {
	*x = LegacyCounter{}
	mi := &file_options_v1_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyCounter) ProtoMessage() {}

func (x *LegacyCounter) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LegacyCounter) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *LegacyCounter) SetCount(v int64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LegacyCounter) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LegacyCounter) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Count = 0
}

type LegacyCounter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Count *int64
}

func (b0 LegacyCounter_builder) Build() *LegacyCounter {
	m0 := &LegacyCounter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Count = *b.Count
	}
	return m0
}

type NullableString struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isNullableString_Value `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	mi := &file_options_v1_options_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_options_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NullableString) GetText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullableString_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *NullableString) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*nullableString_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *NullableString) SetText(v string) {
	x.xxx_hidden_Value = &nullableString_Text{v}
}

func (x *NullableString) SetNull(v structpb.NullValue) {
	x.xxx_hidden_Value = &nullableString_Null{v}
}

func (x *NullableString) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *NullableString) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullableString_Text)
	return ok
}

func (x *NullableString) HasNull() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*nullableString_Null)
	return ok
}

func (x *NullableString) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *NullableString) ClearText() {
	if _, ok := x.xxx_hidden_Value.(*nullableString_Text); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *NullableString) ClearNull() {
	if _, ok := x.xxx_hidden_Value.(*nullableString_Null); ok {
		x.xxx_hidden_Value = nil
	}
}

const NullableString_Value_not_set_case case_NullableString_Value = 0
const NullableString_Text_case case_NullableString_Value = 1
const NullableString_Null_case case_NullableString_Value = 2

func (x *NullableString) WhichValue() case_NullableString_Value {
	if x == nil {
		return NullableString_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *nullableString_Text:
		return NullableString_Text_case
	case *nullableString_Null:
		return NullableString_Null_case
	default:
		return NullableString_Value_not_set_case
	}
}

type NullableString_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	Text *string
	Null *structpb.NullValue
	// -- end of xxx_hidden_Value
}

func (b0 NullableString_builder) Build() *NullableString {
	m0 := &NullableString{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		x.xxx_hidden_Value = &nullableString_Text{*b.Text}
	}
	if b.Null != nil {
		x.xxx_hidden_Value = &nullableString_Null{*b.Null}
	}
	return m0
}

type case_NullableString_Value protoreflect.FieldNumber

func (x case_NullableString_Value) String() string {
	md := file_options_v1_options_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNullableString_Value interface {
	isNullableString_Value()
}

type nullableString_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,oneof"`
}

type nullableString_Null struct {
	Null structpb.NullValue `protobuf:"varint,2,opt,name=null,enum=google.protobuf.NullValue,oneof"`
}

func (*nullableString_Text) isNullableString_Value() {}

func (*nullableString_Null) isNullableString_Value() {}

var File_options_v1_options_proto protoreflect.FileDescriptor

const file_options_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x18options/v1/options.proto\x12\n" +
	"options.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12tego/options.proto\"5\n" +
	"\x14LookupAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"F\n" +
	"\x15LookupAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.options.v1.AccountR\aaccount\"\xd5\x02\n" +
	"\aAccount\x12\\\n" +
	"\x02id\x18\x01 \x01(\tBL҅\n" +
	"H\n" +
	"\x02ID\x12$ID is the stable account identifier.*\x14\n" +
	"\bvalidate\x12\brequired2\x06\n" +
	"\x02id\x10\x01R\x02id\x129\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x16҅\n" +
	"\x122\x10\n" +
	"\fdisplay_name\x10\x01R\vdisplayName\x12\x1c\n" +
	"\x05email\x18\x03 \x01(\tB\x06҅\n" +
	"\x02@\x01R\x05email\x12$\n" +
	"\x04role\x18\x04 \x01(\x0e2\x10.options.v1.RoleR\x04role\x12+\n" +
	"\rinternal_note\x18\x05 \x01(\tB\x06҅\n" +
	"\x02 \x01R\finternalNote:@҅\n" +
	"<\n" +
	"\vUserAccount\x12-UserAccount is the hand-facing account shape.\"\xed\x01\n" +
	"\fAccountPatch\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x120\n" +
	"\x05email\x18\x02 \x01(\v2\x1a.options.v1.NullableStringR\x05email\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.options.v1.RoleR\x04role\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12!\n" +
	"\bactor_id\x18\x05 \x01(\tB\x06҅\n" +
	"\x028\x00R\aactorId:\n" +
	"҅\n" +
	"\x06*\x04\b\x01\x18\x03\"\x91\x01\n" +
	"\x0eAccountMetrics\x12\x1f\n" +
	"\vevent_count\x18\x01 \x01(\x03R\n" +
	"eventCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x02 \x01(\x04R\tbyteCount\x123\n" +
	"\x11approximate_count\x18\x03 \x01(\x03B\x06҅\n" +
	"\x02H\x00R\x10approximateCount:\n" +
	"҅\n" +
	"\x06*\x04\x10\x01\x18\x00\"-\n" +
	"\rLegacyCounter\x12\x1c\n" +
	"\x05count\x18\x01 \x01(\x03B\x06҅\n" +
	"\x02H\x01R\x05count\"a\n" +
	"\x0eNullableString\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x120\n" +
	"\x04null\x18\x02 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04nullB\a\n" +
	"\x05value*\xf1\x01\n" +
	"\x04Role\x12\x1c\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x1a\x06҅\n" +
	"\x02\x18\x01\x12J\n" +
	"\vROLE_VIEWER\x10\x01\x1a9҅\n" +
	"5\n" +
	"\x10AccessRoleViewer\x12\x1fAccessRoleViewer can read data.(\n" +
	"\x12)\n" +
	"\vROLE_EDITOR\x10\x02\x1a\x18҅\n" +
	"\x14\n" +
	"\x10AccessRoleEditor(\x14\x1aT҅\n" +
	"P\n" +
	"\n" +
	"AccessRole\x12@AccessRole is an int-backed enum with explicit generated values. \x022\x86\x02\n" +
	"\x0eAccountService\x12\x85\x01\n" +
	"\rLookupAccount\x12 .options.v1.LookupAccountRequest\x1a!.options.v1.LookupAccountResponse\"/҅\n" +
	"+\n" +
	"\x04Find\x12\x1fFind fetches one account by ID. \x01(\x01\x1al҅\n" +
	"h\n" +
	"\bAccounts\x12ZAccounts is the facade service name this schema would generate when RPC output is enabled.\x18\x00B\x84\x01҅\n" +
	"?\n" +
	"7github.com/seeruk/tego/examples/options/options;options\"\x04\n" +
	"\x02\b\x01Z?github.com/seeruk/tego/examples/options/optionspbv1;optionspbv1b\beditionsp\xe9\a"

var file_options_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_options_v1_options_proto_goTypes = []any{
	(Role)(0),                     // 0: options.v1.Role
	(*LookupAccountRequest)(nil),  // 1: options.v1.LookupAccountRequest
	(*LookupAccountResponse)(nil), // 2: options.v1.LookupAccountResponse
	(*Account)(nil),               // 3: options.v1.Account
	(*AccountPatch)(nil),          // 4: options.v1.AccountPatch
	(*AccountMetrics)(nil),        // 5: options.v1.AccountMetrics
	(*LegacyCounter)(nil),         // 6: options.v1.LegacyCounter
	(*NullableString)(nil),        // 7: options.v1.NullableString
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(structpb.NullValue)(0),       // 9: google.protobuf.NullValue
}
var file_options_v1_options_proto_depIdxs = []int32{
	3, // 0: options.v1.LookupAccountResponse.account:type_name -> options.v1.Account
	0, // 1: options.v1.Account.role:type_name -> options.v1.Role
	7, // 2: options.v1.AccountPatch.email:type_name -> options.v1.NullableString
	0, // 3: options.v1.AccountPatch.role:type_name -> options.v1.Role
	8, // 4: options.v1.AccountPatch.metadata:type_name -> google.protobuf.Struct
	9, // 5: options.v1.NullableString.null:type_name -> google.protobuf.NullValue
	1, // 6: options.v1.AccountService.LookupAccount:input_type -> options.v1.LookupAccountRequest
	2, // 7: options.v1.AccountService.LookupAccount:output_type -> options.v1.LookupAccountResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_options_v1_options_proto_init() }
func file_options_v1_options_proto_init() {
	if File_options_v1_options_proto != nil {
		return
	}
	file_options_v1_options_proto_msgTypes[6].OneofWrappers = []any{
		(*nullableString_Text)(nil),
		(*nullableString_Null)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_options_proto_rawDesc), len(file_options_v1_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_options_v1_options_proto_goTypes,
		DependencyIndexes: file_options_v1_options_proto_depIdxs,
		EnumInfos:         file_options_v1_options_proto_enumTypes,
		MessageInfos:      file_options_v1_options_proto_msgTypes,
	}.Build()
	File_options_v1_options_proto = out.File
	file_options_v1_options_proto_goTypes = nil
	file_options_v1_options_proto_depIdxs = nil
}
