// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: custom/v1/custom.proto

package custompbv1

import (
	_ "github.com/seeruk/tego/tegopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *string                `protobuf:"bytes,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_custom_v1_custom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_custom_v1_custom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UUID) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *UUID) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *UUID) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UUID) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

type UUID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *string
}

func (b0 UUID_builder) Build() *UUID {
	m0 := &UUID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type EmailAddress struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *string                `protobuf:"bytes,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_custom_v1_custom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_custom_v1_custom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EmailAddress) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *EmailAddress) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EmailAddress) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EmailAddress) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

type EmailAddress_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *string
}

func (b0 EmailAddress_builder) Build() *EmailAddress {
	m0 := &EmailAddress{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type Customer struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *UUID                  `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Email          *EmailAddress          `protobuf:"bytes,2,opt,name=email"`
	xxx_hidden_CreditCents    int64                  `protobuf:"varint,3,opt,name=credit_cents,json=creditCents"`
	xxx_hidden_DisplayName    *string                `protobuf:"bytes,4,opt,name=display_name,json=displayName"`
	xxx_hidden_Labels         []string               `protobuf:"bytes,5,rep,name=labels"`
	xxx_hidden_ContactAliases []string               `protobuf:"bytes,6,rep,name=contact_aliases,json=contactAliases"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_custom_v1_custom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_custom_v1_custom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Customer) GetId() *UUID {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Customer) GetEmail() *EmailAddress {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return nil
}

func (x *Customer) GetCreditCents() int64 {
	if x != nil {
		return x.xxx_hidden_CreditCents
	}
	return 0
}

func (x *Customer) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *Customer) GetLabels() []string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Customer) GetContactAliases() []string {
	if x != nil {
		return x.xxx_hidden_ContactAliases
	}
	return nil
}

func (x *Customer) SetId(v *UUID) {
	x.xxx_hidden_Id = v
}

func (x *Customer) SetEmail(v *EmailAddress) {
	x.xxx_hidden_Email = v
}

func (x *Customer) SetCreditCents(v int64) {
	x.xxx_hidden_CreditCents = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Customer) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Customer) SetLabels(v []string) {
	x.xxx_hidden_Labels = v
}

func (x *Customer) SetContactAliases(v []string) {
	x.xxx_hidden_ContactAliases = v
}

func (x *Customer) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *Customer) HasEmail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Email != nil
}

func (x *Customer) HasCreditCents() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Customer) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Customer) ClearId() {
	x.xxx_hidden_Id = nil
}

func (x *Customer) ClearEmail() {
	x.xxx_hidden_Email = nil
}

func (x *Customer) ClearCreditCents() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreditCents = 0
}

func (x *Customer) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DisplayName = nil
}

type Customer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *UUID
	Email          *EmailAddress
	CreditCents    *int64
	DisplayName    *string
	Labels         []string
	ContactAliases []string
}

func (b0 Customer_builder) Build() *Customer {
	m0 := &Customer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Email = b.Email
	if b.CreditCents != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_CreditCents = *b.CreditCents
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_ContactAliases = b.ContactAliases
	return m0
}

var File_custom_v1_custom_proto protoreflect.FileDescriptor

const file_custom_v1_custom_proto_rawDesc = "" +
	"\n" +
	"\x16custom/v1/custom.proto\x12\tcustom.v1\x1a\x12tego/options.proto\"\xe4\x01\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\xc5\x01҅\n" +
	"\xc0\x01\x1a\xbd\x01\n" +
	"7github.com/seeruk/tego/examples/custom-types/types.UUID\x12@github.com/seeruk/tego/examples/custom-types/types.UUIDFromProto\x1a>github.com/seeruk/tego/examples/custom-types/types.UUIDToProto \x01\"\xf8\x01\n" +
	"\fEmailAddress\x12\xdf\x01\n" +
	"\x05value\x18\x01 \x01(\tB\xc8\x01҅\n" +
	"\xc3\x01\x1a\xc0\x01\n" +
	"8github.com/seeruk/tego/examples/custom-types/types.Email\x12Agithub.com/seeruk/tego/examples/custom-types/types.EmailFromProto\x1a?github.com/seeruk/tego/examples/custom-types/types.EmailToProto \x01R\x05value:\x06҅\n" +
	"\x028\x01\"\xbf\t\n" +
	"\bCustomer\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.custom.v1.UUIDR\x02id\x12-\n" +
	"\x05email\x18\x02 \x01(\v2\x17.custom.v1.EmailAddressR\x05email\x12\xec\x01\n" +
	"\fcredit_cents\x18\x03 \x01(\x03B\xc8\x01҅\n" +
	"\xc3\x01\x1a\xc0\x01\n" +
	"8github.com/seeruk/tego/examples/custom-types/types.Money\x12Agithub.com/seeruk/tego/examples/custom-types/types.MoneyFromProto\x1a?github.com/seeruk/tego/examples/custom-types/types.MoneyToProto \x01R\vcreditCents\x12\xfe\x01\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\xda\x01҅\n" +
	"\xd5\x01\x1a\xd2\x01\n" +
	">github.com/seeruk/tego/examples/custom-types/types.DisplayName\x12Ggithub.com/seeruk/tego/examples/custom-types/types.DisplayNameFromProto\x1aEgithub.com/seeruk/tego/examples/custom-types/types.DisplayNameToProto(\x01R\vdisplayName\x12\xa7\x02\n" +
	"\x06labels\x18\x05 \x03(\tB\x8e\x02҅\n" +
	"\x89\x02\x1a\x86\x02\n" +
	"9github.com/seeruk/tego/examples/custom-types/types.Set[T]\x12Dgithub.com/seeruk/tego/examples/custom-types/types.LabelSetFromProto\x1aBgithub.com/seeruk/tego/examples/custom-types/types.LabelSetToProto2?\n" +
	"\x01T\x12:\n" +
	"8github.com/seeruk/tego/examples/custom-types/types.LabelR\x06labels\x12\xc8\x02\n" +
	"\x0fcontact_aliases\x18\x06 \x03(\tB\x9e\x02҅\n" +
	"\x99\x02\x1a\x96\x02\n" +
	"=github.com/seeruk/tego/examples/custom-types/types.Box[*[]*T]\x12Jgithub.com/seeruk/tego/examples/custom-types/types.ContactAliasesFromProto\x1aHgithub.com/seeruk/tego/examples/custom-types/types.ContactAliasesToProto2?\n" +
	"\x01T\x12:\n" +
	"8github.com/seeruk/tego/examples/custom-types/types.EmailR\x0econtactAliasesB\x84\x01҅\n" +
	"<\n" +
	":github.com/seeruk/tego/examples/custom-types/custom;customZBgithub.com/seeruk/tego/examples/custom-types/custompbv1;custompbv1b\beditionsp\xe9\a"

var file_custom_v1_custom_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_custom_v1_custom_proto_goTypes = []any{
	(*UUID)(nil),         // 0: custom.v1.UUID
	(*EmailAddress)(nil), // 1: custom.v1.EmailAddress
	(*Customer)(nil),     // 2: custom.v1.Customer
}
var file_custom_v1_custom_proto_depIdxs = []int32{
	0, // 0: custom.v1.Customer.id:type_name -> custom.v1.UUID
	1, // 1: custom.v1.Customer.email:type_name -> custom.v1.EmailAddress
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_custom_v1_custom_proto_init() }
func file_custom_v1_custom_proto_init() {
	if File_custom_v1_custom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_custom_v1_custom_proto_rawDesc), len(file_custom_v1_custom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_custom_v1_custom_proto_goTypes,
		DependencyIndexes: file_custom_v1_custom_proto_depIdxs,
		MessageInfos:      file_custom_v1_custom_proto_msgTypes,
	}.Build()
	File_custom_v1_custom_proto = out.File
	file_custom_v1_custom_proto_goTypes = nil
	file_custom_v1_custom_proto_depIdxs = nil
}
