// Code generated by protoc-gen-tego. DO NOT EDIT.
package shapes

import (
	shapespbv1 "github.com/seeruk/tego/examples/shapes/shapespbv1"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

type Person struct {
	ID          string
	DisplayName string
}

type Project struct {
	Slug           string
	Members        map[string]Person
	Owner          *Person
	Reviewers      []Person
	Aliases        []string
	LocalizedSlugs map[string]string
	PreviousOwners []*Person
	ContactsByRole map[string]*Person
}

func PersonFromProto(source *shapespbv1.Person) Person {
	var target Person
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	target.DisplayName = source.GetDisplayName()
	return target
}

func PersonToProto(source Person) *shapespbv1.Person {
	target := new(shapespbv1.Person)
	target.SetId(source.ID)
	target.SetDisplayName(source.DisplayName)
	return target
}

func (p Person) ToProto() *shapespbv1.Person {
	return PersonToProto(p)
}

func ProjectFromProto(source *shapespbv1.Project) Project {
	var target Project
	if source == nil {
		return target
	}
	var slug string
	if source.GetSlug() != nil {
		slug = source.GetSlug().GetValue()
	}
	target.Slug = slug
	var members map[string]Person
	if source.GetMembers() != nil {
		membersEntries := source.GetMembers().GetEntries()
		members = make(map[string]Person, len(membersEntries))
		for _, membersEntry := range membersEntries {
			members[membersEntry.GetKey()] = PersonFromProto(membersEntry.GetValue())
		}
	} else {
		members = make(map[string]Person)
	}
	target.Members = members
	var owner *Person
	if source.GetOwner() != nil && source.GetOwner().WhichValue() == shapespbv1.NullablePerson_Person_case {
		owner = new(PersonFromProto(source.GetOwner().GetPerson()))
	}
	target.Owner = owner
	var reviewersSourceItems []*shapespbv1.Person
	if source.GetReviewers() != nil {
		reviewersSourceItems = source.GetReviewers().GetPeople()
	}
	reviewers := make([]Person, len(reviewersSourceItems))
	for reviewersIndex, reviewersItem := range reviewersSourceItems {
		reviewers[reviewersIndex] = PersonFromProto(reviewersItem)
	}
	target.Reviewers = reviewers
	aliases := make([]string, len(source.GetAliases()))
	for aliasesIndex, aliasesItem := range source.GetAliases() {
		var aliasesItemTego string
		if aliasesItem != nil {
			aliasesItemTego = aliasesItem.GetValue()
		}
		aliases[aliasesIndex] = aliasesItemTego
	}
	target.Aliases = aliases
	localizedSlugs := make(map[string]string, len(source.GetLocalizedSlugs()))
	for localizedSlugsKey, localizedSlugsValue := range source.GetLocalizedSlugs() {
		var localizedSlugsValueTego string
		if localizedSlugsValue != nil {
			localizedSlugsValueTego = localizedSlugsValue.GetValue()
		}
		localizedSlugs[localizedSlugsKey] = localizedSlugsValueTego
	}
	target.LocalizedSlugs = localizedSlugs
	previousOwners := make([]*Person, len(source.GetPreviousOwners()))
	for previousOwnersIndex, previousOwnersItem := range source.GetPreviousOwners() {
		var previousOwnersItemTego *Person
		if previousOwnersItem != nil && previousOwnersItem.WhichValue() == shapespbv1.NullablePerson_Person_case {
			previousOwnersItemTego = new(PersonFromProto(previousOwnersItem.GetPerson()))
		}
		previousOwners[previousOwnersIndex] = previousOwnersItemTego
	}
	target.PreviousOwners = previousOwners
	contactsByRole := make(map[string]*Person, len(source.GetContactsByRole()))
	for contactsByRoleKey, contactsByRoleValue := range source.GetContactsByRole() {
		var contactsByRoleValueTego *Person
		if contactsByRoleValue != nil && contactsByRoleValue.WhichValue() == shapespbv1.NullablePerson_Person_case {
			contactsByRoleValueTego = new(PersonFromProto(contactsByRoleValue.GetPerson()))
		}
		contactsByRole[contactsByRoleKey] = contactsByRoleValueTego
	}
	target.ContactsByRole = contactsByRole
	return target
}

func ProjectToProto(source Project) *shapespbv1.Project {
	target := new(shapespbv1.Project)
	slug := new(shapespbv1.ProjectSlug)
	slug.SetValue(source.Slug)
	target.SetSlug(slug)
	membersEntries := make([]*shapespbv1.PeopleByTeam_Map, 0, len(source.Members))
	for membersKey, membersValue := range source.Members {
		membersEntry := new(shapespbv1.PeopleByTeam_Map)
		membersEntry.SetKey(membersKey)
		membersEntry.SetValue(PersonToProto(membersValue))
		membersEntries = append(membersEntries, membersEntry)
	}
	members := new(shapespbv1.PeopleByTeam)
	members.SetEntries(membersEntries)
	target.SetMembers(members)
	var owner *shapespbv1.NullablePerson
	if source.Owner != nil {
		owner = new(shapespbv1.NullablePerson)
		owner.SetPerson(PersonToProto(*source.Owner))
	} else {
		owner = new(shapespbv1.NullablePerson)
		owner.SetNull(structpb.NullValue_NULL_VALUE)
	}
	target.SetOwner(owner)
	reviewers := make([]*shapespbv1.Person, len(source.Reviewers))
	for reviewersIndex, reviewersItem := range source.Reviewers {
		reviewers[reviewersIndex] = PersonToProto(reviewersItem)
	}
	reviewers2 := new(shapespbv1.PersonList)
	reviewers2.SetPeople(reviewers)
	target.SetReviewers(reviewers2)
	aliases := make([]*shapespbv1.ProjectSlug, len(source.Aliases))
	for aliasesIndex, aliasesItem := range source.Aliases {
		aliasesItemProto := new(shapespbv1.ProjectSlug)
		aliasesItemProto.SetValue(aliasesItem)
		aliases[aliasesIndex] = aliasesItemProto
	}
	target.SetAliases(aliases)
	localizedSlugs := make(map[string]*shapespbv1.ProjectSlug, len(source.LocalizedSlugs))
	for localizedSlugsKey, localizedSlugsValue := range source.LocalizedSlugs {
		localizedSlugsValueProto := new(shapespbv1.ProjectSlug)
		localizedSlugsValueProto.SetValue(localizedSlugsValue)
		localizedSlugs[localizedSlugsKey] = localizedSlugsValueProto
	}
	target.SetLocalizedSlugs(localizedSlugs)
	previousOwners := make([]*shapespbv1.NullablePerson, len(source.PreviousOwners))
	for previousOwnersIndex, previousOwnersItem := range source.PreviousOwners {
		var previousOwnersItemProto *shapespbv1.NullablePerson
		if previousOwnersItem != nil {
			previousOwnersItemProto = new(shapespbv1.NullablePerson)
			previousOwnersItemProto.SetPerson(PersonToProto(*previousOwnersItem))
		} else {
			previousOwnersItemProto = new(shapespbv1.NullablePerson)
			previousOwnersItemProto.SetNull(structpb.NullValue_NULL_VALUE)
		}
		previousOwners[previousOwnersIndex] = previousOwnersItemProto
	}
	target.SetPreviousOwners(previousOwners)
	contactsByRole := make(map[string]*shapespbv1.NullablePerson, len(source.ContactsByRole))
	for contactsByRoleKey, contactsByRoleValue := range source.ContactsByRole {
		var contactsByRoleValueProto *shapespbv1.NullablePerson
		if contactsByRoleValue != nil {
			contactsByRoleValueProto = new(shapespbv1.NullablePerson)
			contactsByRoleValueProto.SetPerson(PersonToProto(*contactsByRoleValue))
		} else {
			contactsByRoleValueProto = new(shapespbv1.NullablePerson)
			contactsByRoleValueProto.SetNull(structpb.NullValue_NULL_VALUE)
		}
		contactsByRole[contactsByRoleKey] = contactsByRoleValueProto
	}
	target.SetContactsByRole(contactsByRole)
	return target
}

func (p Project) ToProto() *shapespbv1.Project {
	return ProjectToProto(p)
}
