// Code generated by protoc-gen-tego. DO NOT EDIT.
package options

import (
	omittable "github.com/seeruk/go-containers/omittable"
	tego "github.com/seeruk/tego"
	optionspbv1 "github.com/seeruk/tego/examples/options/optionspbv1"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// AccessRole is an int-backed enum with explicit generated values.
type AccessRole int

const (
	// AccessRoleViewer can read data.
	AccessRoleViewer AccessRole = 10
	AccessRoleEditor AccessRole = 20
)

type LookupAccountRequest struct {
	AccountID string
}

type LookupAccountResponse struct {
	Account UserAccount
}

// UserAccount is the hand-facing account shape.
type UserAccount struct {
	// ID is the stable account identifier.
	ID          string `validate:"required" json:"id,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Email       *string
	Role        AccessRole
}

type AccountPatch struct {
	DisplayName omittable.Value[string]
	Email       omittable.Value[*string]
	Role        omittable.Value[AccessRole]
	Metadata    omittable.Value[tego.Struct]
	ActorID     string
}

func LookupAccountRequestFromProto(source *optionspbv1.LookupAccountRequest) LookupAccountRequest {
	var target LookupAccountRequest
	if source == nil {
		return target
	}
	target.AccountID = source.GetAccountId()
	return target
}

func LookupAccountRequestToProto(source LookupAccountRequest) *optionspbv1.LookupAccountRequest {
	target := new(optionspbv1.LookupAccountRequest)
	target.SetAccountId(source.AccountID)
	return target
}

func (lar LookupAccountRequest) ToProto() *optionspbv1.LookupAccountRequest {
	return LookupAccountRequestToProto(lar)
}

func LookupAccountResponseFromProto(source *optionspbv1.LookupAccountResponse) LookupAccountResponse {
	var target LookupAccountResponse
	if source == nil {
		return target
	}
	target.Account = UserAccountFromProto(source.GetAccount())
	return target
}

func LookupAccountResponseToProto(source LookupAccountResponse) *optionspbv1.LookupAccountResponse {
	target := new(optionspbv1.LookupAccountResponse)
	target.SetAccount(UserAccountToProto(source.Account))
	return target
}

func (lar LookupAccountResponse) ToProto() *optionspbv1.LookupAccountResponse {
	return LookupAccountResponseToProto(lar)
}

func UserAccountFromProto(source *optionspbv1.Account) UserAccount {
	var target UserAccount
	if source == nil {
		return target
	}
	target.ID = source.GetId()
	target.DisplayName = source.GetDisplayName()
	var email *string
	if source.HasEmail() {
		email = new(source.GetEmail())
	}
	target.Email = email
	target.Role = AccessRole(source.GetRole())
	return target
}

func UserAccountToProto(source UserAccount) *optionspbv1.Account {
	target := new(optionspbv1.Account)
	target.SetId(source.ID)
	target.SetDisplayName(source.DisplayName)
	if source.Email != nil {
		target.SetEmail(*source.Email)
	}
	target.SetRole(optionspbv1.Role(source.Role))
	return target
}

func (ua UserAccount) ToProto() *optionspbv1.Account {
	return UserAccountToProto(ua)
}

func AccountPatchFromProto(source *optionspbv1.AccountPatch) AccountPatch {
	var target AccountPatch
	if source == nil {
		return target
	}
	if source.HasDisplayName() {
		target.DisplayName = omittable.Of(source.GetDisplayName())
	} else {
		target.DisplayName = omittable.Empty[string]()
	}
	if source.HasEmail() {
		var email *string
		if source.GetEmail() != nil && source.GetEmail().WhichValue() == optionspbv1.NullableString_Text_case {
			email = new(source.GetEmail().GetText())
		}
		target.Email = omittable.Of(email)
	} else {
		target.Email = omittable.Empty[*string]()
	}
	if source.HasRole() {
		target.Role = omittable.Of(AccessRole(source.GetRole()))
	} else {
		target.Role = omittable.Empty[AccessRole]()
	}
	if source.HasMetadata() {
		var metadata tego.Struct
		if source.GetMetadata() != nil {
			metadata = source.GetMetadata().AsMap()
		}
		target.Metadata = omittable.Of(metadata)
	} else {
		target.Metadata = omittable.Empty[tego.Struct]()
	}
	target.ActorID = source.GetActorId()
	return target
}

func AccountPatchToProto(source AccountPatch) (*optionspbv1.AccountPatch, error) {
	target := new(optionspbv1.AccountPatch)
	if source.DisplayName.IsPresent() {
		target.SetDisplayName(source.DisplayName.Get())
	}
	if source.Email.IsPresent() {
		var email *optionspbv1.NullableString
		if source.Email.Get() != nil {
			email = new(optionspbv1.NullableString)
			email.SetText(*source.Email.Get())
		} else {
			email = new(optionspbv1.NullableString)
			email.SetNull(structpb.NullValue_NULL_VALUE)
		}
		target.SetEmail(email)
	}
	if source.Role.IsPresent() {
		target.SetRole(optionspbv1.Role(source.Role.Get()))
	}
	if source.Metadata.IsPresent() {
		var metadata *structpb.Struct
		if source.Metadata.Get() != nil {
			metadata2, err := structpb.NewStruct(source.Metadata.Get())
			if err != nil {
				return nil, err
			}
			metadata = metadata2
		}
		target.SetMetadata(metadata)
	}
	target.SetActorId(source.ActorID)
	return target, nil
}

func (ap AccountPatch) ToProto() (*optionspbv1.AccountPatch, error) {
	return AccountPatchToProto(ap)
}
