// Code generated by protoc-gen-tego. DO NOT EDIT.
package hello

import (
	connect "connectrpc.com/connect"
	context "context"
	fmt "fmt"
	tego "github.com/seeruk/tego"
	hellopbv1 "github.com/seeruk/tego/examples/quickstart/hellopbv1"
	hellopbv1connect "github.com/seeruk/tego/examples/quickstart/hellopbv1/hellopbv1connect"
	grpc "google.golang.org/grpc"
	http "net/http"
)

type SayHelloRequest struct {
	Name string
}

type SayHelloResponse struct {
	Message string
}

func SayHelloRequestToInline(ctx context.Context, request SayHelloRequest) (context.Context, string) {
	return ctx, request.Name
}

func SayHelloRequestFromInline(ctx context.Context, name string) (context.Context, SayHelloRequest) {
	return ctx, SayHelloRequest{Name: name}
}

func SayHelloResponseToInline(response SayHelloResponse, err error) (string, error) {
	if err != nil {
		var zeroMessage string
		return zeroMessage, err
	}
	return response.Message, nil
}

func SayHelloResponseFromInline(message string, err error) (SayHelloResponse, error) {
	if err != nil {
		var zero SayHelloResponse
		return zero, err
	}
	return SayHelloResponse{Message: message}, nil
}

type GreeterService interface {
	SayHello(ctx context.Context, name string) (string, error)
}

type UnimplementedGreeterService struct{}

func (UnimplementedGreeterService) SayHello(ctx context.Context, name string) (string, error) {
	var zeroMessage string
	return zeroMessage, unimplementedGreeterServiceError("SayHello")
}

func unimplementedGreeterServiceError(method string) error {
	return fmt.Errorf("GreeterService.%s: %w", method, tego.ErrUnimplemented)
}

func RegisterGreeterServiceGRPCServer(registrar grpc.ServiceRegistrar, service GreeterService) {
	hellopbv1.RegisterGreeterServiceServer(registrar, NewGreeterServiceGRPCServer(service))
}

func NewGreeterServiceGRPCServer(service GreeterService) hellopbv1.GreeterServiceServer {
	return &greeterServiceGRPCServer{GreeterServiceGRPCAdapter: NewGreeterServiceGRPCAdapter(service)}
}

type greeterServiceGRPCServer struct {
	hellopbv1.UnimplementedGreeterServiceServer
	*GreeterServiceGRPCAdapter
}

type GreeterServiceGRPCAdapter struct {
	service GreeterService
}

func NewGreeterServiceGRPCAdapter(service GreeterService) *GreeterServiceGRPCAdapter {
	return &GreeterServiceGRPCAdapter{service: service}
}

func (s *greeterServiceGRPCServer) SayHello(ctx context.Context, requestProto *hellopbv1.SayHelloRequest) (*hellopbv1.SayHelloResponse, error) {
	return s.AdaptSayHello(ctx, requestProto)
}

func (a *GreeterServiceGRPCAdapter) AdaptSayHello(ctx context.Context, requestProto *hellopbv1.SayHelloRequest) (*hellopbv1.SayHelloResponse, error) {
	request := SayHelloRequestFromProto(requestProto)
	response, err := SayHelloResponseFromInline(a.service.SayHello(SayHelloRequestToInline(ctx, request)))
	if err != nil {
		return nil, tego.GRPCError(err)
	}
	responseProto := SayHelloResponseToProto(response)
	return responseProto, nil
}

func NewGreeterServiceGRPCClient(client hellopbv1.GreeterServiceClient) GreeterService {
	return &greeterServiceGRPCClient{client: client}
}

type greeterServiceGRPCClient struct {
	client hellopbv1.GreeterServiceClient
}

func (c *greeterServiceGRPCClient) SayHello(ctx context.Context, name string) (string, error) {
	var zero SayHelloResponse
	ctx, request := SayHelloRequestFromInline(ctx, name)
	requestProto := SayHelloRequestToProto(request)
	responseProto, err := c.client.SayHello(ctx, requestProto)
	if err != nil {
		return SayHelloResponseToInline(zero, err)
	}
	response := SayHelloResponseFromProto(responseProto)
	return SayHelloResponseToInline(response, nil)
}

func NewGreeterServiceConnectHandler(service GreeterService, opts ...connect.HandlerOption) (string, http.Handler) {
	return hellopbv1connect.NewGreeterServiceHandler(&greeterServiceConnectHandler{GreeterServiceConnectAdapter: NewGreeterServiceConnectAdapter(service)}, opts...)
}

type greeterServiceConnectHandler struct {
	*GreeterServiceConnectAdapter
}

type GreeterServiceConnectAdapter struct {
	service GreeterService
}

func NewGreeterServiceConnectAdapter(service GreeterService) *GreeterServiceConnectAdapter {
	return &GreeterServiceConnectAdapter{service: service}
}

func (s *greeterServiceConnectHandler) SayHello(ctx context.Context, requestProto *connect.Request[hellopbv1.SayHelloRequest]) (*connect.Response[hellopbv1.SayHelloResponse], error) {
	return s.AdaptSayHello(ctx, requestProto)
}

func (a *GreeterServiceConnectAdapter) AdaptSayHello(ctx context.Context, requestProto *connect.Request[hellopbv1.SayHelloRequest]) (*connect.Response[hellopbv1.SayHelloResponse], error) {
	request := SayHelloRequestFromProto(requestProto.Msg)
	response, err := SayHelloResponseFromInline(a.service.SayHello(SayHelloRequestToInline(ctx, request)))
	if err != nil {
		return nil, tego.ConnectError(err)
	}
	responseProto := SayHelloResponseToProto(response)
	return connect.NewResponse(responseProto), nil
}

func NewGreeterServiceConnectClient(client hellopbv1connect.GreeterServiceClient) GreeterService {
	return &greeterServiceConnectClient{client: client}
}

type greeterServiceConnectClient struct {
	client hellopbv1connect.GreeterServiceClient
}

func (c *greeterServiceConnectClient) SayHello(ctx context.Context, name string) (string, error) {
	var zero SayHelloResponse
	ctx, request := SayHelloRequestFromInline(ctx, name)
	requestProto := SayHelloRequestToProto(request)
	responseProto, err := c.client.SayHello(ctx, connect.NewRequest(requestProto))
	if err != nil {
		return SayHelloResponseToInline(zero, err)
	}
	response := SayHelloResponseFromProto(responseProto.Msg)
	return SayHelloResponseToInline(response, nil)
}

func SayHelloRequestFromProto(source *hellopbv1.SayHelloRequest) SayHelloRequest {
	var target SayHelloRequest
	if source == nil {
		return target
	}
	target.Name = source.GetName()
	return target
}

func SayHelloRequestToProto(source SayHelloRequest) *hellopbv1.SayHelloRequest {
	target := new(hellopbv1.SayHelloRequest)
	target.SetName(source.Name)
	return target
}

func (shr SayHelloRequest) ToProto() *hellopbv1.SayHelloRequest {
	return SayHelloRequestToProto(shr)
}

func SayHelloResponseFromProto(source *hellopbv1.SayHelloResponse) SayHelloResponse {
	var target SayHelloResponse
	if source == nil {
		return target
	}
	target.Message = source.GetMessage()
	return target
}

func SayHelloResponseToProto(source SayHelloResponse) *hellopbv1.SayHelloResponse {
	target := new(hellopbv1.SayHelloResponse)
	target.SetMessage(source.Message)
	return target
}

func (shr SayHelloResponse) ToProto() *hellopbv1.SayHelloResponse {
	return SayHelloResponseToProto(shr)
}
